// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    public static class Video
    {
        public static unsafe int XMVDecoder_CreateDecoderForFile(int Flags, string szFileName, IntPtr ppDecoder)
        {
            byte[] szFileNameBytes = szFileName == null ? null : ToAnsi(szFileName);
            fixed (byte* szFileNamePtr = szFileNameBytes)
                return Native.XMVDecoder_CreateDecoderForFile(Flags, (szFileNameBytes == null) ? IntPtr.Zero : (IntPtr)szFileNamePtr, ppDecoder);
        }

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_CreateDecoderForPackets")]
        public static extern int XMVDecoder_CreateDecoderForPackets(int Flags, IntPtr pFirst4096, int Context, IntPtr pfnGetNextPacket, IntPtr pfnReleasePreviousPacket, IntPtr ppDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_CloseDecoder")]
        public static extern void XMVDecoder_CloseDecoder(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetVideoDescriptor")]
        public static extern void XMVDecoder_GetVideoDescriptor(IntPtr pDecoder, IntPtr pVideoDescriptor);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetAudioDescriptor")]
        public static extern void XMVDecoder_GetAudioDescriptor(IntPtr pDecoder, int AudioStream, IntPtr pAudioDescriptor);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_EnableAudioStream")]
        public static extern int XMVDecoder_EnableAudioStream(IntPtr pDecoder, int AudioStream, int Flags, IntPtr pMixBins, IntPtr ppStream);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_DisableAudioStream")]
        public static extern void XMVDecoder_DisableAudioStream(IntPtr pDecoder, int AudioStream);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetAudioStream")]
        public static extern void XMVDecoder_GetAudioStream(IntPtr pDecoder, int AudioStream, IntPtr ppStream);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetSynchronizationStream")]
        public static extern int XMVDecoder_GetSynchronizationStream(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_SetSynchronizationStream")]
        public static extern void XMVDecoder_SetSynchronizationStream(IntPtr pDecoder, int AudioStream);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_Reset")]
        public static extern int XMVDecoder_Reset(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_Play")]
        public static extern int XMVDecoder_Play(IntPtr pDecoder, int Flags, IntPtr pRect);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_TerminateLoop")]
        public static extern void XMVDecoder_TerminateLoop(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_TerminatePlayback")]
        public static extern void XMVDecoder_TerminatePlayback(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_TerminateImmediately")]
        public static extern void XMVDecoder_TerminateImmediately(IntPtr pDecoder);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetNextFrame")]
        public static extern int XMVDecoder_GetNextFrame(IntPtr pDecoder, IntPtr pSurface, IntPtr pResult, IntPtr pTimeOfFrame);

        [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_GetTimeFromStart")]
        public static extern int XMVDecoder_GetTimeFromStart(IntPtr pDecoder);

        static byte[] ToAnsi(string text)
        {
            return Encoding.ASCII.GetBytes(text + "\0");
        }

        static class Native
        {
            [DllImport("xmv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xmv_XMVDecoder_CreateDecoderForFile")]
            public static extern int XMVDecoder_CreateDecoderForFile(int Flags, IntPtr szFileName, IntPtr ppDecoder);

        }
    }
}
