// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    public static class Audio
    {
        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundCreate")]
        public static extern int DirectSoundCreate(IntPtr pguidDeviceId, IntPtr ppDirectSound, IntPtr pUnkOuter);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundCreateBuffer")]
        public static extern int DirectSoundCreateBuffer(IntPtr pdsbd, IntPtr ppBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundCreateStream")]
        public static extern int DirectSoundCreateStream(IntPtr pdssd, IntPtr ppStream);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundDoWork")]
        public static extern void DirectSoundDoWork();

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundUseFullHRTF")]
        public static extern void DirectSoundUseFullHRTF();

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundUseLightHRTF")]
        public static extern void DirectSoundUseLightHRTF();

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundOverrideSpeakerConfig")]
        public static extern void DirectSoundOverrideSpeakerConfig(int dwSpeakerConfig);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundGetSampleTime")]
        public static extern int DirectSoundGetSampleTime();

        public static void DirectSoundDumpMemoryUsage(bool fAssertNone)
        {
            Native.DirectSoundDumpMemoryUsage(fAssertNone ? 1 : 0);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XAudioCreatePcmFormat")]
        public static extern void XAudioCreatePcmFormat(int nChannels, int nSamplesPerSec, int wBitsPerSample, IntPtr pwfx);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XAudioCreateAdpcmFormat")]
        public static extern void XAudioCreateAdpcmFormat(int nChannels, int nSamplesPerSec, IntPtr pwfx);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XAudioCalculatePitch")]
        public static extern int XAudioCalculatePitch(int dwFrequency);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XWmaDecoderCreateMediaObject")]
        public static extern int XWmaDecoderCreateMediaObject(IntPtr pParameters, IntPtr ppMediaObject);

        public static unsafe int WmaCreateDecoder(string pszFileName, IntPtr hFile, bool fAsyncMode, int dwLookaheadBufferSize, int dwMaxPackets, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject)
        {
            byte[] pszFileNameBytes = pszFileName == null ? null : ToAnsi(pszFileName);
            fixed (byte* pszFileNamePtr = pszFileNameBytes)
                return Native.WmaCreateDecoder((pszFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pszFileNamePtr, hFile, fAsyncMode ? 1 : 0, dwLookaheadBufferSize, dwMaxPackets, dwYieldRate, pwfxCompressed, ppMediaObject);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_WmaCreateInMemoryDecoder")]
        public static extern int WmaCreateInMemoryDecoder(IntPtr pfnCallback, IntPtr pvContext, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject);

        public static unsafe int WmaCreateDecoderEx(string pszFileName, IntPtr hFile, bool fAsyncMode, int dwLookaheadBufferSize, int dwMaxPackets, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject)
        {
            byte[] pszFileNameBytes = pszFileName == null ? null : ToAnsi(pszFileName);
            fixed (byte* pszFileNamePtr = pszFileNameBytes)
                return Native.WmaCreateDecoderEx((pszFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pszFileNamePtr, hFile, fAsyncMode ? 1 : 0, dwLookaheadBufferSize, dwMaxPackets, dwYieldRate, pwfxCompressed, ppMediaObject);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_WmaCreateInMemoryDecoderEx")]
        public static extern int WmaCreateInMemoryDecoderEx(IntPtr pfnCallback, IntPtr pvContext, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_Ac97CreateMediaObject")]
        public static extern int Ac97CreateMediaObject(int dwChannel, IntPtr pfnCallback, IntPtr pvContext, IntPtr ppMediaObject);

        public static unsafe int XFileCreateMediaObject(string pszFileName, int dwDesiredAccess, int dwShareMode, int dwCreationDisposition, int dwFlagsAndAttributes, IntPtr ppMediaObject)
        {
            byte[] pszFileNameBytes = pszFileName == null ? null : ToAnsi(pszFileName);
            fixed (byte* pszFileNamePtr = pszFileNameBytes)
                return Native.XFileCreateMediaObject((pszFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pszFileNamePtr, dwDesiredAccess, dwShareMode, dwCreationDisposition, dwFlagsAndAttributes, ppMediaObject);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileCreateMediaObjectEx")]
        public static extern int XFileCreateMediaObjectEx(IntPtr hFile, IntPtr ppMediaObject);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileCreateMediaObjectAsync")]
        public static extern int XFileCreateMediaObjectAsync(IntPtr hFile, int dwMaxPackets, IntPtr ppMediaObject);

        public static unsafe int XWaveFileCreateMediaObject(string pszFileName, IntPtr ppwfxFormat, IntPtr ppMediaObject)
        {
            byte[] pszFileNameBytes = pszFileName == null ? null : ToAnsi(pszFileName);
            fixed (byte* pszFileNamePtr = pszFileNameBytes)
                return Native.XWaveFileCreateMediaObject((pszFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pszFileNamePtr, ppwfxFormat, ppMediaObject);
        }

        public static unsafe int XWaveFileCreateMediaObjectEx(string pszFileName, IntPtr hFile, IntPtr ppMediaObject)
        {
            byte[] pszFileNameBytes = pszFileName == null ? null : ToAnsi(pszFileName);
            fixed (byte* pszFileNamePtr = pszFileNameBytes)
                return Native.XWaveFileCreateMediaObjectEx((pszFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pszFileNamePtr, hFile, ppMediaObject);
        }

        public static unsafe int XAudioDownloadEffectsImage(string pszImageName, IntPtr pImageLoc, int dwFlags, IntPtr ppImageDesc)
        {
            byte[] pszImageNameBytes = pszImageName == null ? null : ToAnsi(pszImageName);
            fixed (byte* pszImageNamePtr = pszImageNameBytes)
                return Native.XAudioDownloadEffectsImage((pszImageNameBytes == null) ? IntPtr.Zero : (IntPtr)pszImageNamePtr, pImageLoc, dwFlags, ppImageDesc);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XAudioSetEffectData")]
        public static extern int XAudioSetEffectData(int dwEffectIndex, IntPtr pDesc, IntPtr pRawDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_QueryInterface")]
        public static extern int IDirectSound_QueryInterface(IntPtr pDirectSound, int iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_QueryInterfaceC")]
        public static extern int IDirectSound_QueryInterfaceC(IntPtr pDirectSound, IntPtr iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_AddRef")]
        public static extern int IDirectSound_AddRef(IntPtr pDirectSound);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_Release")]
        public static extern int IDirectSound_Release(IntPtr pDirectSound);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_GetCaps")]
        public static extern int IDirectSound_GetCaps(IntPtr pDirectSound, IntPtr pdsc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SynchPlayback")]
        public static extern int IDirectSound_SynchPlayback(IntPtr pDirectSound);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_CreateSoundBuffer")]
        public static extern int IDirectSound_CreateSoundBuffer(IntPtr pDirectSound, IntPtr pdsbd, IntPtr ppBuffer, IntPtr pUnkOuter);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_CreateSoundStream")]
        public static extern int IDirectSound_CreateSoundStream(IntPtr pDirectSound, IntPtr pdssd, IntPtr ppStream, IntPtr pUnkOuter);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_GetSpeakerConfig")]
        public static extern int IDirectSound_GetSpeakerConfig(IntPtr pDirectSound, IntPtr pdwSpeakerConfig);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetCooperativeLevel")]
        public static extern int IDirectSound_SetCooperativeLevel(IntPtr pDirectSound, IntPtr hWnd, int dwLevel);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_Compact")]
        public static extern int IDirectSound_Compact(IntPtr pDirectSound);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_DownloadEffectsImage")]
        public static extern int IDirectSound_DownloadEffectsImage(IntPtr pDirectSound, IntPtr pvImageBuffer, int dwImageSize, IntPtr pImageLoc, IntPtr ppImageDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_GetEffectData")]
        public static extern int IDirectSound_GetEffectData(IntPtr pDirectSound, int dwEffectIndex, int dwOffset, IntPtr pvData, int dwDataSize);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetEffectData")]
        public static extern int IDirectSound_SetEffectData(IntPtr pDirectSound, int dwEffectIndex, int dwOffset, IntPtr pvData, int dwDataSize, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_CommitEffectData")]
        public static extern int IDirectSound_CommitEffectData(IntPtr pDirectSound);

        public static int IDirectSound_EnableHeadphones(IntPtr pDirectSound, bool fEnabled)
        {
            return Native.IDirectSound_EnableHeadphones(pDirectSound, fEnabled ? 1 : 0);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetMixBinHeadroom")]
        public static extern int IDirectSound_SetMixBinHeadroom(IntPtr pDirectSound, int dwMixBin, int dwHeadroom);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetAllParameters")]
        public static extern int IDirectSound_SetAllParameters(IntPtr pDirectSound, IntPtr pds3dl, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetOrientation")]
        public static extern int IDirectSound_SetOrientation(IntPtr pDirectSound, float xFront, float yFront, float zFront, float xTop, float yTop, float zTop, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetPosition")]
        public static extern int IDirectSound_SetPosition(IntPtr pDirectSound, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetVelocity")]
        public static extern int IDirectSound_SetVelocity(IntPtr pDirectSound, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetDistanceFactor")]
        public static extern int IDirectSound_SetDistanceFactor(IntPtr pDirectSound, float flDistanceFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetDopplerFactor")]
        public static extern int IDirectSound_SetDopplerFactor(IntPtr pDirectSound, float flDopplerFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetRolloffFactor")]
        public static extern int IDirectSound_SetRolloffFactor(IntPtr pDirectSound, float flRolloffFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_SetI3DL2Listener")]
        public static extern int IDirectSound_SetI3DL2Listener(IntPtr pDirectSound, IntPtr pds3dl, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_CommitDeferredSettings")]
        public static extern int IDirectSound_CommitDeferredSettings(IntPtr pDirectSound);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_GetTime")]
        public static extern int IDirectSound_GetTime(IntPtr pDirectSound, IntPtr prtCurrent);

        public static int IDirectSound_GetOutputLevels(IntPtr pDirectSound, IntPtr pOutputLevels, bool bResetPeakValues)
        {
            return Native.IDirectSound_GetOutputLevels(pDirectSound, pOutputLevels, bResetPeakValues ? 1 : 0);
        }

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_QueryInterface")]
        public static extern int IDirectSoundBuffer_QueryInterface(IntPtr pBuffer, int iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_QueryInterfaceC")]
        public static extern int IDirectSoundBuffer_QueryInterfaceC(IntPtr pBuffer, IntPtr iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_AddRef")]
        public static extern int IDirectSoundBuffer_AddRef(IntPtr pBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Release")]
        public static extern int IDirectSoundBuffer_Release(IntPtr pBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetFormat")]
        public static extern int IDirectSoundBuffer_SetFormat(IntPtr pBuffer, IntPtr pwfxFormat);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetFrequency")]
        public static extern int IDirectSoundBuffer_SetFrequency(IntPtr pBuffer, int dwFrequency);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetVolume")]
        public static extern int IDirectSoundBuffer_SetVolume(IntPtr pBuffer, int lVolume);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetPitch")]
        public static extern int IDirectSoundBuffer_SetPitch(IntPtr pBuffer, int lPitch);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetLFO")]
        public static extern int IDirectSoundBuffer_SetLFO(IntPtr pBuffer, IntPtr pLFODesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetEG")]
        public static extern int IDirectSoundBuffer_SetEG(IntPtr pBuffer, IntPtr pEnvelopeDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetFilter")]
        public static extern int IDirectSoundBuffer_SetFilter(IntPtr pBuffer, IntPtr pFilterDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetHeadroom")]
        public static extern int IDirectSoundBuffer_SetHeadroom(IntPtr pBuffer, int dwHeadroom);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetOutputBuffer")]
        public static extern int IDirectSoundBuffer_SetOutputBuffer(IntPtr pBuffer, IntPtr pOutputBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetMixBins")]
        public static extern int IDirectSoundBuffer_SetMixBins(IntPtr pBuffer, IntPtr pMixBins);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetMixBinVolumes")]
        public static extern int IDirectSoundBuffer_SetMixBinVolumes(IntPtr pBuffer, IntPtr pMixBins);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetAllParameters")]
        public static extern int IDirectSoundBuffer_SetAllParameters(IntPtr pBuffer, IntPtr pds3db, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetConeAngles")]
        public static extern int IDirectSoundBuffer_SetConeAngles(IntPtr pBuffer, int dwInsideConeAngle, int dwOutsideConeAngle, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetConeOrientation")]
        public static extern int IDirectSoundBuffer_SetConeOrientation(IntPtr pBuffer, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetConeOutsideVolume")]
        public static extern int IDirectSoundBuffer_SetConeOutsideVolume(IntPtr pBuffer, int lConeOutsideVolume, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetMaxDistance")]
        public static extern int IDirectSoundBuffer_SetMaxDistance(IntPtr pBuffer, float flMaxDistance, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetMinDistance")]
        public static extern int IDirectSoundBuffer_SetMinDistance(IntPtr pBuffer, float flMinDistance, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetMode")]
        public static extern int IDirectSoundBuffer_SetMode(IntPtr pBuffer, int dwMode, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetPosition")]
        public static extern int IDirectSoundBuffer_SetPosition(IntPtr pBuffer, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetVelocity")]
        public static extern int IDirectSoundBuffer_SetVelocity(IntPtr pBuffer, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetDistanceFactor")]
        public static extern int IDirectSoundBuffer_SetDistanceFactor(IntPtr pBuffer, float flDistanceFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetDopplerFactor")]
        public static extern int IDirectSoundBuffer_SetDopplerFactor(IntPtr pBuffer, float flDopplerFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetRolloffFactor")]
        public static extern int IDirectSoundBuffer_SetRolloffFactor(IntPtr pBuffer, float flRolloffFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetRolloffCurve")]
        public static extern int IDirectSoundBuffer_SetRolloffCurve(IntPtr pBuffer, IntPtr pflPoints, int dwPointCount, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetI3DL2Source")]
        public static extern int IDirectSoundBuffer_SetI3DL2Source(IntPtr pBuffer, IntPtr pds3db, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Play")]
        public static extern int IDirectSoundBuffer_Play(IntPtr pBuffer, int dwReserved1, int dwReserved2, int dwFlags);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_PlayEx")]
        public static extern int IDirectSoundBuffer_PlayEx(IntPtr pBuffer, long rtTimeStamp, int dwFlags);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Stop")]
        public static extern int IDirectSoundBuffer_Stop(IntPtr pBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Pause")]
        public static extern int IDirectSoundBuffer_Pause(IntPtr pBuffer, int dwPause);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_PauseEx")]
        public static extern int IDirectSoundBuffer_PauseEx(IntPtr pBuffer, long rtTimestamp, int dwPause);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_StopEx")]
        public static extern int IDirectSoundBuffer_StopEx(IntPtr pBuffer, long rtTimeStamp, int dwFlags);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetPlayRegion")]
        public static extern int IDirectSoundBuffer_SetPlayRegion(IntPtr pBuffer, int dwPlayStart, int dwPlayLength);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetLoopRegion")]
        public static extern int IDirectSoundBuffer_SetLoopRegion(IntPtr pBuffer, int dwLoopStart, int dwLoopLength);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_GetStatus")]
        public static extern int IDirectSoundBuffer_GetStatus(IntPtr pBuffer, IntPtr pdwStatus);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_GetCurrentPosition")]
        public static extern int IDirectSoundBuffer_GetCurrentPosition(IntPtr pBuffer, IntPtr pdwPlayCursor, IntPtr pdwWriteCursor);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetCurrentPosition")]
        public static extern int IDirectSoundBuffer_SetCurrentPosition(IntPtr pBuffer, int dwPlayCursor);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetBufferData")]
        public static extern int IDirectSoundBuffer_SetBufferData(IntPtr pBuffer, IntPtr pvBufferData, int dwBufferBytes);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Lock")]
        public static extern int IDirectSoundBuffer_Lock(IntPtr pBuffer, int dwOffset, int dwBytes, IntPtr ppvAudioPtr1, IntPtr pdwAudioBytes1, IntPtr ppvAudioPtr2, IntPtr pdwAudioBytes2, int dwFlags);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Unlock")]
        public static extern int IDirectSoundBuffer_Unlock(IntPtr pBuffer, IntPtr pvLock1, int dwLockSize1, IntPtr pvLock2, int dwLockSize2);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_Restore")]
        public static extern int IDirectSoundBuffer_Restore(IntPtr pBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_SetNotificationPositions")]
        public static extern int IDirectSoundBuffer_SetNotificationPositions(IntPtr pBuffer, int dwNotifyCount, IntPtr paNotifies);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundBuffer_GetVoiceProperties")]
        public static extern int IDirectSoundBuffer_GetVoiceProperties(IntPtr pBuffer, IntPtr pVoiceProps);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_QueryInterface")]
        public static extern int IDirectSoundStream_QueryInterface(IntPtr pStream, int iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_QueryInterfaceC")]
        public static extern int IDirectSoundStream_QueryInterfaceC(IntPtr pStream, IntPtr iid, IntPtr ppvInterface);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetFormat")]
        public static extern int IDirectSoundStream_SetFormat(IntPtr pStream, IntPtr pwfxFormat);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetFrequency")]
        public static extern int IDirectSoundStream_SetFrequency(IntPtr pStream, int dwFrequency);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetVolume")]
        public static extern int IDirectSoundStream_SetVolume(IntPtr pStream, int lVolume);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetPitch")]
        public static extern int IDirectSoundStream_SetPitch(IntPtr pStream, int lPitch);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetLFO")]
        public static extern int IDirectSoundStream_SetLFO(IntPtr pStream, IntPtr pLFODesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetEG")]
        public static extern int IDirectSoundStream_SetEG(IntPtr pStream, IntPtr pEnvelopeDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetFilter")]
        public static extern int IDirectSoundStream_SetFilter(IntPtr pStream, IntPtr pFilterDesc);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetHeadroom")]
        public static extern int IDirectSoundStream_SetHeadroom(IntPtr pStream, int dwHeadroom);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetOutputBuffer")]
        public static extern int IDirectSoundStream_SetOutputBuffer(IntPtr pStream, IntPtr pOutputBuffer);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetMixBins")]
        public static extern int IDirectSoundStream_SetMixBins(IntPtr pStream, IntPtr pMixBins);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetMixBinVolumes")]
        public static extern int IDirectSoundStream_SetMixBinVolumes(IntPtr pStream, IntPtr pMixBins);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetAllParameters")]
        public static extern int IDirectSoundStream_SetAllParameters(IntPtr pStream, IntPtr pds3db, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetConeAngles")]
        public static extern int IDirectSoundStream_SetConeAngles(IntPtr pStream, int dwInsideConeAngle, int dwOutsideConeAngle, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetConeOrientation")]
        public static extern int IDirectSoundStream_SetConeOrientation(IntPtr pStream, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetConeOutsideVolume")]
        public static extern int IDirectSoundStream_SetConeOutsideVolume(IntPtr pStream, int lConeOutsideVolume, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetMaxDistance")]
        public static extern int IDirectSoundStream_SetMaxDistance(IntPtr pStream, float flMaxDistance, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetMinDistance")]
        public static extern int IDirectSoundStream_SetMinDistance(IntPtr pStream, float flMinDistance, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetMode")]
        public static extern int IDirectSoundStream_SetMode(IntPtr pStream, int dwMode, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetPosition")]
        public static extern int IDirectSoundStream_SetPosition(IntPtr pStream, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetVelocity")]
        public static extern int IDirectSoundStream_SetVelocity(IntPtr pStream, float x, float y, float z, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetDistanceFactor")]
        public static extern int IDirectSoundStream_SetDistanceFactor(IntPtr pStream, float flDistanceFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetDopplerFactor")]
        public static extern int IDirectSoundStream_SetDopplerFactor(IntPtr pStream, float flDopplerFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetRolloffFactor")]
        public static extern int IDirectSoundStream_SetRolloffFactor(IntPtr pStream, float flRolloffFactor, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetRolloffCurve")]
        public static extern int IDirectSoundStream_SetRolloffCurve(IntPtr pStream, IntPtr pflPoints, int dwPointCount, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_SetI3DL2Source")]
        public static extern int IDirectSoundStream_SetI3DL2Source(IntPtr pStream, IntPtr pds3db, int dwApply);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_Pause")]
        public static extern int IDirectSoundStream_Pause(IntPtr pStream, int dwPause);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_PauseEx")]
        public static extern int IDirectSoundStream_PauseEx(IntPtr pStream, long rtTimestamp, int dwPause);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_FlushEx")]
        public static extern int IDirectSoundStream_FlushEx(IntPtr pStream, long rtTimeStamp, int dwFlags);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSoundStream_GetVoiceProperties")]
        public static extern int IDirectSoundStream_GetVoiceProperties(IntPtr pStream, IntPtr pVoiceProps);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_AddRef")]
        public static extern int XMediaObject_AddRef(IntPtr a0);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_Release")]
        public static extern int XMediaObject_Release(IntPtr a0);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_GetInfo")]
        public static extern int XMediaObject_GetInfo(IntPtr a0, IntPtr a1);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_GetStatus")]
        public static extern int XMediaObject_GetStatus(IntPtr a0, IntPtr a1);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_Process")]
        public static extern int XMediaObject_Process(IntPtr a0, IntPtr a1, IntPtr a2);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_Discontinuity")]
        public static extern int XMediaObject_Discontinuity(IntPtr a0);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XMediaObject_Flush")]
        public static extern int XMediaObject_Flush(IntPtr a0);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileMediaObject_Seek")]
        public static extern int XFileMediaObject_Seek(IntPtr a0, int a1, int a2, IntPtr a3);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileMediaObject_GetLength")]
        public static extern int XFileMediaObject_GetLength(IntPtr a0, IntPtr a1);

        [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileMediaObject_DoWork")]
        public static extern void XFileMediaObject_DoWork(IntPtr a0);

        static byte[] ToAnsi(string text)
        {
            return Encoding.ASCII.GetBytes(text + "\0");
        }

        static class Native
        {
            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_DirectSoundDumpMemoryUsage")]
            public static extern void DirectSoundDumpMemoryUsage(int fAssertNone);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_WmaCreateDecoder")]
            public static extern int WmaCreateDecoder(IntPtr pszFileName, IntPtr hFile, int fAsyncMode, int dwLookaheadBufferSize, int dwMaxPackets, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_WmaCreateDecoderEx")]
            public static extern int WmaCreateDecoderEx(IntPtr pszFileName, IntPtr hFile, int fAsyncMode, int dwLookaheadBufferSize, int dwMaxPackets, int dwYieldRate, IntPtr pwfxCompressed, IntPtr ppMediaObject);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XFileCreateMediaObject")]
            public static extern int XFileCreateMediaObject(IntPtr pszFileName, int dwDesiredAccess, int dwShareMode, int dwCreationDisposition, int dwFlagsAndAttributes, IntPtr ppMediaObject);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XWaveFileCreateMediaObject")]
            public static extern int XWaveFileCreateMediaObject(IntPtr pszFileName, IntPtr ppwfxFormat, IntPtr ppMediaObject);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XWaveFileCreateMediaObjectEx")]
            public static extern int XWaveFileCreateMediaObjectEx(IntPtr pszFileName, IntPtr hFile, IntPtr ppMediaObject);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_XAudioDownloadEffectsImage")]
            public static extern int XAudioDownloadEffectsImage(IntPtr pszImageName, IntPtr pImageLoc, int dwFlags, IntPtr ppImageDesc);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_EnableHeadphones")]
            public static extern int IDirectSound_EnableHeadphones(IntPtr pDirectSound, int fEnabled);

            [DllImport("dsound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dsound_IDirectSound_GetOutputLevels")]
            public static extern int IDirectSound_GetOutputLevels(IntPtr pDirectSound, IntPtr pOutputLevels, int bResetPeakValues);

        }
    }
}
