// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct Xuid
    {
        public long Id;
        public int Flags;
    }

    public static class Voice
    {
        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceQueueCreateMediaObject")]
        public static extern int XVoiceQueueCreateMediaObject(IntPtr pConfig, IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceSynchronizedQueueCreateMediaObject")]
        public static extern int XVoiceSynchronizedQueueCreateMediaObject(IntPtr pConfig, IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateOneToOneEncoder")]
        public static extern int XVoiceCreateOneToOneEncoder(IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateTwoToTwoEncoder")]
        public static extern int XVoiceCreateTwoToTwoEncoder(IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateFourToFourFullEncoder")]
        public static extern int XVoiceCreateFourToFourFullEncoder(IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateFourToFourRoundRobinEncoder")]
        public static extern int XVoiceCreateFourToFourRoundRobinEncoder(IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateOneToOneDecoder")]
        public static extern int XVoiceCreateOneToOneDecoder(IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateFourToFourFullDecoder")]
        public static extern int XVoiceCreateFourToFourFullDecoder(int dwMaxStreams, IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateFourToOneMixingDecoder")]
        public static extern int XVoiceCreateFourToOneMixingDecoder(int dwMaxStreams, IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceCreateTwoToOneMixingDecoder")]
        public static extern int XVoiceCreateTwoToOneMixingDecoder(int dwMaxStreams, IntPtr ppMediaObject);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XVoiceGetEncodedPacketEnergy")]
        public static extern int XVoiceGetEncodedPacketEnergy(IntPtr pPacket, IntPtr pfEnergy);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_AddRef")]
        public static extern int XHVEngine_AddRef(IntPtr pThis);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_Release")]
        public static extern int XHVEngine_Release(IntPtr pThis);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_EnableProcessingMode")]
        public static extern int XHVEngine_EnableProcessingMode(IntPtr pThis, int processingMode);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetCallbackInterface")]
        public static extern int XHVEngine_SetCallbackInterface(IntPtr pThis, IntPtr pITitleXHV);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_GetCallbackInterface")]
        public static extern int XHVEngine_GetCallbackInterface(IntPtr pThis, IntPtr ppITitleXHV);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_DoWork")]
        public static extern int XHVEngine_DoWork(IntPtr pThis);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_RegisterLocalTalker")]
        public static extern int XHVEngine_RegisterLocalTalker(IntPtr pThis, int dwLocalPort);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_UnregisterLocalTalker")]
        public static extern int XHVEngine_UnregisterLocalTalker(IntPtr pThis, int dwLocalPort);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetProcessingMode")]
        public static extern int XHVEngine_SetProcessingMode(IntPtr pThis, int dwLocalPort, int processingMode);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_GetProcessingMode")]
        public static extern int XHVEngine_GetProcessingMode(IntPtr pThis, int dwLocalPort, IntPtr pProcessingMode);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetVoiceMask")]
        public static extern int XHVEngine_SetVoiceMask(IntPtr pThis, int dwLocalPort, IntPtr pVoiceMask);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_GetLocalTalkerStatus")]
        public static extern int XHVEngine_GetLocalTalkerStatus(IntPtr pThis, int dwLocalPort, IntPtr pLocalTalkerStatus);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_RegisterRemoteTalker")]
        public static extern int XHVEngine_RegisterRemoteTalker(IntPtr pThis, Xuid xuidRemoteTalker);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_UnregisterRemoteTalker")]
        public static extern int XHVEngine_UnregisterRemoteTalker(IntPtr pThis, Xuid xuidRemoteTalker);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_GetRemoteTalkers")]
        public static extern int XHVEngine_GetRemoteTalkers(IntPtr pThis, IntPtr pdwRemoteTalkersCount, IntPtr pxuidRemoteTalkers);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SubmitIncomingVoicePacket")]
        public static extern int XHVEngine_SubmitIncomingVoicePacket(IntPtr pThis, Xuid xuidRemoteTalker, IntPtr pvData, int dwSize);

        public static bool XHVEngine_IsTalking(IntPtr pThis, Xuid xuidRemoteTalker)
        {
            return Native.XHVEngine_IsTalking(pThis, xuidRemoteTalker) != 0;
        }

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetMixBinMapping")]
        public static extern int XHVEngine_SetMixBinMapping(IntPtr pThis, Xuid xuidRemoteTalker, int dwLocalPort, IntPtr pMixBins);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetMixBinVolumes")]
        public static extern int XHVEngine_SetMixBinVolumes(IntPtr pThis, Xuid xuidRemoteTalker, IntPtr pMixBins);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetPlaybackPriority")]
        public static extern int XHVEngine_SetPlaybackPriority(IntPtr pThis, Xuid xuidRemoteTalker, int dwLocalPort, int playbackPriority);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SetMaxPlaybackStreamsCount")]
        public static extern int XHVEngine_SetMaxPlaybackStreamsCount(IntPtr pThis, int dwStreamsCount);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_RegisterSpeechRecognitionBank")]
        public static extern int XHVEngine_RegisterSpeechRecognitionBank(IntPtr pThis, IntPtr pvSRBank);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_SelectVocabulary")]
        public static extern int XHVEngine_SelectVocabulary(IntPtr pThis, int dwLocalPort, int dwVocabsCount, IntPtr pVocabSelections);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_VoiceMailRecord")]
        public static extern int XHVEngine_VoiceMailRecord(IntPtr pThis, int dwLocalPort, int dwMaxTimeMs, int dwOutputBufferSize, IntPtr pbOutputBuffer);

        public static int XHVEngine_VoiceMailPlay(IntPtr pThis, int dwLocalPort, int dwInputBufferSize, IntPtr pbInputBuffer, bool bOutputToSpeakers)
        {
            return Native.XHVEngine_VoiceMailPlay(pThis, dwLocalPort, dwInputBufferSize, pbInputBuffer, bOutputToSpeakers ? 1 : 0);
        }

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_VoiceMailStop")]
        public static extern int XHVEngine_VoiceMailStop(IntPtr pThis, int dwLocalPort);

        [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngineCreate")]
        public static extern int XHVEngineCreate(IntPtr pParams, IntPtr ppEngine);

        static class Native
        {
            [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_IsTalking")]
            public static extern int XHVEngine_IsTalking(IntPtr pThis, Xuid xuidRemoteTalker);

            [DllImport("xvoice", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xvoice_XHVEngine_VoiceMailPlay")]
            public static extern int XHVEngine_VoiceMailPlay(IntPtr pThis, int dwLocalPort, int dwInputBufferSize, IntPtr pbInputBuffer, int bOutputToSpeakers);

        }
    }
}
