// Generated by scripts/gen-xgmath.py. Degree and radian conversion and the
// short vector, matrix, quaternion, plane, and color routines are C#. The
// exported XGraphics functions call libxgraphics.
using System;
using System.Runtime.InteropServices;

namespace Rxdk
{
    public static class MathHelper
    {
        public const float Pi = 3.141592654f;
        public const float OneOverPi = 0.318309886f;

        public static float ToRadian(float degree)
        {
            return degree * (Pi / 180.0f);
        }

        public static float ToDegree(float radian)
        {
            return radian * (180.0f / Pi);
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Vector2
    {
        public float X, Y;
        public Vector2(float x, float y) { X = x; Y = y; }
        public static float LengthSq(Vector2 v) { return v.X * v.X + v.Y * v.Y; }
        public static float Length(Vector2 v) { return (float)Math.Sqrt(LengthSq(v)); }
        public static float Dot(Vector2 a, Vector2 b) { return a.X * b.X + a.Y * b.Y; }
        public static Vector2 Add(Vector2 a, Vector2 b) { return new Vector2(a.X + b.X, a.Y + b.Y); }
        public static Vector2 Subtract(Vector2 a, Vector2 b) { return new Vector2(a.X - b.X, a.Y - b.Y); }
        public static Vector2 Scale(Vector2 v, float s) { return new Vector2(v.X * s, v.Y * s); }
        public static Vector2 Lerp(Vector2 a, Vector2 b, float s) { return new Vector2((a.X + s * (b.X - a.X)), (a.Y + s * (b.Y - a.Y))); }
        public static Vector2 Minimize(Vector2 a, Vector2 b) { return new Vector2(a.X < b.X ? a.X : b.X, a.Y < b.Y ? a.Y : b.Y); }
        public static Vector2 Maximize(Vector2 a, Vector2 b) { return new Vector2(a.X > b.X ? a.X : b.X, a.Y > b.Y ? a.Y : b.Y); }
        public static float Ccw(Vector2 a, Vector2 b) { return a.X * b.Y - a.Y * b.X; }
        public static Vector2 Normalize(Vector2 v)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2Normalize(ref o, ref v);
            return o;
        }
        public static Vector2 Hermite(Vector2 v1, Vector2 t1, Vector2 v2, Vector2 t2, float s)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2Hermite(ref o, ref v1, ref t1, ref v2, ref t2, s);
            return o;
        }
        public static Vector2 CatmullRom(Vector2 v0, Vector2 v1, Vector2 v2, Vector2 v3, float s)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2CatmullRom(ref o, ref v0, ref v1, ref v2, ref v3, s);
            return o;
        }
        public static Vector2 BaryCentric(Vector2 v1, Vector2 v2, Vector2 v3, float f, float g)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2BaryCentric(ref o, ref v1, ref v2, ref v3, f, g);
            return o;
        }
        public static Vector4 Transform(Vector2 v, Matrix4 m)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec2Transform(ref o, ref v, ref m);
            return o;
        }
        public static Vector2 TransformCoord(Vector2 v, Matrix4 m)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2TransformCoord(ref o, ref v, ref m);
            return o;
        }
        public static Vector2 TransformNormal(Vector2 v, Matrix4 m)
        {
            Vector2 o = new Vector2();
            XgNative.XGVec2TransformNormal(ref o, ref v, ref m);
            return o;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Vector3
    {
        public float X, Y, Z;
        public Vector3(float x, float y, float z) { X = x; Y = y; Z = z; }
        public static float LengthSq(Vector3 v) { return v.X * v.X + v.Y * v.Y + v.Z * v.Z; }
        public static float Length(Vector3 v) { return (float)Math.Sqrt(LengthSq(v)); }
        public static float Dot(Vector3 a, Vector3 b) { return a.X * b.X + a.Y * b.Y + a.Z * b.Z; }
        public static Vector3 Add(Vector3 a, Vector3 b) { return new Vector3(a.X + b.X, a.Y + b.Y, a.Z + b.Z); }
        public static Vector3 Subtract(Vector3 a, Vector3 b) { return new Vector3(a.X - b.X, a.Y - b.Y, a.Z - b.Z); }
        public static Vector3 Scale(Vector3 v, float s) { return new Vector3(v.X * s, v.Y * s, v.Z * s); }
        public static Vector3 Lerp(Vector3 a, Vector3 b, float s) { return new Vector3((a.X + s * (b.X - a.X)), (a.Y + s * (b.Y - a.Y)), (a.Z + s * (b.Z - a.Z))); }
        public static Vector3 Minimize(Vector3 a, Vector3 b) { return new Vector3(a.X < b.X ? a.X : b.X, a.Y < b.Y ? a.Y : b.Y, a.Z < b.Z ? a.Z : b.Z); }
        public static Vector3 Maximize(Vector3 a, Vector3 b) { return new Vector3(a.X > b.X ? a.X : b.X, a.Y > b.Y ? a.Y : b.Y, a.Z > b.Z ? a.Z : b.Z); }
        public static Vector3 Cross(Vector3 a, Vector3 b) { return new Vector3(a.Y * b.Z - a.Z * b.Y, a.Z * b.X - a.X * b.Z, a.X * b.Y - a.Y * b.X); }
        public static Vector3 Normalize(Vector3 v)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3Normalize(ref o, ref v);
            return o;
        }
        public static Vector3 Hermite(Vector3 v1, Vector3 t1, Vector3 v2, Vector3 t2, float s)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3Hermite(ref o, ref v1, ref t1, ref v2, ref t2, s);
            return o;
        }
        public static Vector3 CatmullRom(Vector3 v0, Vector3 v1, Vector3 v2, Vector3 v3, float s)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3CatmullRom(ref o, ref v0, ref v1, ref v2, ref v3, s);
            return o;
        }
        public static Vector3 BaryCentric(Vector3 v1, Vector3 v2, Vector3 v3, float f, float g)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3BaryCentric(ref o, ref v1, ref v2, ref v3, f, g);
            return o;
        }
        public static Vector4 Transform(Vector3 v, Matrix4 m)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec3Transform(ref o, ref v, ref m);
            return o;
        }
        public static Vector3 TransformCoord(Vector3 v, Matrix4 m)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3TransformCoord(ref o, ref v, ref m);
            return o;
        }
        public static Vector3 TransformNormal(Vector3 v, Matrix4 m)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3TransformNormal(ref o, ref v, ref m);
            return o;
        }
        public static Vector3 Project(Vector3 v, Viewport viewport, Matrix4 projection, Matrix4 view, Matrix4 world)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3Project(ref o, ref v, ref viewport, ref projection, ref view, ref world);
            return o;
        }
        public static Vector3 Unproject(Vector3 v, Viewport viewport, Matrix4 projection, Matrix4 view, Matrix4 world)
        {
            Vector3 o = new Vector3();
            XgNative.XGVec3Unproject(ref o, ref v, ref viewport, ref projection, ref view, ref world);
            return o;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Vector4
    {
        public float X, Y, Z, W;
        public Vector4(float x, float y, float z, float w) { X = x; Y = y; Z = z; W = w; }
        public static float LengthSq(Vector4 v) { return v.X * v.X + v.Y * v.Y + v.Z * v.Z + v.W * v.W; }
        public static float Length(Vector4 v) { return (float)Math.Sqrt(LengthSq(v)); }
        public static float Dot(Vector4 a, Vector4 b) { return a.X * b.X + a.Y * b.Y + a.Z * b.Z + a.W * b.W; }
        public static Vector4 Add(Vector4 a, Vector4 b) { return new Vector4(a.X + b.X, a.Y + b.Y, a.Z + b.Z, a.W + b.W); }
        public static Vector4 Subtract(Vector4 a, Vector4 b) { return new Vector4(a.X - b.X, a.Y - b.Y, a.Z - b.Z, a.W - b.W); }
        public static Vector4 Scale(Vector4 v, float s) { return new Vector4(v.X * s, v.Y * s, v.Z * s, v.W * s); }
        public static Vector4 Lerp(Vector4 a, Vector4 b, float s) { return new Vector4((a.X + s * (b.X - a.X)), (a.Y + s * (b.Y - a.Y)), (a.Z + s * (b.Z - a.Z)), (a.W + s * (b.W - a.W))); }
        public static Vector4 Minimize(Vector4 a, Vector4 b) { return new Vector4(a.X < b.X ? a.X : b.X, a.Y < b.Y ? a.Y : b.Y, a.Z < b.Z ? a.Z : b.Z, a.W < b.W ? a.W : b.W); }
        public static Vector4 Maximize(Vector4 a, Vector4 b) { return new Vector4(a.X > b.X ? a.X : b.X, a.Y > b.Y ? a.Y : b.Y, a.Z > b.Z ? a.Z : b.Z, a.W > b.W ? a.W : b.W); }
        public static Vector4 Cross(Vector4 v1, Vector4 v2, Vector4 v3)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4Cross(ref o, ref v1, ref v2, ref v3);
            return o;
        }
        public static Vector4 Normalize(Vector4 v)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4Normalize(ref o, ref v);
            return o;
        }
        public static Vector4 Hermite(Vector4 v1, Vector4 t1, Vector4 v2, Vector4 t2, float s)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4Hermite(ref o, ref v1, ref t1, ref v2, ref t2, s);
            return o;
        }
        public static Vector4 CatmullRom(Vector4 v0, Vector4 v1, Vector4 v2, Vector4 v3, float s)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4CatmullRom(ref o, ref v0, ref v1, ref v2, ref v3, s);
            return o;
        }
        public static Vector4 BaryCentric(Vector4 v1, Vector4 v2, Vector4 v3, float f, float g)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4BaryCentric(ref o, ref v1, ref v2, ref v3, f, g);
            return o;
        }
        public static Vector4 Transform(Vector4 v, Matrix4 m)
        {
            Vector4 o = new Vector4();
            XgNative.XGVec4Transform(ref o, ref v, ref m);
            return o;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Quaternion
    {
        public float X, Y, Z, W;
        public Quaternion(float x, float y, float z, float w) { X = x; Y = y; Z = z; W = w; }
        public static float LengthSq(Quaternion v) { return v.X * v.X + v.Y * v.Y + v.Z * v.Z + v.W * v.W; }
        public static float Length(Quaternion v) { return (float)Math.Sqrt(LengthSq(v)); }
        public static float Dot(Quaternion a, Quaternion b) { return a.X * b.X + a.Y * b.Y + a.Z * b.Z + a.W * b.W; }
        public static Quaternion Identity() { return new Quaternion(0f, 0f, 0f, 1f); }
        public static bool IsIdentity(Quaternion q) { return q.X == 0f && q.Y == 0f && q.Z == 0f && q.W == 1f; }
        public static Quaternion Conjugate(Quaternion q) { return new Quaternion(-q.X, -q.Y, -q.Z, q.W); }
        public static void ToAxisAngle(Quaternion q, out Vector3 axis, out float angle)
        {
            XgNative.XGQuaternionToAxisAngle(ref q, out axis, out angle);
        }
        public static Quaternion RotationMatrix(Matrix4 m)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionRotationMatrix(ref o, ref m);
            return o;
        }
        public static Quaternion RotationAxis(Vector3 v, float angle)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionRotationAxis(ref o, ref v, angle);
            return o;
        }
        public static Quaternion RotationYawPitchRoll(float yaw, float pitch, float roll)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionRotationYawPitchRoll(ref o, yaw, pitch, roll);
            return o;
        }
        public static Quaternion Multiply(Quaternion q1, Quaternion q2)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionMultiply(ref o, ref q1, ref q2);
            return o;
        }
        public static Quaternion Normalize(Quaternion q)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionNormalize(ref o, ref q);
            return o;
        }
        public static Quaternion Inverse(Quaternion q)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionInverse(ref o, ref q);
            return o;
        }
        public static Quaternion Ln(Quaternion q)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionLn(ref o, ref q);
            return o;
        }
        public static Quaternion Exp(Quaternion q)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionExp(ref o, ref q);
            return o;
        }
        public static Quaternion Slerp(Quaternion q1, Quaternion q2, float t)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionSlerp(ref o, ref q1, ref q2, t);
            return o;
        }
        public static Quaternion Squad(Quaternion q1, Quaternion q2, Quaternion q3, Quaternion q4, float t)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionSquad(ref o, ref q1, ref q2, ref q3, ref q4, t);
            return o;
        }
        public static Quaternion BaryCentric(Quaternion q1, Quaternion q2, Quaternion q3, float f, float g)
        {
            Quaternion o = new Quaternion();
            XgNative.XGQuaternionBaryCentric(ref o, ref q1, ref q2, ref q3, f, g);
            return o;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Plane
    {
        public float A, B, C, D;
        public Plane(float a, float b, float c, float d) { A = a; B = b; C = c; D = d; }
        public static float Dot(Plane p, Vector4 v) { return p.A * v.X + p.B * v.Y + p.C * v.Z + p.D * v.W; }
        public static float DotCoord(Plane p, Vector3 v) { return p.A * v.X + p.B * v.Y + p.C * v.Z + p.D; }
        public static float DotNormal(Plane p, Vector3 v) { return p.A * v.X + p.B * v.Y + p.C * v.Z; }
        public static Plane Normalize(Plane p)
        {
            Plane o = new Plane();
            XgNative.XGPlaneNormalize(ref o, ref p);
            return o;
        }
        public static Vector3 IntersectLine(Plane p, Vector3 v1, Vector3 v2)
        {
            Vector3 o = new Vector3();
            XgNative.XGPlaneIntersectLine(ref o, ref p, ref v1, ref v2);
            return o;
        }
        public static Plane FromPointNormal(Vector3 point, Vector3 normal)
        {
            Plane o = new Plane();
            XgNative.XGPlaneFromPointNormal(ref o, ref point, ref normal);
            return o;
        }
        public static Plane FromPoints(Vector3 v1, Vector3 v2, Vector3 v3)
        {
            Plane o = new Plane();
            XgNative.XGPlaneFromPoints(ref o, ref v1, ref v2, ref v3);
            return o;
        }
        public static Plane Transform(Plane p, Matrix4 m)
        {
            Plane o = new Plane();
            XgNative.XGPlaneTransform(ref o, ref p, ref m);
            return o;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Color4
    {
        public float R, G, B, A;
        public Color4(float r, float g, float b, float a) { R = r; G = g; B = b; A = a; }
        public static Color4 Negative(Color4 c) { return new Color4(1f - c.R, 1f - c.G, 1f - c.B, c.A); }
        public static Color4 Add(Color4 a, Color4 b) { return new Color4(a.R + b.R, a.G + b.G, a.B + b.B, a.A + b.A); }
        public static Color4 Subtract(Color4 a, Color4 b) { return new Color4(a.R - b.R, a.G - b.G, a.B - b.B, a.A - b.A); }
        public static Color4 Scale(Color4 c, float s) { return new Color4(c.R * s, c.G * s, c.B * s, c.A * s); }
        public static Color4 Modulate(Color4 a, Color4 b) { return new Color4(a.R * b.R, a.G * b.G, a.B * b.B, a.A * b.A); }
        public static Color4 Lerp(Color4 a, Color4 b, float s) { return new Color4(a.R + s * (b.R - a.R), a.G + s * (b.G - a.G), a.B + s * (b.B - a.B), a.A + s * (b.A - a.A)); }
        public static Color4 AdjustSaturation(Color4 c, float s)
        {
            Color4 o = new Color4();
            XgNative.XGColorAdjustSaturation(ref o, ref c, s);
            return o;
        }
        public static Color4 AdjustContrast(Color4 c, float c2)
        {
            Color4 o = new Color4();
            XgNative.XGColorAdjustContrast(ref o, ref c, c2);
            return o;
        }
    }

    public static class Matrix
    {
        public static Matrix4 Identity()
        {
            Matrix4 m = new Matrix4();
            m.M11 = 1f; m.M22 = 1f; m.M33 = 1f; m.M44 = 1f;
            return m;
        }
        public static bool IsIdentity(Matrix4 m)
        {
            return m.M11 == 1f && m.M12 == 0f && m.M13 == 0f && m.M14 == 0f &&
                m.M21 == 0f && m.M22 == 1f && m.M23 == 0f && m.M24 == 0f &&
                m.M31 == 0f && m.M32 == 0f && m.M33 == 1f && m.M34 == 0f &&
                m.M41 == 0f && m.M42 == 0f && m.M43 == 0f && m.M44 == 1f;
        }
        public static float Determinant(Matrix4 m)
        {
            return XgNative.XGMatrixfDeterminant(ref m);
        }
        public static Matrix4 Multiply(Matrix4 m1, Matrix4 m2)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixMultiply(ref o, ref m1, ref m2);
            return o;
        }
        public static Matrix4 Transpose(Matrix4 m)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixTranspose(ref o, ref m);
            return o;
        }
        public static Matrix4 Inverse(out float determinant, Matrix4 m)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixInverse(ref o, out determinant, ref m);
            return o;
        }
        public static Matrix4 Scaling(float sx, float sy, float sz)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixScaling(ref o, sx, sy, sz);
            return o;
        }
        public static Matrix4 Translation(float x, float y, float z)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixTranslation(ref o, x, y, z);
            return o;
        }
        public static Matrix4 RotationX(float angle)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationX(ref o, angle);
            return o;
        }
        public static Matrix4 RotationY(float angle)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationY(ref o, angle);
            return o;
        }
        public static Matrix4 RotationZ(float angle)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationZ(ref o, angle);
            return o;
        }
        public static Matrix4 RotationAxis(Vector3 v, float angle)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationAxis(ref o, ref v, angle);
            return o;
        }
        public static Matrix4 RotationQuaternion(Quaternion q)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationQuaternion(ref o, ref q);
            return o;
        }
        public static Matrix4 RotationYawPitchRoll(float yaw, float pitch, float roll)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixRotationYawPitchRoll(ref o, yaw, pitch, roll);
            return o;
        }
        public static Matrix4 Transformation(Vector3 scalingCenter, Quaternion scalingRotation, Vector3 scaling, Vector3 rotationCenter, Quaternion rotation, Vector3 translation)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixTransformation(ref o, ref scalingCenter, ref scalingRotation, ref scaling, ref rotationCenter, ref rotation, ref translation);
            return o;
        }
        public static Matrix4 AffineTransformation(float scaling, Vector3 rotationCenter, Quaternion rotation, Vector3 translation)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixAffineTransformation(ref o, scaling, ref rotationCenter, ref rotation, ref translation);
            return o;
        }
        public static Matrix4 LookAtRH(Vector3 eye, Vector3 at, Vector3 up)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixLookAtRH(ref o, ref eye, ref at, ref up);
            return o;
        }
        public static Matrix4 LookAtLH(Vector3 eye, Vector3 at, Vector3 up)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixLookAtLH(ref o, ref eye, ref at, ref up);
            return o;
        }
        public static Matrix4 PerspectiveRH(float w, float h, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveRH(ref o, w, h, zn, zf);
            return o;
        }
        public static Matrix4 PerspectiveLH(float w, float h, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveLH(ref o, w, h, zn, zf);
            return o;
        }
        public static Matrix4 PerspectiveFovRH(float fovy, float aspect, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveFovRH(ref o, fovy, aspect, zn, zf);
            return o;
        }
        public static Matrix4 PerspectiveFovLH(float fovy, float aspect, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveFovLH(ref o, fovy, aspect, zn, zf);
            return o;
        }
        public static Matrix4 PerspectiveOffCenterRH(float l, float r, float b, float t, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveOffCenterRH(ref o, l, r, b, t, zn, zf);
            return o;
        }
        public static Matrix4 PerspectiveOffCenterLH(float l, float r, float b, float t, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixPerspectiveOffCenterLH(ref o, l, r, b, t, zn, zf);
            return o;
        }
        public static Matrix4 OrthoRH(float w, float h, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixOrthoRH(ref o, w, h, zn, zf);
            return o;
        }
        public static Matrix4 OrthoLH(float w, float h, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixOrthoLH(ref o, w, h, zn, zf);
            return o;
        }
        public static Matrix4 OrthoOffCenterRH(float l, float r, float b, float t, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixOrthoOffCenterRH(ref o, l, r, b, t, zn, zf);
            return o;
        }
        public static Matrix4 OrthoOffCenterLH(float l, float r, float b, float t, float zn, float zf)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixOrthoOffCenterLH(ref o, l, r, b, t, zn, zf);
            return o;
        }
        public static Matrix4 Shadow(Vector4 light, Plane plane)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixShadow(ref o, ref light, ref plane);
            return o;
        }
        public static Matrix4 Reflect(Plane plane)
        {
            Matrix4 o = new Matrix4();
            XgNative.XGMatrixReflect(ref o, ref plane);
            return o;
        }
    }

    static class XgNative
    {
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2Normalize")]
            public static extern void XGVec2Normalize(ref Vector2 o, ref Vector2 v);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2Hermite")]
            public static extern void XGVec2Hermite(ref Vector2 o, ref Vector2 v1, ref Vector2 t1, ref Vector2 v2, ref Vector2 t2, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2CatmullRom")]
            public static extern void XGVec2CatmullRom(ref Vector2 o, ref Vector2 v0, ref Vector2 v1, ref Vector2 v2, ref Vector2 v3, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2BaryCentric")]
            public static extern void XGVec2BaryCentric(ref Vector2 o, ref Vector2 v1, ref Vector2 v2, ref Vector2 v3, float f, float g);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2Transform")]
            public static extern void XGVec2Transform(ref Vector4 o, ref Vector2 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2TransformCoord")]
            public static extern void XGVec2TransformCoord(ref Vector2 o, ref Vector2 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec2TransformNormal")]
            public static extern void XGVec2TransformNormal(ref Vector2 o, ref Vector2 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3Normalize")]
            public static extern void XGVec3Normalize(ref Vector3 o, ref Vector3 v);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3Hermite")]
            public static extern void XGVec3Hermite(ref Vector3 o, ref Vector3 v1, ref Vector3 t1, ref Vector3 v2, ref Vector3 t2, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3CatmullRom")]
            public static extern void XGVec3CatmullRom(ref Vector3 o, ref Vector3 v0, ref Vector3 v1, ref Vector3 v2, ref Vector3 v3, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3BaryCentric")]
            public static extern void XGVec3BaryCentric(ref Vector3 o, ref Vector3 v1, ref Vector3 v2, ref Vector3 v3, float f, float g);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3Transform")]
            public static extern void XGVec3Transform(ref Vector4 o, ref Vector3 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3TransformCoord")]
            public static extern void XGVec3TransformCoord(ref Vector3 o, ref Vector3 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3TransformNormal")]
            public static extern void XGVec3TransformNormal(ref Vector3 o, ref Vector3 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3Project")]
            public static extern void XGVec3Project(ref Vector3 o, ref Vector3 v, ref Viewport viewport, ref Matrix4 projection, ref Matrix4 view, ref Matrix4 world);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec3Unproject")]
            public static extern void XGVec3Unproject(ref Vector3 o, ref Vector3 v, ref Viewport viewport, ref Matrix4 projection, ref Matrix4 view, ref Matrix4 world);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4Cross")]
            public static extern void XGVec4Cross(ref Vector4 o, ref Vector4 v1, ref Vector4 v2, ref Vector4 v3);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4Normalize")]
            public static extern void XGVec4Normalize(ref Vector4 o, ref Vector4 v);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4Hermite")]
            public static extern void XGVec4Hermite(ref Vector4 o, ref Vector4 v1, ref Vector4 t1, ref Vector4 v2, ref Vector4 t2, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4CatmullRom")]
            public static extern void XGVec4CatmullRom(ref Vector4 o, ref Vector4 v0, ref Vector4 v1, ref Vector4 v2, ref Vector4 v3, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4BaryCentric")]
            public static extern void XGVec4BaryCentric(ref Vector4 o, ref Vector4 v1, ref Vector4 v2, ref Vector4 v3, float f, float g);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGVec4Transform")]
            public static extern void XGVec4Transform(ref Vector4 o, ref Vector4 v, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixfDeterminant")]
            public static extern float XGMatrixfDeterminant(ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixMultiply")]
            public static extern void XGMatrixMultiply(ref Matrix4 o, ref Matrix4 m1, ref Matrix4 m2);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixTranspose")]
            public static extern void XGMatrixTranspose(ref Matrix4 o, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixInverse")]
            public static extern void XGMatrixInverse(ref Matrix4 o, out float determinant, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixScaling")]
            public static extern void XGMatrixScaling(ref Matrix4 o, float sx, float sy, float sz);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixTranslation")]
            public static extern void XGMatrixTranslation(ref Matrix4 o, float x, float y, float z);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationX")]
            public static extern void XGMatrixRotationX(ref Matrix4 o, float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationY")]
            public static extern void XGMatrixRotationY(ref Matrix4 o, float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationZ")]
            public static extern void XGMatrixRotationZ(ref Matrix4 o, float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationAxis")]
            public static extern void XGMatrixRotationAxis(ref Matrix4 o, ref Vector3 v, float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationQuaternion")]
            public static extern void XGMatrixRotationQuaternion(ref Matrix4 o, ref Quaternion q);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixRotationYawPitchRoll")]
            public static extern void XGMatrixRotationYawPitchRoll(ref Matrix4 o, float yaw, float pitch, float roll);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixTransformation")]
            public static extern void XGMatrixTransformation(ref Matrix4 o, ref Vector3 scalingCenter, ref Quaternion scalingRotation, ref Vector3 scaling, ref Vector3 rotationCenter, ref Quaternion rotation, ref Vector3 translation);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixAffineTransformation")]
            public static extern void XGMatrixAffineTransformation(ref Matrix4 o, float scaling, ref Vector3 rotationCenter, ref Quaternion rotation, ref Vector3 translation);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixLookAtRH")]
            public static extern void XGMatrixLookAtRH(ref Matrix4 o, ref Vector3 eye, ref Vector3 at, ref Vector3 up);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixLookAtLH")]
            public static extern void XGMatrixLookAtLH(ref Matrix4 o, ref Vector3 eye, ref Vector3 at, ref Vector3 up);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveRH")]
            public static extern void XGMatrixPerspectiveRH(ref Matrix4 o, float w, float h, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveLH")]
            public static extern void XGMatrixPerspectiveLH(ref Matrix4 o, float w, float h, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveFovRH")]
            public static extern void XGMatrixPerspectiveFovRH(ref Matrix4 o, float fovy, float aspect, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveFovLH")]
            public static extern void XGMatrixPerspectiveFovLH(ref Matrix4 o, float fovy, float aspect, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveOffCenterRH")]
            public static extern void XGMatrixPerspectiveOffCenterRH(ref Matrix4 o, float l, float r, float b, float t, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixPerspectiveOffCenterLH")]
            public static extern void XGMatrixPerspectiveOffCenterLH(ref Matrix4 o, float l, float r, float b, float t, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixOrthoRH")]
            public static extern void XGMatrixOrthoRH(ref Matrix4 o, float w, float h, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixOrthoLH")]
            public static extern void XGMatrixOrthoLH(ref Matrix4 o, float w, float h, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixOrthoOffCenterRH")]
            public static extern void XGMatrixOrthoOffCenterRH(ref Matrix4 o, float l, float r, float b, float t, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixOrthoOffCenterLH")]
            public static extern void XGMatrixOrthoOffCenterLH(ref Matrix4 o, float l, float r, float b, float t, float zn, float zf);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixShadow")]
            public static extern void XGMatrixShadow(ref Matrix4 o, ref Vector4 light, ref Plane plane);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGMatrixReflect")]
            public static extern void XGMatrixReflect(ref Matrix4 o, ref Plane plane);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionToAxisAngle")]
            public static extern void XGQuaternionToAxisAngle(ref Quaternion q, out Vector3 axis, out float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionRotationMatrix")]
            public static extern void XGQuaternionRotationMatrix(ref Quaternion o, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionRotationAxis")]
            public static extern void XGQuaternionRotationAxis(ref Quaternion o, ref Vector3 v, float angle);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionRotationYawPitchRoll")]
            public static extern void XGQuaternionRotationYawPitchRoll(ref Quaternion o, float yaw, float pitch, float roll);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionMultiply")]
            public static extern void XGQuaternionMultiply(ref Quaternion o, ref Quaternion q1, ref Quaternion q2);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionNormalize")]
            public static extern void XGQuaternionNormalize(ref Quaternion o, ref Quaternion q);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionInverse")]
            public static extern void XGQuaternionInverse(ref Quaternion o, ref Quaternion q);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionLn")]
            public static extern void XGQuaternionLn(ref Quaternion o, ref Quaternion q);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionExp")]
            public static extern void XGQuaternionExp(ref Quaternion o, ref Quaternion q);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionSlerp")]
            public static extern void XGQuaternionSlerp(ref Quaternion o, ref Quaternion q1, ref Quaternion q2, float t);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionSquad")]
            public static extern void XGQuaternionSquad(ref Quaternion o, ref Quaternion q1, ref Quaternion q2, ref Quaternion q3, ref Quaternion q4, float t);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGQuaternionBaryCentric")]
            public static extern void XGQuaternionBaryCentric(ref Quaternion o, ref Quaternion q1, ref Quaternion q2, ref Quaternion q3, float f, float g);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGPlaneNormalize")]
            public static extern void XGPlaneNormalize(ref Plane o, ref Plane p);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGPlaneIntersectLine")]
            public static extern void XGPlaneIntersectLine(ref Vector3 o, ref Plane p, ref Vector3 v1, ref Vector3 v2);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGPlaneFromPointNormal")]
            public static extern void XGPlaneFromPointNormal(ref Plane o, ref Vector3 point, ref Vector3 normal);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGPlaneFromPoints")]
            public static extern void XGPlaneFromPoints(ref Plane o, ref Vector3 v1, ref Vector3 v2, ref Vector3 v3);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGPlaneTransform")]
            public static extern void XGPlaneTransform(ref Plane o, ref Plane p, ref Matrix4 m);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGColorAdjustSaturation")]
            public static extern void XGColorAdjustSaturation(ref Color4 o, ref Color4 c, float s);
            [DllImport("xgraphics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xm_XGColorAdjustContrast")]
            public static extern void XGColorAdjustContrast(ref Color4 o, ref Color4 c, float c2);
    }
}
