// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    public static class Xact
    {
        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_XACTEngineCreate")]
        public static extern int XACTEngineCreate(IntPtr pParams, IntPtr ppEngine);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_XACTEngineDoWork")]
        public static extern void XACTEngineDoWork();

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_AddRef")]
        public static extern int IXACTEngine_AddRef(IntPtr pEngine);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_Release")]
        public static extern int IXACTEngine_Release(IntPtr pEngine);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_DownloadEffectsImage")]
        public static extern int IXACTEngine_DownloadEffectsImage(IntPtr pEngine, IntPtr pvData, int dwSize, IntPtr pEffectLoc, IntPtr ppImageDesc);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_CreateSoundSource")]
        public static extern int IXACTEngine_CreateSoundSource(IntPtr pEngine, int dwFlags, IntPtr ppSoundSource);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_CreateSoundBank")]
        public static extern int IXACTEngine_CreateSoundBank(IntPtr pEngine, IntPtr pvData, int dwSize, IntPtr ppSoundBank);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_RegisterWaveBank")]
        public static extern int IXACTEngine_RegisterWaveBank(IntPtr pEngine, IntPtr pvData, int dwSize, IntPtr ppWaveBank);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_RegisterStreamedWaveBank")]
        public static extern int IXACTEngine_RegisterStreamedWaveBank(IntPtr pEngine, IntPtr pParams, IntPtr ppWaveBank);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_UnRegisterWaveBank")]
        public static extern int IXACTEngine_UnRegisterWaveBank(IntPtr pEngine, IntPtr pWaveBank);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetMasterVolume")]
        public static extern int IXACTEngine_SetMasterVolume(IntPtr pEngine, int wCategory, int lVolume);

        public static int IXACTEngine_GlobalPause(IntPtr pEngine, int wCategory, bool fPause)
        {
            return Native.IXACTEngine_GlobalPause(pEngine, wCategory, fPause ? 1 : 0);
        }

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetParameterControl")]
        public static extern int IXACTEngine_SetParameterControl(IntPtr pEngine, IntPtr pParams);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetI3dl2Listener")]
        public static extern int IXACTEngine_SetI3dl2Listener(IntPtr pEngine, IntPtr pds3dl, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetListenerOrientation")]
        public static extern int IXACTEngine_SetListenerOrientation(IntPtr pEngine, float xFront, float yFront, float zFront, float xTop, float yTop, float zTop, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetListenerPosition")]
        public static extern int IXACTEngine_SetListenerPosition(IntPtr pEngine, float x, float y, float z, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetListenerVelocity")]
        public static extern int IXACTEngine_SetListenerVelocity(IntPtr pEngine, float x, float y, float z, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_CommitDeferredSettings")]
        public static extern int IXACTEngine_CommitDeferredSettings(IntPtr pEngine);

        public static int IXACTEngine_EnableHeadphones(IntPtr pEngine, bool fEnabled)
        {
            return Native.IXACTEngine_EnableHeadphones(pEngine, fEnabled ? 1 : 0);
        }

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_RegisterNotification")]
        public static extern int IXACTEngine_RegisterNotification(IntPtr pEngine, IntPtr pNotificationDesc);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_UnRegisterNotification")]
        public static extern int IXACTEngine_UnRegisterNotification(IntPtr pEngine, IntPtr pNotificationDesc);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_GetNotification")]
        public static extern int IXACTEngine_GetNotification(IntPtr pEngine, IntPtr pNotificationDesc, IntPtr pNotification);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_FlushNotification")]
        public static extern int IXACTEngine_FlushNotification(IntPtr pEngine, IntPtr pNotificationDesc);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_SetVariable")]
        public static extern int IXACTEngine_SetVariable(IntPtr pEngine, int dwVariable, int wValue, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_GetVariable")]
        public static extern int IXACTEngine_GetVariable(IntPtr pEngine, int dwVariable, IntPtr pwValue);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_GetRealtimeData")]
        public static extern int IXACTEngine_GetRealtimeData(IntPtr pEngine, IntPtr pData);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_AddRef")]
        public static extern int IXACTSoundSource_AddRef(IntPtr pSoundSource);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_Release")]
        public static extern int IXACTSoundSource_Release(IntPtr pSoundSource);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetPosition")]
        public static extern int IXACTSoundSource_SetPosition(IntPtr pSoundSource, float x, float y, float z, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetConeOrientation")]
        public static extern int IXACTSoundSource_SetConeOrientation(IntPtr pSoundSource, float x, float y, float z, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetI3DL2Source")]
        public static extern int IXACTSoundSource_SetI3DL2Source(IntPtr pSoundSource, IntPtr pds3db, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetVelocity")]
        public static extern int IXACTSoundSource_SetVelocity(IntPtr pSoundSource, float x, float y, float z, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetPitch")]
        public static extern int IXACTSoundSource_SetPitch(IntPtr pSoundSource, int lPitch);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetFilter")]
        public static extern int IXACTSoundSource_SetFilter(IntPtr pSoundSource, IntPtr pFilterDesc);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetMixBins")]
        public static extern int IXACTSoundSource_SetMixBins(IntPtr pSoundSource, IntPtr pMixBins);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetMixBinVolumes")]
        public static extern int IXACTSoundSource_SetMixBinVolumes(IntPtr pSoundSource, IntPtr pMixBins);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_SetMode")]
        public static extern int IXACTSoundSource_SetMode(IntPtr pSoundSource, int dwMode, int dwApply);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_GetStatus")]
        public static extern int IXACTSoundSource_GetStatus(IntPtr pSoundSource, IntPtr pdwStatus);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_GetProperties")]
        public static extern int IXACTSoundSource_GetProperties(IntPtr pSoundSource, IntPtr pProperties);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundSource_StopSoundCues")]
        public static extern int IXACTSoundSource_StopSoundCues(IntPtr pSoundSource);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_AddRef")]
        public static extern int IXACTSoundBank_AddRef(IntPtr pBank);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_Release")]
        public static extern int IXACTSoundBank_Release(IntPtr pBank);

        public static unsafe int IXACTSoundBank_GetSoundCueIndexFromFriendlyName(IntPtr pBank, string pFriendlyName, IntPtr pdwSoundCueIndex)
        {
            byte[] pFriendlyNameBytes = pFriendlyName == null ? null : ToAnsi(pFriendlyName);
            fixed (byte* pFriendlyNamePtr = pFriendlyNameBytes)
                return Native.IXACTSoundBank_GetSoundCueIndexFromFriendlyName(pBank, (pFriendlyNameBytes == null) ? IntPtr.Zero : (IntPtr)pFriendlyNamePtr, pdwSoundCueIndex);
        }

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_PrepareEx")]
        public static extern int IXACTSoundBank_PrepareEx(IntPtr pBank, IntPtr pPrepareData, IntPtr ppSoundCue);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_PlayEx")]
        public static extern int IXACTSoundBank_PlayEx(IntPtr pBank, IntPtr pPrepareData, IntPtr ppSoundCue);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_Stop")]
        public static extern int IXACTSoundBank_Stop(IntPtr pBank, int dwSoundCueIndex, int dwFlags, IntPtr pSoundCue);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_CreateWmaPlayList")]
        public static extern int IXACTSoundBank_CreateWmaPlayList(IntPtr pBank, int dwSoundCueIndex, int dwPlaybackFlags, IntPtr ppWmaPlayList);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_SelectVariation")]
        public static extern int IXACTSoundBank_SelectVariation(IntPtr pBank, int dwSoundCueIndex, IntPtr pVariation);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_GetSoundCueProperties")]
        public static extern int IXACTSoundBank_GetSoundCueProperties(IntPtr pBank, int dwSoundCueIndex, IntPtr pSoundCueProperties);

        public static int IXACTSoundBank_PauseSoundCue(IntPtr pBank, IntPtr pSoundCue, bool fPause)
        {
            return Native.IXACTSoundBank_PauseSoundCue(pBank, pSoundCue, fPause ? 1 : 0);
        }

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_AddRef")]
        public static extern int IXACTWmaPlayList_AddRef(IntPtr pPlayList);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_Release")]
        public static extern int IXACTWmaPlayList_Release(IntPtr pPlayList);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_Add")]
        public static extern int IXACTWmaPlayList_Add(IntPtr pPlayList, IntPtr pDesc, IntPtr ppSong);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_Remove")]
        public static extern int IXACTWmaPlayList_Remove(IntPtr pPlayList, IntPtr pSong);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_SetCurrent")]
        public static extern int IXACTWmaPlayList_SetCurrent(IntPtr pPlayList, IntPtr pSong);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_Next")]
        public static extern int IXACTWmaPlayList_Next(IntPtr pPlayList);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_Previous")]
        public static extern int IXACTWmaPlayList_Previous(IntPtr pPlayList);

        public static unsafe int IXACTWmaPlayList_GetCurrentSongInfo(IntPtr pPlayList, IntPtr pdwSongLength, string pszNameBuffer, int dwBufferSize, IntPtr ppSong)
        {
            byte[] pszNameBufferBytes = pszNameBuffer == null ? null : ToWide(pszNameBuffer);
            fixed (byte* pszNameBufferPtr = pszNameBufferBytes)
                return Native.IXACTWmaPlayList_GetCurrentSongInfo(pPlayList, pdwSongLength, (pszNameBufferBytes == null) ? IntPtr.Zero : (IntPtr)pszNameBufferPtr, dwBufferSize, ppSong);
        }

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfoEx")]
        public static extern int IXACTWmaPlayList_GetCurrentSongInfoEx(IntPtr pPlayList, IntPtr pDesc, IntPtr ppSong);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_SetPlaybackBehavior")]
        public static extern int IXACTWmaPlayList_SetPlaybackBehavior(IntPtr pPlayList, int dwFlags);

        [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_GetProperties")]
        public static extern int IXACTWmaPlayList_GetProperties(IntPtr pPlayList, IntPtr pProperties);

        static byte[] ToAnsi(string text)
        {
            return Encoding.ASCII.GetBytes(text + "\0");
        }

        static byte[] ToWide(string text)
        {
            return Encoding.Unicode.GetBytes(text + "\0");
        }

        static class Native
        {
            [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_GlobalPause")]
            public static extern int IXACTEngine_GlobalPause(IntPtr pEngine, int wCategory, int fPause);

            [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTEngine_EnableHeadphones")]
            public static extern int IXACTEngine_EnableHeadphones(IntPtr pEngine, int fEnabled);

            [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_GetSoundCueIndexFromFriendlyName")]
            public static extern int IXACTSoundBank_GetSoundCueIndexFromFriendlyName(IntPtr pBank, IntPtr pFriendlyName, IntPtr pdwSoundCueIndex);

            [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTSoundBank_PauseSoundCue")]
            public static extern int IXACTSoundBank_PauseSoundCue(IntPtr pBank, IntPtr pSoundCue, int fPause);

            [DllImport("xact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfo")]
            public static extern int IXACTWmaPlayList_GetCurrentSongInfo(IntPtr pPlayList, IntPtr pdwSongLength, IntPtr pszNameBuffer, int dwBufferSize, IntPtr ppSong);

        }
    }
}
