// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct Xuid
    {
        public long Id;
        public int Flags;
    }

    public static class Uix
    {
        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_AddRef")]
        public static extern int PluginSupport_AddRef(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_Release")]
        public static extern int PluginSupport_Release(IntPtr pThis);

        public static unsafe int PluginSupport_GetString(IntPtr pThis, int StringResID, string ppString)
        {
            byte[] ppStringBytes = ppString == null ? null : ToWide(ppString);
            fixed (byte* ppStringPtr = ppStringBytes)
                return Native.PluginSupport_GetString(pThis, StringResID, (ppStringBytes == null) ? IntPtr.Zero : (IntPtr)ppStringPtr);
        }

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_GetLayout")]
        public static extern int PluginSupport_GetLayout(IntPtr pThis, int ScreenResID, int ObjectResID, IntPtr ppLayout);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_GetImage")]
        public static extern int PluginSupport_GetImage(IntPtr pThis, int ImageResID, IntPtr ppTexture);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_GetScreenImage")]
        public static extern int PluginSupport_GetScreenImage(IntPtr pThis, int ScreenResID, int ImageResID, IntPtr ppTexture);

        public static unsafe int PluginSupport_GetWordLength(IntPtr pThis, string pString, IntPtr pWordLength)
        {
            byte[] pStringBytes = pString == null ? null : ToWide(pString);
            fixed (byte* pStringPtr = pStringBytes)
                return Native.PluginSupport_GetWordLength(pThis, (pStringBytes == null) ? IntPtr.Zero : (IntPtr)pStringPtr, pWordLength);
        }

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_AddRef")]
        public static extern int LiveFriendsList_AddRef(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_Release")]
        public static extern int LiveFriendsList_Release(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_Refresh")]
        public static extern int LiveFriendsList_Refresh(IntPtr pThis);

        public static bool LiveFriendsList_IsReady(IntPtr pThis)
        {
            return Native.LiveFriendsList_IsReady(pThis) != 0;
        }

        public static bool LiveFriendsList_HasChanged(IntPtr pThis)
        {
            return Native.LiveFriendsList_HasChanged(pThis) != 0;
        }

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_Count")]
        public static extern int LiveFriendsList_Count(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_GetFriendByIndex")]
        public static extern int LiveFriendsList_GetFriendByIndex(IntPtr pThis, int FriendIndex, IntPtr pFriend);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_GetFriendByXUID")]
        public static extern int LiveFriendsList_GetFriendByXUID(IntPtr pThis, Xuid FriendXUID, IntPtr pFriend);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_Remove")]
        public static extern int LiveFriendsList_Remove(IntPtr pThis, IntPtr pFriend);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_Request")]
        public static extern int LiveFriendsList_Request(IntPtr pThis, Xuid UserXUID);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_AddRef")]
        public static extern int LiveEngine_AddRef(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_Release")]
        public static extern int LiveEngine_Release(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_DoWork")]
        public static extern int LiveEngine_DoWork(IntPtr pThis, IntPtr pDoWorkFlags);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_SetUIPlugin")]
        public static extern int LiveEngine_SetUIPlugin(IntPtr pThis, IntPtr pUIPlugin);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_SetAudioPlugin")]
        public static extern int LiveEngine_SetAudioPlugin(IntPtr pThis, IntPtr pAudioPlugin);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_EnableFeature")]
        public static extern int LiveEngine_EnableFeature(IntPtr pThis, int FeatureID);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_StartFeature")]
        public static extern int LiveEngine_StartFeature(IntPtr pThis, int FeatureID, IntPtr pFeatureParams);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_Render")]
        public static extern int LiveEngine_Render(IntPtr pThis, IntPtr pSurface);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_SetInput")]
        public static extern int LiveEngine_SetInput(IntPtr pThis, int Port, IntPtr pInputState);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetFriendsForUser")]
        public static extern int LiveEngine_GetFriendsForUser(IntPtr pThis, int Port, IntPtr ppFriendsList);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_NotificationSetState")]
        public static extern int LiveEngine_NotificationSetState(IntPtr pThis, int Port, int StateFlags, long SessionID, int StateDataSize, IntPtr pStateData);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetNotifications")]
        public static extern int LiveEngine_GetNotifications(IntPtr pThis, int Port, int Purpose, IntPtr pNotifications);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_SetProperty")]
        public static extern int LiveEngine_SetProperty(IntPtr pThis, int Property, int Value);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetProperty")]
        public static extern int LiveEngine_GetProperty(IntPtr pThis, int Property, IntPtr pValue);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetExitInfo")]
        public static extern int LiveEngine_GetExitInfo(IntPtr pThis, IntPtr pExitInfo);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_Reboot")]
        public static extern int LiveEngine_Reboot(IntPtr pThis, int Context);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_LogOff")]
        public static extern int LiveEngine_LogOff(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetFeatureInterface")]
        public static extern int LiveEngine_GetFeatureInterface(IntPtr pThis, int FeatureID, IntPtr pParam, IntPtr ppFeatureInterface);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_GetSelectionInfo")]
        public static extern int LiveEngine_GetSelectionInfo(IntPtr pThis, IntPtr pSelectionInfo);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_EndFeature")]
        public static extern int LiveEngine_EndFeature(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_ClearInput")]
        public static extern int LiveEngine_ClearInput(IntPtr pThis);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveEngine_UseVoiceMail")]
        public static extern int LiveEngine_UseVoiceMail(IntPtr pThis, int VoiceMailEntryPoint);

        public static unsafe int UIXCreateLiveEngine(string pSkinFileName, int LanguageID, IntPtr ppEngine)
        {
            byte[] pSkinFileNameBytes = pSkinFileName == null ? null : ToAnsi(pSkinFileName);
            fixed (byte* pSkinFileNamePtr = pSkinFileNameBytes)
                return Native.UIXCreateLiveEngine((pSkinFileNameBytes == null) ? IntPtr.Zero : (IntPtr)pSkinFileNamePtr, LanguageID, ppEngine);
        }

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_UIXCreateUIPlugin")]
        public static extern int UIXCreateUIPlugin(IntPtr pFont, IntPtr ppUIPlugin);

        [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_UIXCreateAudioPlugin")]
        public static extern int UIXCreateAudioPlugin(IntPtr pXactEngine, IntPtr pXactSoundBank, IntPtr ppAudioPlugin);

        static byte[] ToAnsi(string text)
        {
            return Encoding.ASCII.GetBytes(text + "\0");
        }

        static byte[] ToWide(string text)
        {
            return Encoding.Unicode.GetBytes(text + "\0");
        }

        static class Native
        {
            [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_GetString")]
            public static extern int PluginSupport_GetString(IntPtr pThis, int StringResID, IntPtr ppString);

            [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_PluginSupport_GetWordLength")]
            public static extern int PluginSupport_GetWordLength(IntPtr pThis, IntPtr pString, IntPtr pWordLength);

            [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_IsReady")]
            public static extern int LiveFriendsList_IsReady(IntPtr pThis);

            [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_LiveFriendsList_HasChanged")]
            public static extern int LiveFriendsList_HasChanged(IntPtr pThis);

            [DllImport("uix", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_uix_UIXCreateLiveEngine")]
            public static extern int UIXCreateLiveEngine(IntPtr pSkinFileName, int LanguageID, IntPtr ppEngine);

        }
    }
}
