// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct Xuid
    {
        public long Id;
        public int Flags;
    }

    public static class Online
    {
        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStartup")]
        public static extern int XOnlineStartup(IntPtr pxosp);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCleanup")]
        public static extern int XOnlineCleanup();

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTaskContinue")]
        public static extern int XOnlineTaskContinue(int hTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTaskClose")]
        public static extern int XOnlineTaskClose(int hTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetUsers")]
        public static extern int XOnlineGetUsers(IntPtr pUsers, IntPtr pdwUsers);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineLogon")]
        public static extern int XOnlineLogon(IntPtr pUsers, IntPtr pdwServiceIDs, int dwServices, IntPtr hWorkEvent, IntPtr pHandle);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineLogonTaskGetResults")]
        public static extern int XOnlineLogonTaskGetResults(int hLogonTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineChangeLogonUsers")]
        public static extern int XOnlineChangeLogonUsers(IntPtr pUsers, IntPtr hWorkEvent, IntPtr pHandle);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineChangeLogonUsersTaskGetResults")]
        public static extern int XOnlineChangeLogonUsersTaskGetResults(int hLogonTask, IntPtr phr);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetLogonUsers")]
        public static extern int XOnlineGetLogonUsers();

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetNatType")]
        public static extern int XOnlineGetNatType();

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetServiceInfo")]
        public static extern int XOnlineGetServiceInfo(int dwServiceID, IntPtr pServiceInfo);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineSilentLogon")]
        public static extern int XOnlineSilentLogon(IntPtr pdwServiceIDs, int dwServices, IntPtr hWorkEvent, IntPtr pHandle);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineSaveLogonState")]
        public static extern int XOnlineSaveLogonState(IntPtr pLogonState);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineRetrieveLogonState")]
        public static extern int XOnlineRetrieveLogonState(IntPtr pLogonState, IntPtr pUsers, IntPtr pdwServiceIDs, IntPtr pdwServices);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTitleUpdate")]
        public static extern int XOnlineTitleUpdate(int dwContext);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineSignatureVerify")]
        public static extern int XOnlineSignatureVerify(IntPtr rgSignaturesToVerify, int dwSignaturesToVerify, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineSignatureVerifyGetResults")]
        public static extern int XOnlineSignatureVerifyGetResults(int hTask, IntPtr prgHresults, IntPtr pdwHresults);

        public static unsafe int XOnlineStorageUpload(IntPtr hServerFileReference, string szDirectory, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] szDirectoryBytes = szDirectory == null ? null : ToAnsi(szDirectory);
            fixed (byte* szDirectoryPtr = szDirectoryBytes)
                return Native.XOnlineStorageUpload(hServerFileReference, (szDirectoryBytes == null) ? IntPtr.Zero : (IntPtr)szDirectoryPtr, dwUploadFlags, hWorkEvent, phTask);
        }

        public static unsafe int XOnlineStorageCreateServerPath(int dwFacility, long qwUserID, long qwTeamID, string wszStorageFileName, string wszStorageServerPath, IntPtr pcchStorageServerPath)
        {
            byte[] wszStorageFileNameBytes = wszStorageFileName == null ? null : ToWide(wszStorageFileName);
            byte[] wszStorageServerPathBytes = wszStorageServerPath == null ? null : ToWide(wszStorageServerPath);
            fixed (byte* wszStorageFileNamePtr = wszStorageFileNameBytes)
                fixed (byte* wszStorageServerPathPtr = wszStorageServerPathBytes)
                    return Native.XOnlineStorageCreateServerPath(dwFacility, qwUserID, qwTeamID, (wszStorageFileNameBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageFileNamePtr, (wszStorageServerPathBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageServerPathPtr, pcchStorageServerPath);
        }

        public static unsafe int XOnlineStorageUploadByServerPath(int dwFacility, int dwUserIndex, string wszStorageFileName, long ftServerExpirationDate, string szDirectory, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStorageFileNameBytes = wszStorageFileName == null ? null : ToWide(wszStorageFileName);
            byte[] szDirectoryBytes = szDirectory == null ? null : ToAnsi(szDirectory);
            fixed (byte* wszStorageFileNamePtr = wszStorageFileNameBytes)
                fixed (byte* szDirectoryPtr = szDirectoryBytes)
                    return Native.XOnlineStorageUploadByServerPath(dwFacility, dwUserIndex, (wszStorageFileNameBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageFileNamePtr, ftServerExpirationDate, (szDirectoryBytes == null) ? IntPtr.Zero : (IntPtr)szDirectoryPtr, dwUploadFlags, hWorkEvent, phTask);
        }

        public static unsafe int XOnlineStorageDownload(int dwFacility, int dwUserIndex, string wszStoragePath, string szInstallDirectory, int dwDownloadFlags, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStoragePathBytes = wszStoragePath == null ? null : ToWide(wszStoragePath);
            byte[] szInstallDirectoryBytes = szInstallDirectory == null ? null : ToAnsi(szInstallDirectory);
            fixed (byte* wszStoragePathPtr = wszStoragePathBytes)
                fixed (byte* szInstallDirectoryPtr = szInstallDirectoryBytes)
                    return Native.XOnlineStorageDownload(dwFacility, dwUserIndex, (wszStoragePathBytes == null) ? IntPtr.Zero : (IntPtr)wszStoragePathPtr, (szInstallDirectoryBytes == null) ? IntPtr.Zero : (IntPtr)szInstallDirectoryPtr, dwDownloadFlags, hWorkEvent, phTask);
        }

        public static unsafe int XOnlineStorageUploadFromMemory(int dwFacility, int dwUserIndex, string wszStorageFileName, long ftServerExpirationDate, IntPtr pbDataToUpload, int cbDataToUpload, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStorageFileNameBytes = wszStorageFileName == null ? null : ToWide(wszStorageFileName);
            fixed (byte* wszStorageFileNamePtr = wszStorageFileNameBytes)
                return Native.XOnlineStorageUploadFromMemory(dwFacility, dwUserIndex, (wszStorageFileNameBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageFileNamePtr, ftServerExpirationDate, pbDataToUpload, cbDataToUpload, dwUploadFlags, hWorkEvent, phTask);
        }

        public static unsafe int XOnlineStorageDownloadToMemory(int dwFacility, int dwUserIndex, string wszStoragePath, IntPtr pbReceiveBuffer, int cbReceiveBuffer, int dwDownloadFlags, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStoragePathBytes = wszStoragePath == null ? null : ToWide(wszStoragePath);
            fixed (byte* wszStoragePathPtr = wszStoragePathBytes)
                return Native.XOnlineStorageDownloadToMemory(dwFacility, dwUserIndex, (wszStoragePathBytes == null) ? IntPtr.Zero : (IntPtr)wszStoragePathPtr, pbReceiveBuffer, cbReceiveBuffer, dwDownloadFlags, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageDownloadToMemoryGetResults")]
        public static extern int XOnlineStorageDownloadToMemoryGetResults(int hTask, IntPtr ppbReceivedData, IntPtr pcbReceivedData, IntPtr pcbDataTotal, IntPtr pqwOwnerPuid, IntPtr pftCreationDate);

        public static unsafe int XOnlineStorageDeleteFile(int dwFacility, int dwUserIndex, string wszStorageFileName, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStorageFileNameBytes = wszStorageFileName == null ? null : ToWide(wszStorageFileName);
            fixed (byte* wszStorageFileNamePtr = wszStorageFileNameBytes)
                return Native.XOnlineStorageDeleteFile(dwFacility, dwUserIndex, (wszStorageFileNameBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageFileNamePtr, hWorkEvent, phTask);
        }

        public static unsafe int XOnlineStorageEnumerate(int dwFacility, int dwUserIndex, string wszStorageEnumerationPath, int dwStartingIndex, int cMaxResultsToReturn, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] wszStorageEnumerationPathBytes = wszStorageEnumerationPath == null ? null : ToWide(wszStorageEnumerationPath);
            fixed (byte* wszStorageEnumerationPathPtr = wszStorageEnumerationPathBytes)
                return Native.XOnlineStorageEnumerate(dwFacility, dwUserIndex, (wszStorageEnumerationPathBytes == null) ? IntPtr.Zero : (IntPtr)wszStorageEnumerationPathPtr, dwStartingIndex, cMaxResultsToReturn, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageEnumerateGetResults")]
        public static extern int XOnlineStorageEnumerateGetResults(int hTask, IntPtr pdwTotalResults, IntPtr pdwResultsReturned, IntPtr prgpStorageFileInfo);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageGetProgress")]
        public static extern int XOnlineStorageGetProgress(int hTask, IntPtr pdwPercentDone, IntPtr pqwNumerator, IntPtr pqwDenominator);

        public static unsafe int XOnlineStorageGetInstallLocation(int dwFacility, string wszStoragePath, string szLocation, IntPtr pdwLocationSize)
        {
            byte[] wszStoragePathBytes = wszStoragePath == null ? null : ToWide(wszStoragePath);
            byte[] szLocationBytes = szLocation == null ? null : ToAnsi(szLocation);
            fixed (byte* wszStoragePathPtr = wszStoragePathBytes)
                fixed (byte* szLocationPtr = szLocationBytes)
                    return Native.XOnlineStorageGetInstallLocation(dwFacility, (wszStoragePathBytes == null) ? IntPtr.Zero : (IntPtr)wszStoragePathPtr, (szLocationBytes == null) ? IntPtr.Zero : (IntPtr)szLocationPtr, pdwLocationSize);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageSetFamilyTitleID")]
        public static extern int XOnlineStorageSetFamilyTitleID(int dwTitleID);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTitleUpdateEx")]
        public static extern int XOnlineTitleUpdateEx(IntPtr pldUpdate);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingPurchase")]
        public static extern int XOnlineOfferingPurchase(int dwUserIndex, long OfferingId, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingCancel")]
        public static extern int XOnlineOfferingCancel(int dwUserIndex, long OfferingId, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingDetails")]
        public static extern int XOnlineOfferingDetails(int dwUserIndex, long OfferingId, int dwLanguage, int dwDescriptionIndex, IntPtr pbBuffer, int dwBufferSize, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingDetailsGetResults")]
        public static extern int XOnlineOfferingDetailsGetResults(int hTask, IntPtr pDetails);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingDetailsMaxSize")]
        public static extern int XOnlineOfferingDetailsMaxSize(int dwTitleSpecificDataMaxSize);

        public static unsafe int XOnlineOfferingPriceFormat(IntPtr pPrice, string lpFormattedPrice, IntPtr pdwLength, int dwExtendedCharsFilter)
        {
            byte[] lpFormattedPriceBytes = lpFormattedPrice == null ? null : ToWide(lpFormattedPrice);
            fixed (byte* lpFormattedPricePtr = lpFormattedPriceBytes)
                return Native.XOnlineOfferingPriceFormat(pPrice, (lpFormattedPriceBytes == null) ? IntPtr.Zero : (IntPtr)lpFormattedPricePtr, pdwLength, dwExtendedCharsFilter);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingIsNewContentAvailable")]
        public static extern int XOnlineOfferingIsNewContentAvailable(int dwBitFilter, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingEnumerate")]
        public static extern int XOnlineOfferingEnumerate(int dwUserIndex, IntPtr pEnumParams, IntPtr pbBuffer, int dwBufferSize, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingEnumerateGetResults")]
        public static extern int XOnlineOfferingEnumerateGetResults(int hTask, IntPtr prgpOfferingInfo, IntPtr pdwReturnedResults, IntPtr pfMoreResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingEnumerateMaxSize")]
        public static extern int XOnlineOfferingEnumerateMaxSize(IntPtr pEnumParams, int dwTitleSpecificDataMaxSize);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineContentInstall")]
        public static extern int XOnlineContentInstall(long OfferingId, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineContentInstallGetProgress")]
        public static extern int XOnlineContentInstallGetProgress(int hTask, IntPtr pdwPercentDone, IntPtr pqwNumerator, IntPtr pqwDenominator);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineContentInstallGetSize")]
        public static extern int XOnlineContentInstallGetSize(int hTask, IntPtr pdwTotalInstalledSizeInBlocks, IntPtr pdwAdditionalBlocksRequired);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineContentSetSecurityKey")]
        public static extern int XOnlineContentSetSecurityKey(IntPtr pbSecretKey);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageEnumerate")]
        public static extern int XOnlineMessageEnumerate(int dwUserIndex, IntPtr pMsgSummaries, IntPtr pdwNumMsgSummaries);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSummary")]
        public static extern int XOnlineMessageSummary(int dwUserIndex, int dwMessageID, IntPtr pMsgSummary);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDetails")]
        public static extern int XOnlineMessageDetails(int dwUserIndex, int dwMessageID, int dwMessageFlagsToSet, int dwMessageFlagsToClear, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDetailsGetResultsSummary")]
        public static extern int XOnlineMessageDetailsGetResultsSummary(int hTask, IntPtr pMsgSummary, IntPtr pdwNumProperties, IntPtr pqwAttachmentsSize);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDetailsGetResultsProperty")]
        public static extern int XOnlineMessageDetailsGetResultsProperty(int hTask, int wPropTag, int dwPropValueBufferSize, IntPtr pPropValue, IntPtr pdwPropValueSize, IntPtr pdwAttachmentFlags);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDownloadAttachmentToMemory")]
        public static extern int XOnlineMessageDownloadAttachmentToMemory(int hDetailsTask, int wPropTag, IntPtr pbBuffer, int dwBufferSize, IntPtr hWorkEvent, IntPtr phDownloadTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDownloadAttachmentToMemoryGetResults")]
        public static extern int XOnlineMessageDownloadAttachmentToMemoryGetResults(int hDownloadTask, IntPtr ppbReceivedData, IntPtr pdwReceivedDataSize, IntPtr pdwTotalDataSize);

        public static unsafe int XOnlineMessageDownloadAttachmentToDirectory(int hDetailsTask, int wPropTag, string lpLocalPath, IntPtr hWorkEvent, IntPtr phDownloadTask)
        {
            byte[] lpLocalPathBytes = lpLocalPath == null ? null : ToAnsi(lpLocalPath);
            fixed (byte* lpLocalPathPtr = lpLocalPathBytes)
                return Native.XOnlineMessageDownloadAttachmentToDirectory(hDetailsTask, wPropTag, (lpLocalPathBytes == null) ? IntPtr.Zero : (IntPtr)lpLocalPathPtr, hWorkEvent, phDownloadTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDownloadAttachmentGetProgress")]
        public static extern int XOnlineMessageDownloadAttachmentGetProgress(int hDownloadTask, IntPtr pdwPercentDone, IntPtr pqwNumerator, IntPtr pqwDenominator);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSetFlags")]
        public static extern int XOnlineMessageSetFlags(int dwUserIndex, int dwMessageID, int dwMessageFlagsToSet, int dwMessageFlagsToClear, IntPtr hWorkEvent, IntPtr phTask);

        public static int XOnlineMessageDelete(int dwUserIndex, int dwMessageID, bool fBlockSender)
        {
            return Native.XOnlineMessageDelete(dwUserIndex, dwMessageID, fBlockSender ? 1 : 0);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageCreate")]
        public static extern int XOnlineMessageCreate(int bMsgType, int wNumProperties, int wExpectedValuesSize, long qwMessageContext, int dwMessageFlags, int wExpireMinutes, IntPtr phMsg);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDestroy")]
        public static extern int XOnlineMessageDestroy(int hMsg);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSetProperty")]
        public static extern int XOnlineMessageSetProperty(int hMsg, int wPropTag, int dwPropValueSize, IntPtr pPropValue, int dwAttachmentFlags);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSend")]
        public static extern int XOnlineMessageSend(int dwUserIndexSender, int hMsg, int dwRecipientCount, IntPtr pxuidRecipients, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSendGetProgress")]
        public static extern int XOnlineMessageSendGetProgress(int hTask, IntPtr pdwPercentDone, IntPtr pqwNumerator, IntPtr pqwDenominator);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSendGetResults")]
        public static extern int XOnlineMessageSendGetResults(int hTask, IntPtr pMsgSendResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageRevoke")]
        public static extern int XOnlineMessageRevoke(int dwUserIndex, int dwNumMsgSendResults, IntPtr pMsgSendResults, IntPtr hWorkEvent, IntPtr phTask);

        public static bool XOnlineMessageSetSummaryRefresh(bool fEnable)
        {
            return Native.XOnlineMessageSetSummaryRefresh(fEnable ? 1 : 0) != 0;
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageEnableReceivingFamilyTitleIDs")]
        public static extern int XOnlineMessageEnableReceivingFamilyTitleIDs(int dwNumTitleIDs, IntPtr pdwTitleIDs);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSetSendingFamilyTitleID")]
        public static extern int XOnlineMessageSetSendingFamilyTitleID(int dwTitleID);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSessionCreate")]
        public static extern int XOnlineMatchSessionCreate(int dwPublicFilled, int dwPublicOpen, int dwPrivateFilled, int dwPrivateOpen, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSessionUpdate")]
        public static extern int XOnlineMatchSessionUpdate(long SessionID, int dwPublicFilled, int dwPublicOpen, int dwPrivateFilled, int dwPrivateOpen, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSessionGetInfo")]
        public static extern int XOnlineMatchSessionGetInfo(int hTask, IntPtr pSessionID, IntPtr pKeyExchangeKey);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSessionDelete")]
        public static extern int XOnlineMatchSessionDelete(long SessionID, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSessionFindFromID")]
        public static extern int XOnlineMatchSessionFindFromID(long SessionID, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSearch")]
        public static extern int XOnlineMatchSearch(int dwProcedureIndex, int dwNumResults, int dwNumAttributes, IntPtr pAttributes, int dwResultsLen, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSearchGetResults")]
        public static extern int XOnlineMatchSearchGetResults(int hTask, IntPtr prgpSearchResults, IntPtr pdwReturnedResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSearchParse")]
        public static extern int XOnlineMatchSearchParse(IntPtr pSearchResult, int dwNumSessionAttributes, IntPtr pSessionAttributeSpec, IntPtr pQuerySession);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMatchSearchResultsLen")]
        public static extern int XOnlineMatchSearchResultsLen(int dwNumResults, int dwNumSessionAttributes, IntPtr pSessionAttributeSpec);

        public static bool XOnlineTitleIdIsSameTitle(int dwTitleID)
        {
            return Native.XOnlineTitleIdIsSameTitle(dwTitleID) != 0;
        }

        public static bool XOnlineTitleIdIsSamePublisher(int dwTitleID)
        {
            return Native.XOnlineTitleIdIsSamePublisher(dwTitleID) != 0;
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineNotificationSetState")]
        public static extern int XOnlineNotificationSetState(int dwUserIndex, int dwStateFlags, long sessionID, int dwStateData, IntPtr pbStateData);

        public static bool XOnlineGetNotification(int dwUserIndex, int NotificationType)
        {
            return Native.XOnlineGetNotification(dwUserIndex, NotificationType) != 0;
        }

        public static bool XOnlineGetNotificationEx(int dwUserIndex, IntPtr pNotificationInfo, IntPtr pdwStateFlags)
        {
            return Native.XOnlineGetNotificationEx(dwUserIndex, pNotificationInfo, pdwStateFlags) != 0;
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsStartup")]
        public static extern int XOnlineFriendsStartup(IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsEnumerate")]
        public static extern int XOnlineFriendsEnumerate(int dwUserIndex, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsEnumerateFinish")]
        public static extern int XOnlineFriendsEnumerateFinish(int hTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGetLatest")]
        public static extern int XOnlineFriendsGetLatest(int dwUserIndex, int dwFriendBufferCount, IntPtr pFriendBuffer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGetLatestByRange")]
        public static extern int XOnlineFriendsGetLatestByRange(int dwUserIndex, int dwRangeStart, IntPtr pdwFriendBuffer, IntPtr pFriendBuffer, IntPtr pdwFriendsBefore, IntPtr pdwFriendsAfter);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGetLatestByFocus")]
        public static extern int XOnlineFriendsGetLatestByFocus(int dwUserIndex, Xuid xuidFriendFocus, int dwBeforeFocus, IntPtr pdwFriendBuffer, IntPtr pFriendBuffer, IntPtr pdwFriendsBefore, IntPtr pdwFriendsAfter);

        public static unsafe int XOnlineFriendsGetTitleName(int dwTitleId, int dwLanguage, int dwMaxTitleNameChars, string lpTitleName)
        {
            byte[] lpTitleNameBytes = lpTitleName == null ? null : ToWide(lpTitleName);
            fixed (byte* lpTitleNamePtr = lpTitleNameBytes)
                return Native.XOnlineFriendsGetTitleName(dwTitleId, dwLanguage, dwMaxTitleNameChars, (lpTitleNameBytes == null) ? IntPtr.Zero : (IntPtr)lpTitleNamePtr);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsRemove")]
        public static extern int XOnlineFriendsRemove(int dwUserIndex, IntPtr pFriend);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsRequest")]
        public static extern int XOnlineFriendsRequest(int dwUserIndex, Xuid xuidToUser);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsRequestEx")]
        public static extern int XOnlineFriendsRequestEx(int dwUserIndex, Xuid xuidToUser, int hMsg, IntPtr hWorkEvent, IntPtr phTask);

        public static unsafe int XOnlineFriendsRequestByNameEx(int dwUserIndex, string lpUserName, int hMsg, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] lpUserNameBytes = lpUserName == null ? null : ToAnsi(lpUserName);
            fixed (byte* lpUserNamePtr = lpUserNameBytes)
                return Native.XOnlineFriendsRequestByNameEx(dwUserIndex, (lpUserNameBytes == null) ? IntPtr.Zero : (IntPtr)lpUserNamePtr, hMsg, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGameInvite")]
        public static extern int XOnlineFriendsGameInvite(int dwUserIndex, long SessionID, int dwFriendListCount, IntPtr pToFriendList);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsRevokeGameInvite")]
        public static extern int XOnlineFriendsRevokeGameInvite(int dwUserIndex, long SessionID, int dwFriendListCount, IntPtr pToFriendList);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsAnswerRequest")]
        public static extern int XOnlineFriendsAnswerRequest(int dwUserIndex, IntPtr pToFriend, int Answer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsAnswerGameInvite")]
        public static extern int XOnlineFriendsAnswerGameInvite(int dwUserIndex, IntPtr pToFriend, int Answer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsJoinGame")]
        public static extern int XOnlineFriendsJoinGame(int dwUserIndex, IntPtr pToFriend);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGetAcceptedGameInvite")]
        public static extern int XOnlineFriendsGetAcceptedGameInvite(IntPtr pAcceptedGameInvite);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMutelistGet")]
        public static extern int XOnlineMutelistGet(int dwUserIndex, int dwMutelistUserBufferCount, IntPtr hWorkEvent, IntPtr phTask, IntPtr pMutelistUsersBuffer, IntPtr pdwNumMustlistUsers);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMutelistStartup")]
        public static extern int XOnlineMutelistStartup(IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMutelistAdd")]
        public static extern int XOnlineMutelistAdd(int dwUserIndex, Xuid xUserID);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMutelistRemove")]
        public static extern int XOnlineMutelistRemove(int dwUserIndex, Xuid xUserID);

        public static unsafe int XOnlineVerifyNickname(string lpNickname, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] lpNicknameBytes = lpNickname == null ? null : ToWide(lpNickname);
            fixed (byte* lpNicknamePtr = lpNicknameBytes)
                return Native.XOnlineVerifyNickname((lpNicknameBytes == null) ? IntPtr.Zero : (IntPtr)lpNicknamePtr, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFeedbackSend")]
        public static extern int XOnlineFeedbackSend(int dwUserIndex, Xuid xTargetUser, int FeedbackType, IntPtr pParams, IntPtr hWorkEvent, IntPtr phTask);

        public static unsafe int XOnlineStringVerify(int wNumStrings, string ppwStrings, int dwLanguage, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] ppwStringsBytes = ppwStrings == null ? null : ToWide(ppwStrings);
            fixed (byte* ppwStringsPtr = ppwStringsBytes)
                return Native.XOnlineStringVerify(wNumStrings, (ppwStringsBytes == null) ? IntPtr.Zero : (IntPtr)ppwStringsPtr, dwLanguage, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStringVerifyGetResults")]
        public static extern int XOnlineStringVerifyGetResults(int hTask, int wNumResults, IntPtr pResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStringLookupEx")]
        public static extern int XOnlineStringLookupEx(int dwTitleID, int wNumStringIDs, IntPtr pdwStringIDs, int dwLanguage, IntPtr hWorkEvent, IntPtr phTask);

        public static unsafe int XOnlineStringLookupGetResults(int hTask, IntPtr pbBuffer, IntPtr pdwBufferSize, string ppwszStrings, IntPtr pwNumStrings)
        {
            byte[] ppwszStringsBytes = ppwszStrings == null ? null : ToWide(ppwszStrings);
            fixed (byte* ppwszStringsPtr = ppwszStringsBytes)
                return Native.XOnlineStringLookupGetResults(hTask, pbBuffer, pdwBufferSize, (ppwszStringsBytes == null) ? IntPtr.Zero : (IntPtr)ppwszStringsPtr, pwNumStrings);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryAdd")]
        public static extern int XOnlineQueryAdd(int dwUserIndex, long qwTeamId, int dwDatasetId, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryAddGetResults")]
        public static extern int XOnlineQueryAddGetResults(int hTask, IntPtr pEntityId);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryUpdate")]
        public static extern int XOnlineQueryUpdate(int dwUserIndex, long qwTeamId, int dwDatasetId, int dwProcIndex, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryUpdateId")]
        public static extern int XOnlineQueryUpdateId(int dwUserIndex, long qwTeamId, int dwDatasetId, int dwProcIndex, long entityId, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryGetResultsBufferSize")]
        public static extern int XOnlineQueryGetResultsBufferSize(int dwNumResults, int dwNumSpecs, IntPtr pSpecs);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQuerySearch")]
        public static extern int XOnlineQuerySearch(int dwDatasetId, int dwProcIndex, int dwPage, int dwResultsPerPage, int dwNumResultSpecs, IntPtr pAttributeSpecs, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQuerySearchGetResults")]
        public static extern int XOnlineQuerySearchGetResults(int hTask, IntPtr pdwTotalResults, IntPtr pdwReturnedResults, IntPtr pdwResultsSize, IntPtr pbResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryFindFromIds")]
        public static extern int XOnlineQueryFindFromIds(int dwDatasetId, int dwProcIndex, int dwNumResultSpecs, IntPtr pAttributeSpecs, int dwNumEntityIds, IntPtr pEntityIds, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryFindFromIdsGetResults")]
        public static extern int XOnlineQueryFindFromIdsGetResults(int hTask, IntPtr pdwReturnedResults, IntPtr pResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryRemove")]
        public static extern int XOnlineQueryRemove(int dwUserIndex, long qwTeamId, int dwDatasetId, int dwProcIndex, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQueryRemoveId")]
        public static extern int XOnlineQueryRemoveId(int dwUserIndex, long qwTeamId, int dwDatasetId, long entityId, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineQuerySelect")]
        public static extern int XOnlineQuerySelect(int dwUserIndex, long qwTeamId, int dwDatasetId, long entityId, int dwAction, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetSession")]
        public static extern int XOnlineGetSession(IntPtr pxnaddr, IntPtr pxnkid, IntPtr pxnkey);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetUserSession")]
        public static extern int XOnlineGetUserSession(int dwUserIndex, Xuid xuidPeer, IntPtr hWorkEvent, IntPtr phTask, IntPtr pResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGameInviteSend")]
        public static extern int XOnlineGameInviteSend(int dwUserIndex, int dwPeerCount, IntPtr pxuidPeersToInvite, long SessionID, int dwFlags, int hMsg, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGameInviteAnswer")]
        public static extern int XOnlineGameInviteAnswer(int dwUserIndex, IntPtr pGameInviteAnswerInfo, int GameInviteAnswer, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGameInviteRevoke")]
        public static extern int XOnlineGameInviteRevoke(int dwUserIndex, int dwPeerCount, IntPtr pxuidPeersToRevoke, long SessionID, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGameInviteGetLatestAccepted")]
        public static extern int XOnlineGameInviteGetLatestAccepted(IntPtr pLatestAcceptedGameInvite);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGameJoin")]
        public static extern int XOnlineGameJoin(int dwUserIndex, IntPtr pGameJoinInfo);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamCreate")]
        public static extern int XOnlineTeamCreate(int dwUserIndex, IntPtr pTeamProperties, IntPtr pFirstTeamMemberProperties, int dwMaxTeamMemberCount, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamCreateGetResults")]
        public static extern int XOnlineTeamCreateGetResults(int hTask, IntPtr pTeam);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamSetProperties")]
        public static extern int XOnlineTeamSetProperties(int dwUserIndex, Xuid xuidTeam, IntPtr pTeamProperties, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamDelete")]
        public static extern int XOnlineTeamDelete(int dwUserIndex, Xuid xuidTeam, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberSetProperties")]
        public static extern int XOnlineTeamMemberSetProperties(int dwUserIndex, Xuid xuidTeam, Xuid xuidTeamMember, IntPtr pTeamMemberProperties, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberRemove")]
        public static extern int XOnlineTeamMemberRemove(int dwUserIndex, Xuid xuidTeam, Xuid xuidTeamMember, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberRecruit")]
        public static extern int XOnlineTeamMemberRecruit(int dwUserIndex, Xuid xuidTeam, Xuid xuidPeer, IntPtr pPeerTeamMemberInfo, int hMsg, IntPtr hWorkEvent, IntPtr phTask);

        public static unsafe int XOnlineTeamMemberRecruitByName(int dwUserIndex, Xuid xuidTeam, string lpPeerName, IntPtr pPeerTeamMemberInfo, int hMsg, IntPtr hWorkEvent, IntPtr phTask)
        {
            byte[] lpPeerNameBytes = lpPeerName == null ? null : ToAnsi(lpPeerName);
            fixed (byte* lpPeerNamePtr = lpPeerNameBytes)
                return Native.XOnlineTeamMemberRecruitByName(dwUserIndex, xuidTeam, (lpPeerNameBytes == null) ? IntPtr.Zero : (IntPtr)lpPeerNamePtr, pPeerTeamMemberInfo, hMsg, hWorkEvent, phTask);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberAnswerRecruit")]
        public static extern int XOnlineTeamMemberAnswerRecruit(int dwUserIndex, Xuid xuidTeam, int RecruitAnswer, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamEnumerate")]
        public static extern int XOnlineTeamEnumerate(int dwUserIndex, int dwTeamCount, IntPtr pxuidTeams, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamEnumerateByUserXUID")]
        public static extern int XOnlineTeamEnumerateByUserXUID(int dwUserIndex, Xuid xuidUser, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamEnumerateGetResults")]
        public static extern int XOnlineTeamEnumerateGetResults(int hTask, IntPtr pdwTeamCount, IntPtr pxuidTeams);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamGetDetails")]
        public static extern int XOnlineTeamGetDetails(int hTask, Xuid xuidTeam, IntPtr pTeamInfo);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMembersEnumerate")]
        public static extern int XOnlineTeamMembersEnumerate(int dwUserIndex, Xuid xuidTeam, int dwFlags, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMembersEnumerateGetResults")]
        public static extern int XOnlineTeamMembersEnumerateGetResults(int hTask, IntPtr pdwTeamMemberCount, IntPtr pxuidTeamMembers);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberGetDetails")]
        public static extern int XOnlineTeamMemberGetDetails(int hTask, Xuid xuidTeamMember, IntPtr pTeamMemberInfo);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamSetFamilyTitleID")]
        public static extern int XOnlineTeamSetFamilyTitleID(int dwTitleID);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceInit")]
        public static extern int XOnlinePresenceInit(int dwUserIndex, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceAdd")]
        public static extern int XOnlinePresenceAdd(int hTask, int dwGroupID, int dwUserCount, IntPtr pxuidUsers);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceClear")]
        public static extern int XOnlinePresenceClear(int hTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceSubmit")]
        public static extern int XOnlinePresenceSubmit(int hTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceGetLatest")]
        public static extern int XOnlinePresenceGetLatest(int hTask, int dwGroupID, int dwUserPresenceBufferCount, IntPtr pUserPresence);

        public static unsafe int XOnlinePresenceGetTitleName(int hTask, int dwTitleID, int dwLanguage, int dwTitleNameSize, string wszTitleName)
        {
            byte[] wszTitleNameBytes = wszTitleName == null ? null : ToWide(wszTitleName);
            fixed (byte* wszTitleNamePtr = wszTitleNameBytes)
                return Native.XOnlinePresenceGetTitleName(hTask, dwTitleID, dwLanguage, dwTitleNameSize, (wszTitleNameBytes == null) ? IntPtr.Zero : (IntPtr)wszTitleNamePtr);
        }

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatWrite")]
        public static extern int XOnlineStatWrite(int dwNumStatSpecs, IntPtr pStatSpecs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatWriteEx")]
        public static extern int XOnlineStatWriteEx(int dwNumStatProcs, IntPtr pStatProcs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatWriteGetResult")]
        public static extern int XOnlineStatWriteGetResult(int hTask, IntPtr phServerFileReference, IntPtr prgReferences, IntPtr pdwReferences);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatRead")]
        public static extern int XOnlineStatRead(int dwNumStatSpecs, IntPtr pStatSpecs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatReadGetResult")]
        public static extern int XOnlineStatReadGetResult(int hTask, int dwNumStatSpecs, IntPtr pStatSpecs, int dwExtraBufferSize, IntPtr pExtraBuffer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatUnitRead")]
        public static extern int XOnlineStatUnitRead(IntPtr pxuidUnitMembers, int dwNumStatSpecUnits, IntPtr pStatSpecUnits, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatUnitReadGetResult")]
        public static extern int XOnlineStatUnitReadGetResult(int hTask, int dwNumStatSpecUnits, IntPtr pStatSpecUnits);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatLeaderEnumerate")]
        public static extern int XOnlineStatLeaderEnumerate(IntPtr pxuidPagePivot, int dwPageStart, int dwPageSize, int dwLeaderboardID, int dwNumStatsPerUser, IntPtr pStatsPerUser, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatLeaderEnumerateGetResults")]
        public static extern int XOnlineStatLeaderEnumerateGetResults(int hTask, int dwUserCount, IntPtr pUsers, int dwStatCount, IntPtr pStats, IntPtr pdwLeaderboardSize, IntPtr pdwReturnedResults, int dwExtraBufferSize, IntPtr pExtraBuffer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatUnitEnumerate")]
        public static extern int XOnlineStatUnitEnumerate(Xuid xuidUnitMember, int dwLeaderboardID, int SortOrder, int dwMaxUnitsToReturn, int dwNumStatsPerUnit, IntPtr pStatsPerUnit, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatUnitEnumerateGetResults")]
        public static extern int XOnlineStatUnitEnumerateGetResults(int hTask, IntPtr pUnits, int dwStatCount, IntPtr pStats, IntPtr pdwReturnedResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStatReset")]
        public static extern int XOnlineStatReset(Xuid xuid, int dwLeaderBoardId, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineArbitrationCreateRoundID")]
        public static extern int XOnlineArbitrationCreateRoundID(IntPtr pqwRoundID);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineArbitrationRegister")]
        public static extern int XOnlineArbitrationRegister(IntPtr pArbID, int wMaxRoundSeconds, int dwFlags, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineArbitrationRegisterGetResults")]
        public static extern int XOnlineArbitrationRegisterGetResults(int hTask, int dwRegistrantsBufferCount, IntPtr pRegistrants, IntPtr pdwNumRegistrants);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineArbitrationExtendRound")]
        public static extern int XOnlineArbitrationExtendRound(IntPtr pArbID, int wMaxSecondsFromNow, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineArbitrationReport")]
        public static extern int XOnlineArbitrationReport(IntPtr pArbID, int dwNumStatProcs, IntPtr pStatProcs, IntPtr pReportData, int dwFlags, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionCreate")]
        public static extern int XOnlineCompetitionCreate(int dwUserIndex, int dwTemplate, long qwTeamID, int dwNumCompetitionAttributes, IntPtr pCompetitionAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionCreateGetResults")]
        public static extern int XOnlineCompetitionCreateGetResults(int hTask, IntPtr pCompResults);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionCreateSingleElimination")]
        public static extern int XOnlineCompetitionCreateSingleElimination(int dwUserIndex, int dwTemplate, long qwTeamID, IntPtr pDefaultAttributes, int dwNumAdditionalAttributes, IntPtr pAdditionalAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionSearch")]
        public static extern int XOnlineCompetitionSearch(int dwQueryID, int dwTarget, int dwPage, int dwResultsPerPage, int dwNumSearchAttributes, IntPtr pSearchAttributes, int dwNumResultAttributeSpecs, IntPtr pResultAttributeSpecs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionSearchGetResults")]
        public static extern int XOnlineCompetitionSearchGetResults(int hTask, IntPtr pdwTotalItemsInSearchResult, IntPtr pdwItemsReturned, IntPtr pdwResultBufferSize, IntPtr pbResultBuffer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionGetResultsBufferSize")]
        public static extern int XOnlineCompetitionGetResultsBufferSize(int dwResultsPerPage, int dwNumSpecs, IntPtr pSpecs);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionManageEntrant")]
        public static extern int XOnlineCompetitionManageEntrant(int dwAction, int dwUserIndex, int dwTemplate, long qwTeamID, long qwCompetitionID, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionCheckin")]
        public static extern int XOnlineCompetitionCheckin(int dwUserIndex, int dwTemplate, long qwTeamID, long qwCompetitionID, long qwEventID, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionCancel")]
        public static extern int XOnlineCompetitionCancel(int dwUserIndex, int dwTemplate, long qwTeamID, long qwCompetitionID, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionSessionRegister")]
        public static extern int XOnlineCompetitionSessionRegister(IntPtr pArbitrationID, int wMaxRoundSeconds, int dwArbitrationRegisterFlags, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionSessionRegisterGetResults")]
        public static extern int XOnlineCompetitionSessionRegisterGetResults(int hTask, int dwRegistrantsBufferCount, IntPtr pRegistrants, IntPtr pdwNumRegistrants);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionSubmitResults")]
        public static extern int XOnlineCompetitionSubmitResults(int dwTemplate, long qwCompetitionID, IntPtr pArbitrationID, int dwArbitrationReportFlags, IntPtr pArbitrationReportData, int dwNumStatProcs, IntPtr pStatProcs, int dwNumAttributes, IntPtr pAttributes, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionTopology")]
        public static extern int XOnlineCompetitionTopology(int dwTemplate, long qwCompetitionID, int dwPage, int dwResultsPerPage, int dwStartingEventTopologyID, int dwEndingEventTopologyID, int dwNumResultAttributeSpecs, IntPtr pResultAttributeSpecs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionTopologyGetResults")]
        public static extern int XOnlineCompetitionTopologyGetResults(int hTask, IntPtr pdwTotalItemsInSearchResult, IntPtr pdwItemsReturned, IntPtr pdwResultBufferSize, IntPtr pbResultBuffer);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionTopologySingleElimination")]
        public static extern int XOnlineCompetitionTopologySingleElimination(int dwTemplate, long qwCompetitionID, int dwOriginEventTopologyID, int dwRoundsForward, int dwRoundsBackward, int dwTopWidth, int dwNumResultAttributeSpecs, IntPtr pResultAttributeSpecs, IntPtr hWorkEvent, IntPtr phTask);

        [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineCompetitionTopologySingleEliminationGetResults")]
        public static extern int XOnlineCompetitionTopologySingleEliminationGetResults(int hTask, IntPtr ppTopologyResults);

        public static unsafe int XOnlineThrottleSet(int dwServiceID, string szThrottleTag, int dwThrottleFlags, int dwDelay)
        {
            byte[] szThrottleTagBytes = szThrottleTag == null ? null : ToAnsi(szThrottleTag);
            fixed (byte* szThrottleTagPtr = szThrottleTagBytes)
                return Native.XOnlineThrottleSet(dwServiceID, (szThrottleTagBytes == null) ? IntPtr.Zero : (IntPtr)szThrottleTagPtr, dwThrottleFlags, dwDelay);
        }

        public static unsafe int XOnlineThrottleGet(int dwServiceID, string szThrottleTag, IntPtr pdwThrottleFlags, IntPtr pdwDelay)
        {
            byte[] szThrottleTagBytes = szThrottleTag == null ? null : ToAnsi(szThrottleTag);
            fixed (byte* szThrottleTagPtr = szThrottleTagBytes)
                return Native.XOnlineThrottleGet(dwServiceID, (szThrottleTagBytes == null) ? IntPtr.Zero : (IntPtr)szThrottleTagPtr, pdwThrottleFlags, pdwDelay);
        }

        static byte[] ToAnsi(string text)
        {
            return Encoding.ASCII.GetBytes(text + "\0");
        }

        static byte[] ToWide(string text)
        {
            return Encoding.Unicode.GetBytes(text + "\0");
        }

        static class Native
        {
            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageUpload")]
            public static extern int XOnlineStorageUpload(IntPtr hServerFileReference, IntPtr szDirectory, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageCreateServerPath")]
            public static extern int XOnlineStorageCreateServerPath(int dwFacility, long qwUserID, long qwTeamID, IntPtr wszStorageFileName, IntPtr wszStorageServerPath, IntPtr pcchStorageServerPath);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageUploadByServerPath")]
            public static extern int XOnlineStorageUploadByServerPath(int dwFacility, int dwUserIndex, IntPtr wszStorageFileName, long ftServerExpirationDate, IntPtr szDirectory, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageDownload")]
            public static extern int XOnlineStorageDownload(int dwFacility, int dwUserIndex, IntPtr wszStoragePath, IntPtr szInstallDirectory, int dwDownloadFlags, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageUploadFromMemory")]
            public static extern int XOnlineStorageUploadFromMemory(int dwFacility, int dwUserIndex, IntPtr wszStorageFileName, long ftServerExpirationDate, IntPtr pbDataToUpload, int cbDataToUpload, int dwUploadFlags, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageDownloadToMemory")]
            public static extern int XOnlineStorageDownloadToMemory(int dwFacility, int dwUserIndex, IntPtr wszStoragePath, IntPtr pbReceiveBuffer, int cbReceiveBuffer, int dwDownloadFlags, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageDeleteFile")]
            public static extern int XOnlineStorageDeleteFile(int dwFacility, int dwUserIndex, IntPtr wszStorageFileName, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageEnumerate")]
            public static extern int XOnlineStorageEnumerate(int dwFacility, int dwUserIndex, IntPtr wszStorageEnumerationPath, int dwStartingIndex, int cMaxResultsToReturn, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStorageGetInstallLocation")]
            public static extern int XOnlineStorageGetInstallLocation(int dwFacility, IntPtr wszStoragePath, IntPtr szLocation, IntPtr pdwLocationSize);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineOfferingPriceFormat")]
            public static extern int XOnlineOfferingPriceFormat(IntPtr pPrice, IntPtr lpFormattedPrice, IntPtr pdwLength, int dwExtendedCharsFilter);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDownloadAttachmentToDirectory")]
            public static extern int XOnlineMessageDownloadAttachmentToDirectory(int hDetailsTask, int wPropTag, IntPtr lpLocalPath, IntPtr hWorkEvent, IntPtr phDownloadTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageDelete")]
            public static extern int XOnlineMessageDelete(int dwUserIndex, int dwMessageID, int fBlockSender);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineMessageSetSummaryRefresh")]
            public static extern int XOnlineMessageSetSummaryRefresh(int fEnable);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTitleIdIsSameTitle")]
            public static extern int XOnlineTitleIdIsSameTitle(int dwTitleID);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTitleIdIsSamePublisher")]
            public static extern int XOnlineTitleIdIsSamePublisher(int dwTitleID);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetNotification")]
            public static extern int XOnlineGetNotification(int dwUserIndex, int NotificationType);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineGetNotificationEx")]
            public static extern int XOnlineGetNotificationEx(int dwUserIndex, IntPtr pNotificationInfo, IntPtr pdwStateFlags);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsGetTitleName")]
            public static extern int XOnlineFriendsGetTitleName(int dwTitleId, int dwLanguage, int dwMaxTitleNameChars, IntPtr lpTitleName);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineFriendsRequestByNameEx")]
            public static extern int XOnlineFriendsRequestByNameEx(int dwUserIndex, IntPtr lpUserName, int hMsg, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineVerifyNickname")]
            public static extern int XOnlineVerifyNickname(IntPtr lpNickname, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStringVerify")]
            public static extern int XOnlineStringVerify(int wNumStrings, IntPtr ppwStrings, int dwLanguage, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineStringLookupGetResults")]
            public static extern int XOnlineStringLookupGetResults(int hTask, IntPtr pbBuffer, IntPtr pdwBufferSize, IntPtr ppwszStrings, IntPtr pwNumStrings);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineTeamMemberRecruitByName")]
            public static extern int XOnlineTeamMemberRecruitByName(int dwUserIndex, Xuid xuidTeam, IntPtr lpPeerName, IntPtr pPeerTeamMemberInfo, int hMsg, IntPtr hWorkEvent, IntPtr phTask);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlinePresenceGetTitleName")]
            public static extern int XOnlinePresenceGetTitleName(int hTask, int dwTitleID, int dwLanguage, int dwTitleNameSize, IntPtr wszTitleName);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineThrottleSet")]
            public static extern int XOnlineThrottleSet(int dwServiceID, IntPtr szThrottleTag, int dwThrottleFlags, int dwDelay);

            [DllImport("xonline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_xonline_XOnlineThrottleGet")]
            public static extern int XOnlineThrottleGet(int dwServiceID, IntPtr szThrottleTag, IntPtr pdwThrottleFlags, IntPtr pdwDelay);

        }
    }
}
