#!/usr/bin/env bash
# The remaining RXDK SDK libraries, one assembly each. Sources and binds are
# generated by scripts/gen-sdklibs.py. Each sidecar names its own native lib so
# build-host only links what the title actually references.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/toolchain.sh"
OUT="$ROOT/build-out/corlib"
CORLIB="$OUT/mscorlib.dll"

[ -f "$CORLIB" ] || { echo "ERROR: $CORLIB not found — build corlib first"; exit 1; }
mkdir -p "$OUT"

# assembly:source
SETS="Rxdk.Audio:Audio Rxdk.Music:Music Rxdk.Xact:Xact Rxdk.Video:Video Rxdk.Uix:Uix Rxdk.Online:Online Rxdk.Voice:Voice"

rc=0
for entry in $SETS; do
  asm="${entry%%:*}"
  cls="${entry##*:}"
  src="$ROOT/src/$asm/$cls.cs"
  dll="$OUT/$asm.dll"
  log="$OUT/$(echo "$asm" | tr 'A-Z.' 'a-z-').log"
  [ -f "$src" ] || { echo "ERROR: $src missing — run scripts/gen-sdklibs.py"; exit 1; }
  echo "== compiling $asm.dll =="
  MSYS2_ARG_CONV_EXCL='*' dotnet exec "$(cygpath -w "$CSC")" -nostdlib -noconfig -target:library -unsafe -optimize+ \
    -out:"$(cygpath -w "$dll")" -reference:"$(cygpath -w "$CORLIB")" \
    "$(cygpath -w "$src")" > "$log" 2>&1
  if [ "$?" != 0 ]; then
    echo "$asm.dll FAILED"
    grep -iE 'error' "$log" | head
    rc=1
    continue
  fi
  cp "$ROOT/src/$asm/$asm.dll.libs" "$OUT/$asm.dll.libs"
  echo "$asm.dll: $(stat -c%s "$dll" 2>/dev/null) bytes"
done
exit $rc
