#!/usr/bin/env python
"""Generate an internal SR class from corefx .resx string tables.

corefx sources throw with SR.SomeName, where SR is generated per-assembly from that project's
Resources/Strings.resx. We compile those sources outside their own build, so we generate the same
class here instead of hand-copying message text. mscorlib has an SR but it is internal to corlib
and cannot be extended across an assembly boundary.

  python scripts/gen-sr.py out.cs strings.resx [more.resx ...]

Later files do not override earlier ones, so pass the owning project's resx first.
"""
import sys
import xml.etree.ElementTree as ET

HEADER = """// Generated by scripts/gen-sr.py from corefx .resx string tables. Do not edit.
internal static class SR
{
"""

FOOTER = """
    internal static string Format(string fmt, params object[] args) => string.Format(fmt, args);
    internal static string Format(string fmt, object a) => string.Format(fmt, a);
    internal static string Format(string fmt, object a, object b) => string.Format(fmt, a, b);
    internal static string Format(string fmt, object a, object b, object c) => string.Format(fmt, a, b, c);
}
"""


def literal(text):
    """A C# verbatim string, which needs only doubled quotes."""
    return '@"' + text.replace('"', '""') + '"'


def main(argv):
    if len(argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    out_path, resx_paths = argv[1], argv[2:]

    strings = {}
    for path in resx_paths:
        for node in ET.parse(path).getroot().findall('data'):
            name = node.get('name')
            value = node.find('value')
            if not name or value is None or value.text is None:
                continue
            # resx allows names that are not C# identifiers; those are never used as SR members.
            if not name.replace('_', 'a').isalnum() or name[0].isdigit():
                continue
            strings.setdefault(name, value.text)

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(HEADER)
        for name in sorted(strings):
            f.write('    internal static string %s => %s;\n' % (name, literal(strings[name])))
        f.write(FOOTER)
    print('%s: %d strings from %d resx' % (out_path, len(strings), len(resx_paths)))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
