// Generated by scripts/gen-sdklibs.py. Do not edit.
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Rxdk
{
    public static class Music
    {
        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicCreateInstance")]
        public static extern int DirectMusicCreateInstance(int clsid, IntPtr pUnkOuter, int iid, IntPtr ppvInterface);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicDoWork")]
        public static extern void DirectMusicDoWork(int dwQuantum);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicAlloc")]
        public static extern void DirectMusicAlloc(int cb);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicFree")]
        public static extern void DirectMusicFree(IntPtr pv);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicPhysicalAlloc")]
        public static extern void DirectMusicPhysicalAlloc(int dwSize);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicPhysicalFree")]
        public static extern void DirectMusicPhysicalFree(IntPtr lpAddress);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicCreateDefaultHeap")]
        public static extern int DirectMusicCreateDefaultHeap(IntPtr ppHeap);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicCreateDefaultPhysicalHeap")]
        public static extern int DirectMusicCreateDefaultPhysicalHeap(IntPtr ppHeap);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicCreateFixedSizeHeap")]
        public static extern int DirectMusicCreateFixedSizeHeap(int cbSize, IntPtr ppHeap);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicCreateFixedSizePhysicalHeap")]
        public static extern int DirectMusicCreateFixedSizePhysicalHeap(int cbSize, IntPtr ppHeap);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicInitialize")]
        public static extern int DirectMusicInitialize();

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicInitializeEx")]
        public static extern int DirectMusicInitializeEx(IntPtr pNormalHeap, IntPtr pPhysicalHeap, IntPtr pFactory);

        [DllImport("dmusic", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, EntryPoint = "rxdk_dmusic_DirectMusicInitializeFixedSizeHeaps")]
        public static extern int DirectMusicInitializeFixedSizeHeaps(int cbNormalHeapSize, int cbPhysicalHeapSize, IntPtr pFactory);

    }
}
