/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

extern int __attribute__((stdcall)) DirectMusicCreateInstance(int a0, void * a1, int a2, void * a3);
extern void __attribute__((stdcall)) DirectMusicDoWork(int a0);
extern void __attribute__((stdcall)) DirectMusicAlloc(int a0);
extern void __attribute__((stdcall)) DirectMusicFree(void * a0);
extern void __attribute__((stdcall)) DirectMusicPhysicalAlloc(int a0);
extern void __attribute__((stdcall)) DirectMusicPhysicalFree(void * a0);
extern int __attribute__((stdcall)) DirectMusicCreateDefaultHeap(void * a0);
extern int __attribute__((stdcall)) DirectMusicCreateDefaultPhysicalHeap(void * a0);
extern int __attribute__((stdcall)) DirectMusicCreateFixedSizeHeap(int a0, void * a1);
extern int __attribute__((stdcall)) DirectMusicCreateFixedSizePhysicalHeap(int a0, void * a1);
extern int __attribute__((stdcall)) DirectMusicInitialize(void);
extern int __attribute__((stdcall)) DirectMusicInitializeEx(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) DirectMusicInitializeFixedSizeHeaps(int a0, int a1, void * a2);

static int rxdk_dmusic_DirectMusicCreateInstance(int a0, void * a1, int a2, void * a3)
{
    return DirectMusicCreateInstance(a0, a1, a2, a3);
}

static void rxdk_dmusic_DirectMusicDoWork(int a0)
{
    DirectMusicDoWork(a0);
}

static void rxdk_dmusic_DirectMusicAlloc(int a0)
{
    DirectMusicAlloc(a0);
}

static void rxdk_dmusic_DirectMusicFree(void * a0)
{
    DirectMusicFree(a0);
}

static void rxdk_dmusic_DirectMusicPhysicalAlloc(int a0)
{
    DirectMusicPhysicalAlloc(a0);
}

static void rxdk_dmusic_DirectMusicPhysicalFree(void * a0)
{
    DirectMusicPhysicalFree(a0);
}

static int rxdk_dmusic_DirectMusicCreateDefaultHeap(void * a0)
{
    return DirectMusicCreateDefaultHeap(a0);
}

static int rxdk_dmusic_DirectMusicCreateDefaultPhysicalHeap(void * a0)
{
    return DirectMusicCreateDefaultPhysicalHeap(a0);
}

static int rxdk_dmusic_DirectMusicCreateFixedSizeHeap(int a0, void * a1)
{
    return DirectMusicCreateFixedSizeHeap(a0, a1);
}

static int rxdk_dmusic_DirectMusicCreateFixedSizePhysicalHeap(int a0, void * a1)
{
    return DirectMusicCreateFixedSizePhysicalHeap(a0, a1);
}

static int rxdk_dmusic_DirectMusicInitialize(void)
{
    return DirectMusicInitialize();
}

static int rxdk_dmusic_DirectMusicInitializeEx(void * a0, void * a1, void * a2)
{
    return DirectMusicInitializeEx(a0, a1, a2);
}

static int rxdk_dmusic_DirectMusicInitializeFixedSizeHeaps(int a0, int a1, void * a2)
{
    return DirectMusicInitializeFixedSizeHeaps(a0, a1, a2);
}

static void *dmusic_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "dmusic") && strcmp(name, "dmusic.dll")) return NULL;
    return (void *)(unsigned long)1145918803u;
}

static void *dmusic_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1145918803u || !name) return NULL;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicCreateInstance")) return (void *)&rxdk_dmusic_DirectMusicCreateInstance;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicDoWork")) return (void *)&rxdk_dmusic_DirectMusicDoWork;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicAlloc")) return (void *)&rxdk_dmusic_DirectMusicAlloc;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicFree")) return (void *)&rxdk_dmusic_DirectMusicFree;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicPhysicalAlloc")) return (void *)&rxdk_dmusic_DirectMusicPhysicalAlloc;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicPhysicalFree")) return (void *)&rxdk_dmusic_DirectMusicPhysicalFree;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicCreateDefaultHeap")) return (void *)&rxdk_dmusic_DirectMusicCreateDefaultHeap;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicCreateDefaultPhysicalHeap")) return (void *)&rxdk_dmusic_DirectMusicCreateDefaultPhysicalHeap;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicCreateFixedSizeHeap")) return (void *)&rxdk_dmusic_DirectMusicCreateFixedSizeHeap;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicCreateFixedSizePhysicalHeap")) return (void *)&rxdk_dmusic_DirectMusicCreateFixedSizePhysicalHeap;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicInitialize")) return (void *)&rxdk_dmusic_DirectMusicInitialize;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicInitializeEx")) return (void *)&rxdk_dmusic_DirectMusicInitializeEx;
    if (!strcmp(name, "rxdk_dmusic_DirectMusicInitializeFixedSizeHeaps")) return (void *)&rxdk_dmusic_DirectMusicInitializeFixedSizeHeaps;
    return NULL;
}

static void *dmusic_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_dmusic_register(void)
{
    mono_dl_fallback_register(dmusic_load, dmusic_symbol, dmusic_close, NULL);
}
