/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

extern int __attribute__((stdcall)) DirectSoundCreate(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) DirectSoundCreateBuffer(void * a0, void * a1);
extern int __attribute__((stdcall)) DirectSoundCreateStream(void * a0, void * a1);
extern void __attribute__((stdcall)) DirectSoundDoWork(void);
extern void __attribute__((stdcall)) DirectSoundUseFullHRTF(void);
extern void __attribute__((stdcall)) DirectSoundUseLightHRTF(void);
extern void __attribute__((stdcall)) DirectSoundOverrideSpeakerConfig(int a0);
extern int __attribute__((stdcall)) DirectSoundGetSampleTime(void);
extern void __attribute__((stdcall)) DirectSoundDumpMemoryUsage(int a0);
extern void __attribute__((stdcall)) XAudioCreatePcmFormat(int a0, int a1, int a2, void * a3);
extern void __attribute__((stdcall)) XAudioCreateAdpcmFormat(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XAudioCalculatePitch(int a0);
extern int __attribute__((stdcall)) XWmaDecoderCreateMediaObject(void * a0, void * a1);
extern int __attribute__((stdcall)) WmaCreateDecoder(void * a0, void * a1, int a2, int a3, int a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) WmaCreateInMemoryDecoder(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) WmaCreateDecoderEx(void * a0, void * a1, int a2, int a3, int a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) WmaCreateInMemoryDecoderEx(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) Ac97CreateMediaObject(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XFileCreateMediaObject(void * a0, int a1, int a2, int a3, int a4, void * a5);
extern int __attribute__((stdcall)) XFileCreateMediaObjectEx(void * a0, void * a1);
extern int __attribute__((stdcall)) XFileCreateMediaObjectAsync(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XWaveFileCreateMediaObject(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XWaveFileCreateMediaObjectEx(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XAudioDownloadEffectsImage(void * a0, void * a1, int a2, void * a3);
extern int __attribute__((stdcall)) XAudioSetEffectData(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IDirectSound_QueryInterface(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IDirectSound_QueryInterfaceC(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IDirectSound_AddRef(void * a0);
extern int __attribute__((stdcall)) IDirectSound_Release(void * a0);
extern int __attribute__((stdcall)) IDirectSound_GetCaps(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSound_SynchPlayback(void * a0);
extern int __attribute__((stdcall)) IDirectSound_CreateSoundBuffer(void * a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) IDirectSound_CreateSoundStream(void * a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) IDirectSound_GetSpeakerConfig(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSound_SetCooperativeLevel(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_Compact(void * a0);
extern int __attribute__((stdcall)) IDirectSound_DownloadEffectsImage(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) IDirectSound_GetEffectData(void * a0, int a1, int a2, void * a3, int a4);
extern int __attribute__((stdcall)) IDirectSound_SetEffectData(void * a0, int a1, int a2, void * a3, int a4, int a5);
extern int __attribute__((stdcall)) IDirectSound_CommitEffectData(void * a0);
extern int __attribute__((stdcall)) IDirectSound_EnableHeadphones(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSound_SetMixBinHeadroom(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_SetAllParameters(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_SetOrientation(void * a0, float a1, float a2, float a3, float a4, float a5, float a6, int a7);
extern int __attribute__((stdcall)) IDirectSound_SetPosition(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSound_SetVelocity(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSound_SetDistanceFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_SetDopplerFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_SetRolloffFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_SetI3DL2Listener(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSound_CommitDeferredSettings(void * a0);
extern int __attribute__((stdcall)) IDirectSound_GetTime(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSound_GetOutputLevels(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_QueryInterface(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_QueryInterfaceC(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_AddRef(void * a0);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Release(void * a0);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetFormat(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetFrequency(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetVolume(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetPitch(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetLFO(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetEG(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetFilter(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetHeadroom(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetOutputBuffer(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetMixBins(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetMixBinVolumes(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetAllParameters(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetConeAngles(void * a0, int a1, int a2, int a3);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetConeOutsideVolume(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetMaxDistance(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetMinDistance(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetMode(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetPosition(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetVelocity(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetDistanceFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetDopplerFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetRolloffFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetRolloffCurve(void * a0, void * a1, int a2, int a3);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetI3DL2Source(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Play(void * a0, int a1, int a2, int a3);
extern int __attribute__((stdcall)) IDirectSoundBuffer_PlayEx(void * a0, long long a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Stop(void * a0);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Pause(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_PauseEx(void * a0, long long a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_StopEx(void * a0, long long a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetPlayRegion(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetLoopRegion(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_GetStatus(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_GetCurrentPosition(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetCurrentPosition(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetBufferData(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Lock(void * a0, int a1, int a2, void * a3, void * a4, void * a5, void * a6, int a7);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Unlock(void * a0, void * a1, int a2, void * a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundBuffer_Restore(void * a0);
extern int __attribute__((stdcall)) IDirectSoundBuffer_SetNotificationPositions(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundBuffer_GetVoiceProperties(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_QueryInterface(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundStream_QueryInterfaceC(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetFormat(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetFrequency(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetVolume(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetPitch(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetLFO(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetEG(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetFilter(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetHeadroom(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetOutputBuffer(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetMixBins(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetMixBinVolumes(void * a0, void * a1);
extern int __attribute__((stdcall)) IDirectSoundStream_SetAllParameters(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetConeAngles(void * a0, int a1, int a2, int a3);
extern int __attribute__((stdcall)) IDirectSoundStream_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundStream_SetConeOutsideVolume(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetMaxDistance(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetMinDistance(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetMode(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetPosition(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundStream_SetVelocity(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IDirectSoundStream_SetDistanceFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetDopplerFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetRolloffFactor(void * a0, float a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_SetRolloffCurve(void * a0, void * a1, int a2, int a3);
extern int __attribute__((stdcall)) IDirectSoundStream_SetI3DL2Source(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_Pause(void * a0, int a1);
extern int __attribute__((stdcall)) IDirectSoundStream_PauseEx(void * a0, long long a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_FlushEx(void * a0, long long a1, int a2);
extern int __attribute__((stdcall)) IDirectSoundStream_GetVoiceProperties(void * a0, void * a1);

static int rxdk_dsound_DirectSoundCreate(void * a0, void * a1, void * a2)
{
    return DirectSoundCreate(a0, a1, a2);
}

static int rxdk_dsound_DirectSoundCreateBuffer(void * a0, void * a1)
{
    return DirectSoundCreateBuffer(a0, a1);
}

static int rxdk_dsound_DirectSoundCreateStream(void * a0, void * a1)
{
    return DirectSoundCreateStream(a0, a1);
}

static void rxdk_dsound_DirectSoundDoWork(void)
{
    DirectSoundDoWork();
}

static void rxdk_dsound_DirectSoundUseFullHRTF(void)
{
    DirectSoundUseFullHRTF();
}

static void rxdk_dsound_DirectSoundUseLightHRTF(void)
{
    DirectSoundUseLightHRTF();
}

static void rxdk_dsound_DirectSoundOverrideSpeakerConfig(int a0)
{
    DirectSoundOverrideSpeakerConfig(a0);
}

static int rxdk_dsound_DirectSoundGetSampleTime(void)
{
    return DirectSoundGetSampleTime();
}

static void rxdk_dsound_DirectSoundDumpMemoryUsage(int a0)
{
    DirectSoundDumpMemoryUsage(a0);
}

static void rxdk_dsound_XAudioCreatePcmFormat(int a0, int a1, int a2, void * a3)
{
    XAudioCreatePcmFormat(a0, a1, a2, a3);
}

static void rxdk_dsound_XAudioCreateAdpcmFormat(int a0, int a1, void * a2)
{
    XAudioCreateAdpcmFormat(a0, a1, a2);
}

static int rxdk_dsound_XAudioCalculatePitch(int a0)
{
    return XAudioCalculatePitch(a0);
}

static int rxdk_dsound_XWmaDecoderCreateMediaObject(void * a0, void * a1)
{
    return XWmaDecoderCreateMediaObject(a0, a1);
}

static int rxdk_dsound_WmaCreateDecoder(void * a0, void * a1, int a2, int a3, int a4, int a5, void * a6, void * a7)
{
    return WmaCreateDecoder(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_dsound_WmaCreateInMemoryDecoder(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return WmaCreateInMemoryDecoder(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_WmaCreateDecoderEx(void * a0, void * a1, int a2, int a3, int a4, int a5, void * a6, void * a7)
{
    return WmaCreateDecoderEx(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_dsound_WmaCreateInMemoryDecoderEx(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return WmaCreateInMemoryDecoderEx(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_Ac97CreateMediaObject(int a0, void * a1, void * a2, void * a3)
{
    return Ac97CreateMediaObject(a0, a1, a2, a3);
}

static int rxdk_dsound_XFileCreateMediaObject(void * a0, int a1, int a2, int a3, int a4, void * a5)
{
    return XFileCreateMediaObject(a0, a1, a2, a3, a4, a5);
}

static int rxdk_dsound_XFileCreateMediaObjectEx(void * a0, void * a1)
{
    return XFileCreateMediaObjectEx(a0, a1);
}

static int rxdk_dsound_XFileCreateMediaObjectAsync(void * a0, int a1, void * a2)
{
    return XFileCreateMediaObjectAsync(a0, a1, a2);
}

static int rxdk_dsound_XWaveFileCreateMediaObject(void * a0, void * a1, void * a2)
{
    return XWaveFileCreateMediaObject(a0, a1, a2);
}

static int rxdk_dsound_XWaveFileCreateMediaObjectEx(void * a0, void * a1, void * a2)
{
    return XWaveFileCreateMediaObjectEx(a0, a1, a2);
}

static int rxdk_dsound_XAudioDownloadEffectsImage(void * a0, void * a1, int a2, void * a3)
{
    return XAudioDownloadEffectsImage(a0, a1, a2, a3);
}

static int rxdk_dsound_XAudioSetEffectData(int a0, void * a1, void * a2)
{
    return XAudioSetEffectData(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_QueryInterface(void * a0, int a1, void * a2)
{
    return IDirectSound_QueryInterface(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_QueryInterfaceC(void * a0, void * a1, void * a2)
{
    return IDirectSound_QueryInterfaceC(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_AddRef(void * a0)
{
    return IDirectSound_AddRef(a0);
}

static int rxdk_dsound_IDirectSound_Release(void * a0)
{
    return IDirectSound_Release(a0);
}

static int rxdk_dsound_IDirectSound_GetCaps(void * a0, void * a1)
{
    return IDirectSound_GetCaps(a0, a1);
}

static int rxdk_dsound_IDirectSound_SynchPlayback(void * a0)
{
    return IDirectSound_SynchPlayback(a0);
}

static int rxdk_dsound_IDirectSound_CreateSoundBuffer(void * a0, void * a1, void * a2, void * a3)
{
    return IDirectSound_CreateSoundBuffer(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSound_CreateSoundStream(void * a0, void * a1, void * a2, void * a3)
{
    return IDirectSound_CreateSoundStream(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSound_GetSpeakerConfig(void * a0, void * a1)
{
    return IDirectSound_GetSpeakerConfig(a0, a1);
}

static int rxdk_dsound_IDirectSound_SetCooperativeLevel(void * a0, void * a1, int a2)
{
    return IDirectSound_SetCooperativeLevel(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_Compact(void * a0)
{
    return IDirectSound_Compact(a0);
}

static int rxdk_dsound_IDirectSound_DownloadEffectsImage(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return IDirectSound_DownloadEffectsImage(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSound_GetEffectData(void * a0, int a1, int a2, void * a3, int a4)
{
    return IDirectSound_GetEffectData(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSound_SetEffectData(void * a0, int a1, int a2, void * a3, int a4, int a5)
{
    return IDirectSound_SetEffectData(a0, a1, a2, a3, a4, a5);
}

static int rxdk_dsound_IDirectSound_CommitEffectData(void * a0)
{
    return IDirectSound_CommitEffectData(a0);
}

static int rxdk_dsound_IDirectSound_EnableHeadphones(void * a0, int a1)
{
    return IDirectSound_EnableHeadphones(a0, a1);
}

static int rxdk_dsound_IDirectSound_SetMixBinHeadroom(void * a0, int a1, int a2)
{
    return IDirectSound_SetMixBinHeadroom(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_SetAllParameters(void * a0, void * a1, int a2)
{
    return IDirectSound_SetAllParameters(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_SetOrientation(void * a0, float a1, float a2, float a3, float a4, float a5, float a6, int a7)
{
    return IDirectSound_SetOrientation(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_dsound_IDirectSound_SetPosition(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSound_SetPosition(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSound_SetVelocity(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSound_SetVelocity(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSound_SetDistanceFactor(void * a0, float a1, int a2)
{
    return IDirectSound_SetDistanceFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_SetDopplerFactor(void * a0, float a1, int a2)
{
    return IDirectSound_SetDopplerFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_SetRolloffFactor(void * a0, float a1, int a2)
{
    return IDirectSound_SetRolloffFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_SetI3DL2Listener(void * a0, void * a1, int a2)
{
    return IDirectSound_SetI3DL2Listener(a0, a1, a2);
}

static int rxdk_dsound_IDirectSound_CommitDeferredSettings(void * a0)
{
    return IDirectSound_CommitDeferredSettings(a0);
}

static int rxdk_dsound_IDirectSound_GetTime(void * a0, void * a1)
{
    return IDirectSound_GetTime(a0, a1);
}

static int rxdk_dsound_IDirectSound_GetOutputLevels(void * a0, void * a1, int a2)
{
    return IDirectSound_GetOutputLevels(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_QueryInterface(void * a0, int a1, void * a2)
{
    return IDirectSoundBuffer_QueryInterface(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_QueryInterfaceC(void * a0, void * a1, void * a2)
{
    return IDirectSoundBuffer_QueryInterfaceC(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_AddRef(void * a0)
{
    return IDirectSoundBuffer_AddRef(a0);
}

static int rxdk_dsound_IDirectSoundBuffer_Release(void * a0)
{
    return IDirectSoundBuffer_Release(a0);
}

static int rxdk_dsound_IDirectSoundBuffer_SetFormat(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetFormat(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetFrequency(void * a0, int a1)
{
    return IDirectSoundBuffer_SetFrequency(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetVolume(void * a0, int a1)
{
    return IDirectSoundBuffer_SetVolume(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetPitch(void * a0, int a1)
{
    return IDirectSoundBuffer_SetPitch(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetLFO(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetLFO(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetEG(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetEG(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetFilter(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetFilter(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetHeadroom(void * a0, int a1)
{
    return IDirectSoundBuffer_SetHeadroom(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetOutputBuffer(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetOutputBuffer(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetMixBins(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetMixBins(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetMixBinVolumes(void * a0, void * a1)
{
    return IDirectSoundBuffer_SetMixBinVolumes(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetAllParameters(void * a0, void * a1, int a2)
{
    return IDirectSoundBuffer_SetAllParameters(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetConeAngles(void * a0, int a1, int a2, int a3)
{
    return IDirectSoundBuffer_SetConeAngles(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSoundBuffer_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundBuffer_SetConeOrientation(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundBuffer_SetConeOutsideVolume(void * a0, int a1, int a2)
{
    return IDirectSoundBuffer_SetConeOutsideVolume(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetMaxDistance(void * a0, float a1, int a2)
{
    return IDirectSoundBuffer_SetMaxDistance(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetMinDistance(void * a0, float a1, int a2)
{
    return IDirectSoundBuffer_SetMinDistance(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetMode(void * a0, int a1, int a2)
{
    return IDirectSoundBuffer_SetMode(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetPosition(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundBuffer_SetPosition(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundBuffer_SetVelocity(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundBuffer_SetVelocity(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundBuffer_SetDistanceFactor(void * a0, float a1, int a2)
{
    return IDirectSoundBuffer_SetDistanceFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetDopplerFactor(void * a0, float a1, int a2)
{
    return IDirectSoundBuffer_SetDopplerFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetRolloffFactor(void * a0, float a1, int a2)
{
    return IDirectSoundBuffer_SetRolloffFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetRolloffCurve(void * a0, void * a1, int a2, int a3)
{
    return IDirectSoundBuffer_SetRolloffCurve(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSoundBuffer_SetI3DL2Source(void * a0, void * a1, int a2)
{
    return IDirectSoundBuffer_SetI3DL2Source(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_Play(void * a0, int a1, int a2, int a3)
{
    return IDirectSoundBuffer_Play(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSoundBuffer_PlayEx(void * a0, long long a1, int a2)
{
    return IDirectSoundBuffer_PlayEx(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_Stop(void * a0)
{
    return IDirectSoundBuffer_Stop(a0);
}

static int rxdk_dsound_IDirectSoundBuffer_Pause(void * a0, int a1)
{
    return IDirectSoundBuffer_Pause(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_PauseEx(void * a0, long long a1, int a2)
{
    return IDirectSoundBuffer_PauseEx(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_StopEx(void * a0, long long a1, int a2)
{
    return IDirectSoundBuffer_StopEx(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetPlayRegion(void * a0, int a1, int a2)
{
    return IDirectSoundBuffer_SetPlayRegion(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetLoopRegion(void * a0, int a1, int a2)
{
    return IDirectSoundBuffer_SetLoopRegion(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_GetStatus(void * a0, void * a1)
{
    return IDirectSoundBuffer_GetStatus(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_GetCurrentPosition(void * a0, void * a1, void * a2)
{
    return IDirectSoundBuffer_GetCurrentPosition(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_SetCurrentPosition(void * a0, int a1)
{
    return IDirectSoundBuffer_SetCurrentPosition(a0, a1);
}

static int rxdk_dsound_IDirectSoundBuffer_SetBufferData(void * a0, void * a1, int a2)
{
    return IDirectSoundBuffer_SetBufferData(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_Lock(void * a0, int a1, int a2, void * a3, void * a4, void * a5, void * a6, int a7)
{
    return IDirectSoundBuffer_Lock(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_dsound_IDirectSoundBuffer_Unlock(void * a0, void * a1, int a2, void * a3, int a4)
{
    return IDirectSoundBuffer_Unlock(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundBuffer_Restore(void * a0)
{
    return IDirectSoundBuffer_Restore(a0);
}

static int rxdk_dsound_IDirectSoundBuffer_SetNotificationPositions(void * a0, int a1, void * a2)
{
    return IDirectSoundBuffer_SetNotificationPositions(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundBuffer_GetVoiceProperties(void * a0, void * a1)
{
    return IDirectSoundBuffer_GetVoiceProperties(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_QueryInterface(void * a0, int a1, void * a2)
{
    return IDirectSoundStream_QueryInterface(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_QueryInterfaceC(void * a0, void * a1, void * a2)
{
    return IDirectSoundStream_QueryInterfaceC(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetFormat(void * a0, void * a1)
{
    return IDirectSoundStream_SetFormat(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetFrequency(void * a0, int a1)
{
    return IDirectSoundStream_SetFrequency(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetVolume(void * a0, int a1)
{
    return IDirectSoundStream_SetVolume(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetPitch(void * a0, int a1)
{
    return IDirectSoundStream_SetPitch(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetLFO(void * a0, void * a1)
{
    return IDirectSoundStream_SetLFO(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetEG(void * a0, void * a1)
{
    return IDirectSoundStream_SetEG(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetFilter(void * a0, void * a1)
{
    return IDirectSoundStream_SetFilter(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetHeadroom(void * a0, int a1)
{
    return IDirectSoundStream_SetHeadroom(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetOutputBuffer(void * a0, void * a1)
{
    return IDirectSoundStream_SetOutputBuffer(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetMixBins(void * a0, void * a1)
{
    return IDirectSoundStream_SetMixBins(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetMixBinVolumes(void * a0, void * a1)
{
    return IDirectSoundStream_SetMixBinVolumes(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_SetAllParameters(void * a0, void * a1, int a2)
{
    return IDirectSoundStream_SetAllParameters(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetConeAngles(void * a0, int a1, int a2, int a3)
{
    return IDirectSoundStream_SetConeAngles(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSoundStream_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundStream_SetConeOrientation(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundStream_SetConeOutsideVolume(void * a0, int a1, int a2)
{
    return IDirectSoundStream_SetConeOutsideVolume(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetMaxDistance(void * a0, float a1, int a2)
{
    return IDirectSoundStream_SetMaxDistance(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetMinDistance(void * a0, float a1, int a2)
{
    return IDirectSoundStream_SetMinDistance(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetMode(void * a0, int a1, int a2)
{
    return IDirectSoundStream_SetMode(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetPosition(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundStream_SetPosition(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundStream_SetVelocity(void * a0, float a1, float a2, float a3, int a4)
{
    return IDirectSoundStream_SetVelocity(a0, a1, a2, a3, a4);
}

static int rxdk_dsound_IDirectSoundStream_SetDistanceFactor(void * a0, float a1, int a2)
{
    return IDirectSoundStream_SetDistanceFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetDopplerFactor(void * a0, float a1, int a2)
{
    return IDirectSoundStream_SetDopplerFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetRolloffFactor(void * a0, float a1, int a2)
{
    return IDirectSoundStream_SetRolloffFactor(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_SetRolloffCurve(void * a0, void * a1, int a2, int a3)
{
    return IDirectSoundStream_SetRolloffCurve(a0, a1, a2, a3);
}

static int rxdk_dsound_IDirectSoundStream_SetI3DL2Source(void * a0, void * a1, int a2)
{
    return IDirectSoundStream_SetI3DL2Source(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_Pause(void * a0, int a1)
{
    return IDirectSoundStream_Pause(a0, a1);
}

static int rxdk_dsound_IDirectSoundStream_PauseEx(void * a0, long long a1, int a2)
{
    return IDirectSoundStream_PauseEx(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_FlushEx(void * a0, long long a1, int a2)
{
    return IDirectSoundStream_FlushEx(a0, a1, a2);
}

static int rxdk_dsound_IDirectSoundStream_GetVoiceProperties(void * a0, void * a1)
{
    return IDirectSoundStream_GetVoiceProperties(a0, a1);
}

static void *dsound_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "dsound") && strcmp(name, "dsound.dll")) return NULL;
    return (void *)(unsigned long)1146310212u;
}

static void *dsound_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1146310212u || !name) return NULL;
    if (!strcmp(name, "rxdk_dsound_DirectSoundCreate")) return (void *)&rxdk_dsound_DirectSoundCreate;
    if (!strcmp(name, "rxdk_dsound_DirectSoundCreateBuffer")) return (void *)&rxdk_dsound_DirectSoundCreateBuffer;
    if (!strcmp(name, "rxdk_dsound_DirectSoundCreateStream")) return (void *)&rxdk_dsound_DirectSoundCreateStream;
    if (!strcmp(name, "rxdk_dsound_DirectSoundDoWork")) return (void *)&rxdk_dsound_DirectSoundDoWork;
    if (!strcmp(name, "rxdk_dsound_DirectSoundUseFullHRTF")) return (void *)&rxdk_dsound_DirectSoundUseFullHRTF;
    if (!strcmp(name, "rxdk_dsound_DirectSoundUseLightHRTF")) return (void *)&rxdk_dsound_DirectSoundUseLightHRTF;
    if (!strcmp(name, "rxdk_dsound_DirectSoundOverrideSpeakerConfig")) return (void *)&rxdk_dsound_DirectSoundOverrideSpeakerConfig;
    if (!strcmp(name, "rxdk_dsound_DirectSoundGetSampleTime")) return (void *)&rxdk_dsound_DirectSoundGetSampleTime;
    if (!strcmp(name, "rxdk_dsound_DirectSoundDumpMemoryUsage")) return (void *)&rxdk_dsound_DirectSoundDumpMemoryUsage;
    if (!strcmp(name, "rxdk_dsound_XAudioCreatePcmFormat")) return (void *)&rxdk_dsound_XAudioCreatePcmFormat;
    if (!strcmp(name, "rxdk_dsound_XAudioCreateAdpcmFormat")) return (void *)&rxdk_dsound_XAudioCreateAdpcmFormat;
    if (!strcmp(name, "rxdk_dsound_XAudioCalculatePitch")) return (void *)&rxdk_dsound_XAudioCalculatePitch;
    if (!strcmp(name, "rxdk_dsound_XWmaDecoderCreateMediaObject")) return (void *)&rxdk_dsound_XWmaDecoderCreateMediaObject;
    if (!strcmp(name, "rxdk_dsound_WmaCreateDecoder")) return (void *)&rxdk_dsound_WmaCreateDecoder;
    if (!strcmp(name, "rxdk_dsound_WmaCreateInMemoryDecoder")) return (void *)&rxdk_dsound_WmaCreateInMemoryDecoder;
    if (!strcmp(name, "rxdk_dsound_WmaCreateDecoderEx")) return (void *)&rxdk_dsound_WmaCreateDecoderEx;
    if (!strcmp(name, "rxdk_dsound_WmaCreateInMemoryDecoderEx")) return (void *)&rxdk_dsound_WmaCreateInMemoryDecoderEx;
    if (!strcmp(name, "rxdk_dsound_Ac97CreateMediaObject")) return (void *)&rxdk_dsound_Ac97CreateMediaObject;
    if (!strcmp(name, "rxdk_dsound_XFileCreateMediaObject")) return (void *)&rxdk_dsound_XFileCreateMediaObject;
    if (!strcmp(name, "rxdk_dsound_XFileCreateMediaObjectEx")) return (void *)&rxdk_dsound_XFileCreateMediaObjectEx;
    if (!strcmp(name, "rxdk_dsound_XFileCreateMediaObjectAsync")) return (void *)&rxdk_dsound_XFileCreateMediaObjectAsync;
    if (!strcmp(name, "rxdk_dsound_XWaveFileCreateMediaObject")) return (void *)&rxdk_dsound_XWaveFileCreateMediaObject;
    if (!strcmp(name, "rxdk_dsound_XWaveFileCreateMediaObjectEx")) return (void *)&rxdk_dsound_XWaveFileCreateMediaObjectEx;
    if (!strcmp(name, "rxdk_dsound_XAudioDownloadEffectsImage")) return (void *)&rxdk_dsound_XAudioDownloadEffectsImage;
    if (!strcmp(name, "rxdk_dsound_XAudioSetEffectData")) return (void *)&rxdk_dsound_XAudioSetEffectData;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_QueryInterface")) return (void *)&rxdk_dsound_IDirectSound_QueryInterface;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_QueryInterfaceC")) return (void *)&rxdk_dsound_IDirectSound_QueryInterfaceC;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_AddRef")) return (void *)&rxdk_dsound_IDirectSound_AddRef;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_Release")) return (void *)&rxdk_dsound_IDirectSound_Release;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_GetCaps")) return (void *)&rxdk_dsound_IDirectSound_GetCaps;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SynchPlayback")) return (void *)&rxdk_dsound_IDirectSound_SynchPlayback;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_CreateSoundBuffer")) return (void *)&rxdk_dsound_IDirectSound_CreateSoundBuffer;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_CreateSoundStream")) return (void *)&rxdk_dsound_IDirectSound_CreateSoundStream;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_GetSpeakerConfig")) return (void *)&rxdk_dsound_IDirectSound_GetSpeakerConfig;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetCooperativeLevel")) return (void *)&rxdk_dsound_IDirectSound_SetCooperativeLevel;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_Compact")) return (void *)&rxdk_dsound_IDirectSound_Compact;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_DownloadEffectsImage")) return (void *)&rxdk_dsound_IDirectSound_DownloadEffectsImage;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_GetEffectData")) return (void *)&rxdk_dsound_IDirectSound_GetEffectData;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetEffectData")) return (void *)&rxdk_dsound_IDirectSound_SetEffectData;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_CommitEffectData")) return (void *)&rxdk_dsound_IDirectSound_CommitEffectData;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_EnableHeadphones")) return (void *)&rxdk_dsound_IDirectSound_EnableHeadphones;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetMixBinHeadroom")) return (void *)&rxdk_dsound_IDirectSound_SetMixBinHeadroom;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetAllParameters")) return (void *)&rxdk_dsound_IDirectSound_SetAllParameters;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetOrientation")) return (void *)&rxdk_dsound_IDirectSound_SetOrientation;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetPosition")) return (void *)&rxdk_dsound_IDirectSound_SetPosition;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetVelocity")) return (void *)&rxdk_dsound_IDirectSound_SetVelocity;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetDistanceFactor")) return (void *)&rxdk_dsound_IDirectSound_SetDistanceFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetDopplerFactor")) return (void *)&rxdk_dsound_IDirectSound_SetDopplerFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetRolloffFactor")) return (void *)&rxdk_dsound_IDirectSound_SetRolloffFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_SetI3DL2Listener")) return (void *)&rxdk_dsound_IDirectSound_SetI3DL2Listener;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_CommitDeferredSettings")) return (void *)&rxdk_dsound_IDirectSound_CommitDeferredSettings;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_GetTime")) return (void *)&rxdk_dsound_IDirectSound_GetTime;
    if (!strcmp(name, "rxdk_dsound_IDirectSound_GetOutputLevels")) return (void *)&rxdk_dsound_IDirectSound_GetOutputLevels;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_QueryInterface")) return (void *)&rxdk_dsound_IDirectSoundBuffer_QueryInterface;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_QueryInterfaceC")) return (void *)&rxdk_dsound_IDirectSoundBuffer_QueryInterfaceC;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_AddRef")) return (void *)&rxdk_dsound_IDirectSoundBuffer_AddRef;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Release")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Release;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetFormat")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetFormat;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetFrequency")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetFrequency;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetVolume")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetVolume;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetPitch")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetPitch;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetLFO")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetLFO;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetEG")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetEG;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetFilter")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetFilter;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetHeadroom")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetHeadroom;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetOutputBuffer")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetOutputBuffer;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetMixBins")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetMixBins;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetMixBinVolumes")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetMixBinVolumes;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetAllParameters")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetAllParameters;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetConeAngles")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetConeAngles;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetConeOrientation")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetConeOrientation;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetConeOutsideVolume")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetConeOutsideVolume;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetMaxDistance")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetMaxDistance;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetMinDistance")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetMinDistance;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetMode")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetMode;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetPosition")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetPosition;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetVelocity")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetVelocity;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetDistanceFactor")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetDistanceFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetDopplerFactor")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetDopplerFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetRolloffFactor")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetRolloffFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetRolloffCurve")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetRolloffCurve;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetI3DL2Source")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetI3DL2Source;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Play")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Play;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_PlayEx")) return (void *)&rxdk_dsound_IDirectSoundBuffer_PlayEx;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Stop")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Stop;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Pause")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Pause;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_PauseEx")) return (void *)&rxdk_dsound_IDirectSoundBuffer_PauseEx;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_StopEx")) return (void *)&rxdk_dsound_IDirectSoundBuffer_StopEx;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetPlayRegion")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetPlayRegion;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetLoopRegion")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetLoopRegion;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_GetStatus")) return (void *)&rxdk_dsound_IDirectSoundBuffer_GetStatus;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_GetCurrentPosition")) return (void *)&rxdk_dsound_IDirectSoundBuffer_GetCurrentPosition;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetCurrentPosition")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetCurrentPosition;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetBufferData")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetBufferData;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Lock")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Lock;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Unlock")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Unlock;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_Restore")) return (void *)&rxdk_dsound_IDirectSoundBuffer_Restore;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_SetNotificationPositions")) return (void *)&rxdk_dsound_IDirectSoundBuffer_SetNotificationPositions;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundBuffer_GetVoiceProperties")) return (void *)&rxdk_dsound_IDirectSoundBuffer_GetVoiceProperties;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_QueryInterface")) return (void *)&rxdk_dsound_IDirectSoundStream_QueryInterface;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_QueryInterfaceC")) return (void *)&rxdk_dsound_IDirectSoundStream_QueryInterfaceC;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetFormat")) return (void *)&rxdk_dsound_IDirectSoundStream_SetFormat;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetFrequency")) return (void *)&rxdk_dsound_IDirectSoundStream_SetFrequency;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetVolume")) return (void *)&rxdk_dsound_IDirectSoundStream_SetVolume;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetPitch")) return (void *)&rxdk_dsound_IDirectSoundStream_SetPitch;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetLFO")) return (void *)&rxdk_dsound_IDirectSoundStream_SetLFO;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetEG")) return (void *)&rxdk_dsound_IDirectSoundStream_SetEG;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetFilter")) return (void *)&rxdk_dsound_IDirectSoundStream_SetFilter;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetHeadroom")) return (void *)&rxdk_dsound_IDirectSoundStream_SetHeadroom;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetOutputBuffer")) return (void *)&rxdk_dsound_IDirectSoundStream_SetOutputBuffer;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetMixBins")) return (void *)&rxdk_dsound_IDirectSoundStream_SetMixBins;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetMixBinVolumes")) return (void *)&rxdk_dsound_IDirectSoundStream_SetMixBinVolumes;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetAllParameters")) return (void *)&rxdk_dsound_IDirectSoundStream_SetAllParameters;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetConeAngles")) return (void *)&rxdk_dsound_IDirectSoundStream_SetConeAngles;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetConeOrientation")) return (void *)&rxdk_dsound_IDirectSoundStream_SetConeOrientation;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetConeOutsideVolume")) return (void *)&rxdk_dsound_IDirectSoundStream_SetConeOutsideVolume;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetMaxDistance")) return (void *)&rxdk_dsound_IDirectSoundStream_SetMaxDistance;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetMinDistance")) return (void *)&rxdk_dsound_IDirectSoundStream_SetMinDistance;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetMode")) return (void *)&rxdk_dsound_IDirectSoundStream_SetMode;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetPosition")) return (void *)&rxdk_dsound_IDirectSoundStream_SetPosition;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetVelocity")) return (void *)&rxdk_dsound_IDirectSoundStream_SetVelocity;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetDistanceFactor")) return (void *)&rxdk_dsound_IDirectSoundStream_SetDistanceFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetDopplerFactor")) return (void *)&rxdk_dsound_IDirectSoundStream_SetDopplerFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetRolloffFactor")) return (void *)&rxdk_dsound_IDirectSoundStream_SetRolloffFactor;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetRolloffCurve")) return (void *)&rxdk_dsound_IDirectSoundStream_SetRolloffCurve;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_SetI3DL2Source")) return (void *)&rxdk_dsound_IDirectSoundStream_SetI3DL2Source;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_Pause")) return (void *)&rxdk_dsound_IDirectSoundStream_Pause;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_PauseEx")) return (void *)&rxdk_dsound_IDirectSoundStream_PauseEx;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_FlushEx")) return (void *)&rxdk_dsound_IDirectSoundStream_FlushEx;
    if (!strcmp(name, "rxdk_dsound_IDirectSoundStream_GetVoiceProperties")) return (void *)&rxdk_dsound_IDirectSoundStream_GetVoiceProperties;
    return NULL;
}

static void *dsound_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_dsound_register(void)
{
    mono_dl_fallback_register(dsound_load, dsound_symbol, dsound_close, NULL);
}
