/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

#pragma pack(push, 4)
typedef struct { long long id; int flags; } RxdkXuid;
#pragma pack(pop)

extern int __attribute__((stdcall)) PluginSupport_AddRef(void * a0);
extern int __attribute__((stdcall)) PluginSupport_Release(void * a0);
extern int __attribute__((stdcall)) PluginSupport_GetString(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) PluginSupport_GetLayout(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) PluginSupport_GetImage(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) PluginSupport_GetScreenImage(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) PluginSupport_GetWordLength(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) LiveFriendsList_AddRef(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_Release(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_Refresh(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_IsReady(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_HasChanged(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_Count(void * a0);
extern int __attribute__((stdcall)) LiveFriendsList_GetFriendByIndex(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) LiveFriendsList_GetFriendByXUID(void * a0, RxdkXuid a1, void * a2);
extern int __attribute__((stdcall)) LiveFriendsList_Remove(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveFriendsList_Request(void * a0, RxdkXuid a1);
extern int __attribute__((stdcall)) LiveEngine_AddRef(void * a0);
extern int __attribute__((stdcall)) LiveEngine_Release(void * a0);
extern int __attribute__((stdcall)) LiveEngine_DoWork(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_SetUIPlugin(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_SetAudioPlugin(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_EnableFeature(void * a0, int a1);
extern int __attribute__((stdcall)) LiveEngine_StartFeature(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) LiveEngine_Render(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_SetInput(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) LiveEngine_GetFriendsForUser(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) LiveEngine_NotificationSetState(void * a0, int a1, int a2, long long a3, int a4, void * a5);
extern int __attribute__((stdcall)) LiveEngine_GetNotifications(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) LiveEngine_SetProperty(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) LiveEngine_GetProperty(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) LiveEngine_GetExitInfo(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_Reboot(void * a0, int a1);
extern int __attribute__((stdcall)) LiveEngine_LogOff(void * a0);
extern int __attribute__((stdcall)) LiveEngine_GetFeatureInterface(void * a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) LiveEngine_GetSelectionInfo(void * a0, void * a1);
extern int __attribute__((stdcall)) LiveEngine_EndFeature(void * a0);
extern int __attribute__((stdcall)) LiveEngine_ClearInput(void * a0);
extern int __attribute__((stdcall)) LiveEngine_UseVoiceMail(void * a0, int a1);
extern int __attribute__((stdcall)) UIXCreateLiveEngine(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) UIXCreateUIPlugin(void * a0, void * a1);
extern int __attribute__((stdcall)) UIXCreateAudioPlugin(void * a0, void * a1, void * a2);

static int rxdk_uix_PluginSupport_AddRef(void * a0)
{
    return PluginSupport_AddRef(a0);
}

static int rxdk_uix_PluginSupport_Release(void * a0)
{
    return PluginSupport_Release(a0);
}

static int rxdk_uix_PluginSupport_GetString(void * a0, int a1, void * a2)
{
    return PluginSupport_GetString(a0, a1, a2);
}

static int rxdk_uix_PluginSupport_GetLayout(void * a0, int a1, int a2, void * a3)
{
    return PluginSupport_GetLayout(a0, a1, a2, a3);
}

static int rxdk_uix_PluginSupport_GetImage(void * a0, int a1, void * a2)
{
    return PluginSupport_GetImage(a0, a1, a2);
}

static int rxdk_uix_PluginSupport_GetScreenImage(void * a0, int a1, int a2, void * a3)
{
    return PluginSupport_GetScreenImage(a0, a1, a2, a3);
}

static int rxdk_uix_PluginSupport_GetWordLength(void * a0, void * a1, void * a2)
{
    return PluginSupport_GetWordLength(a0, a1, a2);
}

static int rxdk_uix_LiveFriendsList_AddRef(void * a0)
{
    return LiveFriendsList_AddRef(a0);
}

static int rxdk_uix_LiveFriendsList_Release(void * a0)
{
    return LiveFriendsList_Release(a0);
}

static int rxdk_uix_LiveFriendsList_Refresh(void * a0)
{
    return LiveFriendsList_Refresh(a0);
}

static int rxdk_uix_LiveFriendsList_IsReady(void * a0)
{
    return LiveFriendsList_IsReady(a0);
}

static int rxdk_uix_LiveFriendsList_HasChanged(void * a0)
{
    return LiveFriendsList_HasChanged(a0);
}

static int rxdk_uix_LiveFriendsList_Count(void * a0)
{
    return LiveFriendsList_Count(a0);
}

static int rxdk_uix_LiveFriendsList_GetFriendByIndex(void * a0, int a1, void * a2)
{
    return LiveFriendsList_GetFriendByIndex(a0, a1, a2);
}

static int rxdk_uix_LiveFriendsList_GetFriendByXUID(void * a0, RxdkXuid a1, void * a2)
{
    return LiveFriendsList_GetFriendByXUID(a0, a1, a2);
}

static int rxdk_uix_LiveFriendsList_Remove(void * a0, void * a1)
{
    return LiveFriendsList_Remove(a0, a1);
}

static int rxdk_uix_LiveFriendsList_Request(void * a0, RxdkXuid a1)
{
    return LiveFriendsList_Request(a0, a1);
}

static int rxdk_uix_LiveEngine_AddRef(void * a0)
{
    return LiveEngine_AddRef(a0);
}

static int rxdk_uix_LiveEngine_Release(void * a0)
{
    return LiveEngine_Release(a0);
}

static int rxdk_uix_LiveEngine_DoWork(void * a0, void * a1)
{
    return LiveEngine_DoWork(a0, a1);
}

static int rxdk_uix_LiveEngine_SetUIPlugin(void * a0, void * a1)
{
    return LiveEngine_SetUIPlugin(a0, a1);
}

static int rxdk_uix_LiveEngine_SetAudioPlugin(void * a0, void * a1)
{
    return LiveEngine_SetAudioPlugin(a0, a1);
}

static int rxdk_uix_LiveEngine_EnableFeature(void * a0, int a1)
{
    return LiveEngine_EnableFeature(a0, a1);
}

static int rxdk_uix_LiveEngine_StartFeature(void * a0, int a1, void * a2)
{
    return LiveEngine_StartFeature(a0, a1, a2);
}

static int rxdk_uix_LiveEngine_Render(void * a0, void * a1)
{
    return LiveEngine_Render(a0, a1);
}

static int rxdk_uix_LiveEngine_SetInput(void * a0, int a1, void * a2)
{
    return LiveEngine_SetInput(a0, a1, a2);
}

static int rxdk_uix_LiveEngine_GetFriendsForUser(void * a0, int a1, void * a2)
{
    return LiveEngine_GetFriendsForUser(a0, a1, a2);
}

static int rxdk_uix_LiveEngine_NotificationSetState(void * a0, int a1, int a2, long long a3, int a4, void * a5)
{
    return LiveEngine_NotificationSetState(a0, a1, a2, a3, a4, a5);
}

static int rxdk_uix_LiveEngine_GetNotifications(void * a0, int a1, int a2, void * a3)
{
    return LiveEngine_GetNotifications(a0, a1, a2, a3);
}

static int rxdk_uix_LiveEngine_SetProperty(void * a0, int a1, int a2)
{
    return LiveEngine_SetProperty(a0, a1, a2);
}

static int rxdk_uix_LiveEngine_GetProperty(void * a0, int a1, void * a2)
{
    return LiveEngine_GetProperty(a0, a1, a2);
}

static int rxdk_uix_LiveEngine_GetExitInfo(void * a0, void * a1)
{
    return LiveEngine_GetExitInfo(a0, a1);
}

static int rxdk_uix_LiveEngine_Reboot(void * a0, int a1)
{
    return LiveEngine_Reboot(a0, a1);
}

static int rxdk_uix_LiveEngine_LogOff(void * a0)
{
    return LiveEngine_LogOff(a0);
}

static int rxdk_uix_LiveEngine_GetFeatureInterface(void * a0, int a1, void * a2, void * a3)
{
    return LiveEngine_GetFeatureInterface(a0, a1, a2, a3);
}

static int rxdk_uix_LiveEngine_GetSelectionInfo(void * a0, void * a1)
{
    return LiveEngine_GetSelectionInfo(a0, a1);
}

static int rxdk_uix_LiveEngine_EndFeature(void * a0)
{
    return LiveEngine_EndFeature(a0);
}

static int rxdk_uix_LiveEngine_ClearInput(void * a0)
{
    return LiveEngine_ClearInput(a0);
}

static int rxdk_uix_LiveEngine_UseVoiceMail(void * a0, int a1)
{
    return LiveEngine_UseVoiceMail(a0, a1);
}

static int rxdk_uix_UIXCreateLiveEngine(void * a0, int a1, void * a2)
{
    return UIXCreateLiveEngine(a0, a1, a2);
}

static int rxdk_uix_UIXCreateUIPlugin(void * a0, void * a1)
{
    return UIXCreateUIPlugin(a0, a1);
}

static int rxdk_uix_UIXCreateAudioPlugin(void * a0, void * a1, void * a2)
{
    return UIXCreateAudioPlugin(a0, a1, a2);
}

static void *uix_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "uix") && strcmp(name, "uix.dll")) return NULL;
    return (void *)(unsigned long)1430870016u;
}

static void *uix_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1430870016u || !name) return NULL;
    if (!strcmp(name, "rxdk_uix_PluginSupport_AddRef")) return (void *)&rxdk_uix_PluginSupport_AddRef;
    if (!strcmp(name, "rxdk_uix_PluginSupport_Release")) return (void *)&rxdk_uix_PluginSupport_Release;
    if (!strcmp(name, "rxdk_uix_PluginSupport_GetString")) return (void *)&rxdk_uix_PluginSupport_GetString;
    if (!strcmp(name, "rxdk_uix_PluginSupport_GetLayout")) return (void *)&rxdk_uix_PluginSupport_GetLayout;
    if (!strcmp(name, "rxdk_uix_PluginSupport_GetImage")) return (void *)&rxdk_uix_PluginSupport_GetImage;
    if (!strcmp(name, "rxdk_uix_PluginSupport_GetScreenImage")) return (void *)&rxdk_uix_PluginSupport_GetScreenImage;
    if (!strcmp(name, "rxdk_uix_PluginSupport_GetWordLength")) return (void *)&rxdk_uix_PluginSupport_GetWordLength;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_AddRef")) return (void *)&rxdk_uix_LiveFriendsList_AddRef;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_Release")) return (void *)&rxdk_uix_LiveFriendsList_Release;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_Refresh")) return (void *)&rxdk_uix_LiveFriendsList_Refresh;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_IsReady")) return (void *)&rxdk_uix_LiveFriendsList_IsReady;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_HasChanged")) return (void *)&rxdk_uix_LiveFriendsList_HasChanged;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_Count")) return (void *)&rxdk_uix_LiveFriendsList_Count;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_GetFriendByIndex")) return (void *)&rxdk_uix_LiveFriendsList_GetFriendByIndex;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_GetFriendByXUID")) return (void *)&rxdk_uix_LiveFriendsList_GetFriendByXUID;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_Remove")) return (void *)&rxdk_uix_LiveFriendsList_Remove;
    if (!strcmp(name, "rxdk_uix_LiveFriendsList_Request")) return (void *)&rxdk_uix_LiveFriendsList_Request;
    if (!strcmp(name, "rxdk_uix_LiveEngine_AddRef")) return (void *)&rxdk_uix_LiveEngine_AddRef;
    if (!strcmp(name, "rxdk_uix_LiveEngine_Release")) return (void *)&rxdk_uix_LiveEngine_Release;
    if (!strcmp(name, "rxdk_uix_LiveEngine_DoWork")) return (void *)&rxdk_uix_LiveEngine_DoWork;
    if (!strcmp(name, "rxdk_uix_LiveEngine_SetUIPlugin")) return (void *)&rxdk_uix_LiveEngine_SetUIPlugin;
    if (!strcmp(name, "rxdk_uix_LiveEngine_SetAudioPlugin")) return (void *)&rxdk_uix_LiveEngine_SetAudioPlugin;
    if (!strcmp(name, "rxdk_uix_LiveEngine_EnableFeature")) return (void *)&rxdk_uix_LiveEngine_EnableFeature;
    if (!strcmp(name, "rxdk_uix_LiveEngine_StartFeature")) return (void *)&rxdk_uix_LiveEngine_StartFeature;
    if (!strcmp(name, "rxdk_uix_LiveEngine_Render")) return (void *)&rxdk_uix_LiveEngine_Render;
    if (!strcmp(name, "rxdk_uix_LiveEngine_SetInput")) return (void *)&rxdk_uix_LiveEngine_SetInput;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetFriendsForUser")) return (void *)&rxdk_uix_LiveEngine_GetFriendsForUser;
    if (!strcmp(name, "rxdk_uix_LiveEngine_NotificationSetState")) return (void *)&rxdk_uix_LiveEngine_NotificationSetState;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetNotifications")) return (void *)&rxdk_uix_LiveEngine_GetNotifications;
    if (!strcmp(name, "rxdk_uix_LiveEngine_SetProperty")) return (void *)&rxdk_uix_LiveEngine_SetProperty;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetProperty")) return (void *)&rxdk_uix_LiveEngine_GetProperty;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetExitInfo")) return (void *)&rxdk_uix_LiveEngine_GetExitInfo;
    if (!strcmp(name, "rxdk_uix_LiveEngine_Reboot")) return (void *)&rxdk_uix_LiveEngine_Reboot;
    if (!strcmp(name, "rxdk_uix_LiveEngine_LogOff")) return (void *)&rxdk_uix_LiveEngine_LogOff;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetFeatureInterface")) return (void *)&rxdk_uix_LiveEngine_GetFeatureInterface;
    if (!strcmp(name, "rxdk_uix_LiveEngine_GetSelectionInfo")) return (void *)&rxdk_uix_LiveEngine_GetSelectionInfo;
    if (!strcmp(name, "rxdk_uix_LiveEngine_EndFeature")) return (void *)&rxdk_uix_LiveEngine_EndFeature;
    if (!strcmp(name, "rxdk_uix_LiveEngine_ClearInput")) return (void *)&rxdk_uix_LiveEngine_ClearInput;
    if (!strcmp(name, "rxdk_uix_LiveEngine_UseVoiceMail")) return (void *)&rxdk_uix_LiveEngine_UseVoiceMail;
    if (!strcmp(name, "rxdk_uix_UIXCreateLiveEngine")) return (void *)&rxdk_uix_UIXCreateLiveEngine;
    if (!strcmp(name, "rxdk_uix_UIXCreateUIPlugin")) return (void *)&rxdk_uix_UIXCreateUIPlugin;
    if (!strcmp(name, "rxdk_uix_UIXCreateAudioPlugin")) return (void *)&rxdk_uix_UIXCreateAudioPlugin;
    return NULL;
}

static void *uix_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_uix_register(void)
{
    mono_dl_fallback_register(uix_load, uix_symbol, uix_close, NULL);
}
