/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

extern int __attribute__((stdcall)) XACTEngineCreate(void * a0, void * a1);
extern void __attribute__((stdcall)) XACTEngineDoWork(void);
extern int __attribute__((stdcall)) IXACTEngine_AddRef(void * a0);
extern int __attribute__((stdcall)) IXACTEngine_Release(void * a0);
extern int __attribute__((stdcall)) IXACTEngine_DownloadEffectsImage(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) IXACTEngine_CreateSoundSource(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IXACTEngine_CreateSoundBank(void * a0, void * a1, int a2, void * a3);
extern int __attribute__((stdcall)) IXACTEngine_RegisterWaveBank(void * a0, void * a1, int a2, void * a3);
extern int __attribute__((stdcall)) IXACTEngine_RegisterStreamedWaveBank(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTEngine_UnRegisterWaveBank(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTEngine_SetMasterVolume(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IXACTEngine_GlobalPause(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IXACTEngine_SetParameterControl(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTEngine_SetI3dl2Listener(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IXACTEngine_SetListenerOrientation(void * a0, float a1, float a2, float a3, float a4, float a5, float a6, int a7);
extern int __attribute__((stdcall)) IXACTEngine_SetListenerPosition(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IXACTEngine_SetListenerVelocity(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IXACTEngine_CommitDeferredSettings(void * a0);
extern int __attribute__((stdcall)) IXACTEngine_EnableHeadphones(void * a0, int a1);
extern int __attribute__((stdcall)) IXACTEngine_RegisterNotification(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTEngine_UnRegisterNotification(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTEngine_GetNotification(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTEngine_FlushNotification(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTEngine_SetVariable(void * a0, int a1, int a2, int a3);
extern int __attribute__((stdcall)) IXACTEngine_GetVariable(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IXACTEngine_GetRealtimeData(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_AddRef(void * a0);
extern int __attribute__((stdcall)) IXACTSoundSource_Release(void * a0);
extern int __attribute__((stdcall)) IXACTSoundSource_SetPosition(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IXACTSoundSource_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IXACTSoundSource_SetI3DL2Source(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IXACTSoundSource_SetVelocity(void * a0, float a1, float a2, float a3, int a4);
extern int __attribute__((stdcall)) IXACTSoundSource_SetPitch(void * a0, int a1);
extern int __attribute__((stdcall)) IXACTSoundSource_SetFilter(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_SetMixBins(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_SetMixBinVolumes(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_SetMode(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) IXACTSoundSource_GetStatus(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_GetProperties(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTSoundSource_StopSoundCues(void * a0);
extern int __attribute__((stdcall)) IXACTSoundBank_AddRef(void * a0);
extern int __attribute__((stdcall)) IXACTSoundBank_Release(void * a0);
extern int __attribute__((stdcall)) IXACTSoundBank_GetSoundCueIndexFromFriendlyName(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTSoundBank_PrepareEx(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTSoundBank_PlayEx(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTSoundBank_Stop(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) IXACTSoundBank_CreateWmaPlayList(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) IXACTSoundBank_SelectVariation(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IXACTSoundBank_GetSoundCueProperties(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) IXACTSoundBank_PauseSoundCue(void * a0, void * a1, int a2);
extern int __attribute__((stdcall)) IXACTWmaPlayList_AddRef(void * a0);
extern int __attribute__((stdcall)) IXACTWmaPlayList_Release(void * a0);
extern int __attribute__((stdcall)) IXACTWmaPlayList_Add(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTWmaPlayList_Remove(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTWmaPlayList_SetCurrent(void * a0, void * a1);
extern int __attribute__((stdcall)) IXACTWmaPlayList_Next(void * a0);
extern int __attribute__((stdcall)) IXACTWmaPlayList_Previous(void * a0);
extern int __attribute__((stdcall)) IXACTWmaPlayList_GetCurrentSongInfo(void * a0, void * a1, void * a2, int a3, void * a4);
extern int __attribute__((stdcall)) IXACTWmaPlayList_GetCurrentSongInfoEx(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) IXACTWmaPlayList_SetPlaybackBehavior(void * a0, int a1);
extern int __attribute__((stdcall)) IXACTWmaPlayList_GetProperties(void * a0, void * a1);

static int rxdk_xact_XACTEngineCreate(void * a0, void * a1)
{
    return XACTEngineCreate(a0, a1);
}

static void rxdk_xact_XACTEngineDoWork(void)
{
    XACTEngineDoWork();
}

static int rxdk_xact_IXACTEngine_AddRef(void * a0)
{
    return IXACTEngine_AddRef(a0);
}

static int rxdk_xact_IXACTEngine_Release(void * a0)
{
    return IXACTEngine_Release(a0);
}

static int rxdk_xact_IXACTEngine_DownloadEffectsImage(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return IXACTEngine_DownloadEffectsImage(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTEngine_CreateSoundSource(void * a0, int a1, void * a2)
{
    return IXACTEngine_CreateSoundSource(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_CreateSoundBank(void * a0, void * a1, int a2, void * a3)
{
    return IXACTEngine_CreateSoundBank(a0, a1, a2, a3);
}

static int rxdk_xact_IXACTEngine_RegisterWaveBank(void * a0, void * a1, int a2, void * a3)
{
    return IXACTEngine_RegisterWaveBank(a0, a1, a2, a3);
}

static int rxdk_xact_IXACTEngine_RegisterStreamedWaveBank(void * a0, void * a1, void * a2)
{
    return IXACTEngine_RegisterStreamedWaveBank(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_UnRegisterWaveBank(void * a0, void * a1)
{
    return IXACTEngine_UnRegisterWaveBank(a0, a1);
}

static int rxdk_xact_IXACTEngine_SetMasterVolume(void * a0, int a1, int a2)
{
    return IXACTEngine_SetMasterVolume(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_GlobalPause(void * a0, int a1, int a2)
{
    return IXACTEngine_GlobalPause(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_SetParameterControl(void * a0, void * a1)
{
    return IXACTEngine_SetParameterControl(a0, a1);
}

static int rxdk_xact_IXACTEngine_SetI3dl2Listener(void * a0, void * a1, int a2)
{
    return IXACTEngine_SetI3dl2Listener(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_SetListenerOrientation(void * a0, float a1, float a2, float a3, float a4, float a5, float a6, int a7)
{
    return IXACTEngine_SetListenerOrientation(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xact_IXACTEngine_SetListenerPosition(void * a0, float a1, float a2, float a3, int a4)
{
    return IXACTEngine_SetListenerPosition(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTEngine_SetListenerVelocity(void * a0, float a1, float a2, float a3, int a4)
{
    return IXACTEngine_SetListenerVelocity(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTEngine_CommitDeferredSettings(void * a0)
{
    return IXACTEngine_CommitDeferredSettings(a0);
}

static int rxdk_xact_IXACTEngine_EnableHeadphones(void * a0, int a1)
{
    return IXACTEngine_EnableHeadphones(a0, a1);
}

static int rxdk_xact_IXACTEngine_RegisterNotification(void * a0, void * a1)
{
    return IXACTEngine_RegisterNotification(a0, a1);
}

static int rxdk_xact_IXACTEngine_UnRegisterNotification(void * a0, void * a1)
{
    return IXACTEngine_UnRegisterNotification(a0, a1);
}

static int rxdk_xact_IXACTEngine_GetNotification(void * a0, void * a1, void * a2)
{
    return IXACTEngine_GetNotification(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_FlushNotification(void * a0, void * a1)
{
    return IXACTEngine_FlushNotification(a0, a1);
}

static int rxdk_xact_IXACTEngine_SetVariable(void * a0, int a1, int a2, int a3)
{
    return IXACTEngine_SetVariable(a0, a1, a2, a3);
}

static int rxdk_xact_IXACTEngine_GetVariable(void * a0, int a1, void * a2)
{
    return IXACTEngine_GetVariable(a0, a1, a2);
}

static int rxdk_xact_IXACTEngine_GetRealtimeData(void * a0, void * a1)
{
    return IXACTEngine_GetRealtimeData(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_AddRef(void * a0)
{
    return IXACTSoundSource_AddRef(a0);
}

static int rxdk_xact_IXACTSoundSource_Release(void * a0)
{
    return IXACTSoundSource_Release(a0);
}

static int rxdk_xact_IXACTSoundSource_SetPosition(void * a0, float a1, float a2, float a3, int a4)
{
    return IXACTSoundSource_SetPosition(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTSoundSource_SetConeOrientation(void * a0, float a1, float a2, float a3, int a4)
{
    return IXACTSoundSource_SetConeOrientation(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTSoundSource_SetI3DL2Source(void * a0, void * a1, int a2)
{
    return IXACTSoundSource_SetI3DL2Source(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundSource_SetVelocity(void * a0, float a1, float a2, float a3, int a4)
{
    return IXACTSoundSource_SetVelocity(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTSoundSource_SetPitch(void * a0, int a1)
{
    return IXACTSoundSource_SetPitch(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_SetFilter(void * a0, void * a1)
{
    return IXACTSoundSource_SetFilter(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_SetMixBins(void * a0, void * a1)
{
    return IXACTSoundSource_SetMixBins(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_SetMixBinVolumes(void * a0, void * a1)
{
    return IXACTSoundSource_SetMixBinVolumes(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_SetMode(void * a0, int a1, int a2)
{
    return IXACTSoundSource_SetMode(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundSource_GetStatus(void * a0, void * a1)
{
    return IXACTSoundSource_GetStatus(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_GetProperties(void * a0, void * a1)
{
    return IXACTSoundSource_GetProperties(a0, a1);
}

static int rxdk_xact_IXACTSoundSource_StopSoundCues(void * a0)
{
    return IXACTSoundSource_StopSoundCues(a0);
}

static int rxdk_xact_IXACTSoundBank_AddRef(void * a0)
{
    return IXACTSoundBank_AddRef(a0);
}

static int rxdk_xact_IXACTSoundBank_Release(void * a0)
{
    return IXACTSoundBank_Release(a0);
}

static int rxdk_xact_IXACTSoundBank_GetSoundCueIndexFromFriendlyName(void * a0, void * a1, void * a2)
{
    return IXACTSoundBank_GetSoundCueIndexFromFriendlyName(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundBank_PrepareEx(void * a0, void * a1, void * a2)
{
    return IXACTSoundBank_PrepareEx(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundBank_PlayEx(void * a0, void * a1, void * a2)
{
    return IXACTSoundBank_PlayEx(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundBank_Stop(void * a0, int a1, int a2, void * a3)
{
    return IXACTSoundBank_Stop(a0, a1, a2, a3);
}

static int rxdk_xact_IXACTSoundBank_CreateWmaPlayList(void * a0, int a1, int a2, void * a3)
{
    return IXACTSoundBank_CreateWmaPlayList(a0, a1, a2, a3);
}

static int rxdk_xact_IXACTSoundBank_SelectVariation(void * a0, int a1, void * a2)
{
    return IXACTSoundBank_SelectVariation(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundBank_GetSoundCueProperties(void * a0, int a1, void * a2)
{
    return IXACTSoundBank_GetSoundCueProperties(a0, a1, a2);
}

static int rxdk_xact_IXACTSoundBank_PauseSoundCue(void * a0, void * a1, int a2)
{
    return IXACTSoundBank_PauseSoundCue(a0, a1, a2);
}

static int rxdk_xact_IXACTWmaPlayList_AddRef(void * a0)
{
    return IXACTWmaPlayList_AddRef(a0);
}

static int rxdk_xact_IXACTWmaPlayList_Release(void * a0)
{
    return IXACTWmaPlayList_Release(a0);
}

static int rxdk_xact_IXACTWmaPlayList_Add(void * a0, void * a1, void * a2)
{
    return IXACTWmaPlayList_Add(a0, a1, a2);
}

static int rxdk_xact_IXACTWmaPlayList_Remove(void * a0, void * a1)
{
    return IXACTWmaPlayList_Remove(a0, a1);
}

static int rxdk_xact_IXACTWmaPlayList_SetCurrent(void * a0, void * a1)
{
    return IXACTWmaPlayList_SetCurrent(a0, a1);
}

static int rxdk_xact_IXACTWmaPlayList_Next(void * a0)
{
    return IXACTWmaPlayList_Next(a0);
}

static int rxdk_xact_IXACTWmaPlayList_Previous(void * a0)
{
    return IXACTWmaPlayList_Previous(a0);
}

static int rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfo(void * a0, void * a1, void * a2, int a3, void * a4)
{
    return IXACTWmaPlayList_GetCurrentSongInfo(a0, a1, a2, a3, a4);
}

static int rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfoEx(void * a0, void * a1, void * a2)
{
    return IXACTWmaPlayList_GetCurrentSongInfoEx(a0, a1, a2);
}

static int rxdk_xact_IXACTWmaPlayList_SetPlaybackBehavior(void * a0, int a1)
{
    return IXACTWmaPlayList_SetPlaybackBehavior(a0, a1);
}

static int rxdk_xact_IXACTWmaPlayList_GetProperties(void * a0, void * a1)
{
    return IXACTWmaPlayList_GetProperties(a0, a1);
}

static void *xact_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "xact") && strcmp(name, "xact.dll")) return NULL;
    return (void *)(unsigned long)1480672084u;
}

static void *xact_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1480672084u || !name) return NULL;
    if (!strcmp(name, "rxdk_xact_XACTEngineCreate")) return (void *)&rxdk_xact_XACTEngineCreate;
    if (!strcmp(name, "rxdk_xact_XACTEngineDoWork")) return (void *)&rxdk_xact_XACTEngineDoWork;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_AddRef")) return (void *)&rxdk_xact_IXACTEngine_AddRef;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_Release")) return (void *)&rxdk_xact_IXACTEngine_Release;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_DownloadEffectsImage")) return (void *)&rxdk_xact_IXACTEngine_DownloadEffectsImage;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_CreateSoundSource")) return (void *)&rxdk_xact_IXACTEngine_CreateSoundSource;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_CreateSoundBank")) return (void *)&rxdk_xact_IXACTEngine_CreateSoundBank;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_RegisterWaveBank")) return (void *)&rxdk_xact_IXACTEngine_RegisterWaveBank;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_RegisterStreamedWaveBank")) return (void *)&rxdk_xact_IXACTEngine_RegisterStreamedWaveBank;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_UnRegisterWaveBank")) return (void *)&rxdk_xact_IXACTEngine_UnRegisterWaveBank;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetMasterVolume")) return (void *)&rxdk_xact_IXACTEngine_SetMasterVolume;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_GlobalPause")) return (void *)&rxdk_xact_IXACTEngine_GlobalPause;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetParameterControl")) return (void *)&rxdk_xact_IXACTEngine_SetParameterControl;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetI3dl2Listener")) return (void *)&rxdk_xact_IXACTEngine_SetI3dl2Listener;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetListenerOrientation")) return (void *)&rxdk_xact_IXACTEngine_SetListenerOrientation;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetListenerPosition")) return (void *)&rxdk_xact_IXACTEngine_SetListenerPosition;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetListenerVelocity")) return (void *)&rxdk_xact_IXACTEngine_SetListenerVelocity;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_CommitDeferredSettings")) return (void *)&rxdk_xact_IXACTEngine_CommitDeferredSettings;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_EnableHeadphones")) return (void *)&rxdk_xact_IXACTEngine_EnableHeadphones;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_RegisterNotification")) return (void *)&rxdk_xact_IXACTEngine_RegisterNotification;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_UnRegisterNotification")) return (void *)&rxdk_xact_IXACTEngine_UnRegisterNotification;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_GetNotification")) return (void *)&rxdk_xact_IXACTEngine_GetNotification;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_FlushNotification")) return (void *)&rxdk_xact_IXACTEngine_FlushNotification;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_SetVariable")) return (void *)&rxdk_xact_IXACTEngine_SetVariable;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_GetVariable")) return (void *)&rxdk_xact_IXACTEngine_GetVariable;
    if (!strcmp(name, "rxdk_xact_IXACTEngine_GetRealtimeData")) return (void *)&rxdk_xact_IXACTEngine_GetRealtimeData;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_AddRef")) return (void *)&rxdk_xact_IXACTSoundSource_AddRef;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_Release")) return (void *)&rxdk_xact_IXACTSoundSource_Release;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetPosition")) return (void *)&rxdk_xact_IXACTSoundSource_SetPosition;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetConeOrientation")) return (void *)&rxdk_xact_IXACTSoundSource_SetConeOrientation;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetI3DL2Source")) return (void *)&rxdk_xact_IXACTSoundSource_SetI3DL2Source;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetVelocity")) return (void *)&rxdk_xact_IXACTSoundSource_SetVelocity;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetPitch")) return (void *)&rxdk_xact_IXACTSoundSource_SetPitch;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetFilter")) return (void *)&rxdk_xact_IXACTSoundSource_SetFilter;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetMixBins")) return (void *)&rxdk_xact_IXACTSoundSource_SetMixBins;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetMixBinVolumes")) return (void *)&rxdk_xact_IXACTSoundSource_SetMixBinVolumes;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_SetMode")) return (void *)&rxdk_xact_IXACTSoundSource_SetMode;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_GetStatus")) return (void *)&rxdk_xact_IXACTSoundSource_GetStatus;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_GetProperties")) return (void *)&rxdk_xact_IXACTSoundSource_GetProperties;
    if (!strcmp(name, "rxdk_xact_IXACTSoundSource_StopSoundCues")) return (void *)&rxdk_xact_IXACTSoundSource_StopSoundCues;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_AddRef")) return (void *)&rxdk_xact_IXACTSoundBank_AddRef;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_Release")) return (void *)&rxdk_xact_IXACTSoundBank_Release;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_GetSoundCueIndexFromFriendlyName")) return (void *)&rxdk_xact_IXACTSoundBank_GetSoundCueIndexFromFriendlyName;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_PrepareEx")) return (void *)&rxdk_xact_IXACTSoundBank_PrepareEx;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_PlayEx")) return (void *)&rxdk_xact_IXACTSoundBank_PlayEx;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_Stop")) return (void *)&rxdk_xact_IXACTSoundBank_Stop;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_CreateWmaPlayList")) return (void *)&rxdk_xact_IXACTSoundBank_CreateWmaPlayList;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_SelectVariation")) return (void *)&rxdk_xact_IXACTSoundBank_SelectVariation;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_GetSoundCueProperties")) return (void *)&rxdk_xact_IXACTSoundBank_GetSoundCueProperties;
    if (!strcmp(name, "rxdk_xact_IXACTSoundBank_PauseSoundCue")) return (void *)&rxdk_xact_IXACTSoundBank_PauseSoundCue;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_AddRef")) return (void *)&rxdk_xact_IXACTWmaPlayList_AddRef;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_Release")) return (void *)&rxdk_xact_IXACTWmaPlayList_Release;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_Add")) return (void *)&rxdk_xact_IXACTWmaPlayList_Add;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_Remove")) return (void *)&rxdk_xact_IXACTWmaPlayList_Remove;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_SetCurrent")) return (void *)&rxdk_xact_IXACTWmaPlayList_SetCurrent;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_Next")) return (void *)&rxdk_xact_IXACTWmaPlayList_Next;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_Previous")) return (void *)&rxdk_xact_IXACTWmaPlayList_Previous;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfo")) return (void *)&rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfo;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfoEx")) return (void *)&rxdk_xact_IXACTWmaPlayList_GetCurrentSongInfoEx;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_SetPlaybackBehavior")) return (void *)&rxdk_xact_IXACTWmaPlayList_SetPlaybackBehavior;
    if (!strcmp(name, "rxdk_xact_IXACTWmaPlayList_GetProperties")) return (void *)&rxdk_xact_IXACTWmaPlayList_GetProperties;
    return NULL;
}

static void *xact_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_xact_register(void)
{
    mono_dl_fallback_register(xact_load, xact_symbol, xact_close, NULL);
}
