/* Generated by scripts/gen-xgmath.py. Exported XGraphics math only.
 * The short routines live in C# (Math.cs). */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

extern void * __attribute__((stdcall)) XGVec2Normalize(void *, const void *);
extern void * __attribute__((stdcall)) XGVec2Hermite(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec2CatmullRom(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec2BaryCentric(void *, const void *, const void *, const void *, float, float);
extern void * __attribute__((stdcall)) XGVec2Transform(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec2TransformCoord(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec2TransformNormal(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec3Normalize(void *, const void *);
extern void * __attribute__((stdcall)) XGVec3Hermite(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec3CatmullRom(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec3BaryCentric(void *, const void *, const void *, const void *, float, float);
extern void * __attribute__((stdcall)) XGVec3Transform(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec3TransformCoord(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec3TransformNormal(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec3Project(void *, const void *, const void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec3Unproject(void *, const void *, const void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec4Cross(void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGVec4Normalize(void *, const void *);
extern void * __attribute__((stdcall)) XGVec4Hermite(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec4CatmullRom(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGVec4BaryCentric(void *, const void *, const void *, const void *, float, float);
extern void * __attribute__((stdcall)) XGVec4Transform(void *, const void *, const void *);
extern float __attribute__((stdcall)) XGMatrixfDeterminant(const void *);
extern void * __attribute__((stdcall)) XGMatrixMultiply(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixTranspose(void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixInverse(void *, float *, const void *);
extern void * __attribute__((stdcall)) XGMatrixScaling(void *, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixTranslation(void *, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixRotationX(void *, float);
extern void * __attribute__((stdcall)) XGMatrixRotationY(void *, float);
extern void * __attribute__((stdcall)) XGMatrixRotationZ(void *, float);
extern void * __attribute__((stdcall)) XGMatrixRotationAxis(void *, const void *, float);
extern void * __attribute__((stdcall)) XGMatrixRotationQuaternion(void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixRotationYawPitchRoll(void *, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixTransformation(void *, const void *, const void *, const void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixAffineTransformation(void *, float, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixLookAtRH(void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixLookAtLH(void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveRH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveLH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveFovRH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveFovLH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveOffCenterRH(void *, float, float, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixPerspectiveOffCenterLH(void *, float, float, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixOrthoRH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixOrthoLH(void *, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixOrthoOffCenterRH(void *, float, float, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixOrthoOffCenterLH(void *, float, float, float, float, float, float);
extern void * __attribute__((stdcall)) XGMatrixShadow(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGMatrixReflect(void *, const void *);
extern void __attribute__((stdcall)) XGQuaternionToAxisAngle(const void *, void *, float *);
extern void * __attribute__((stdcall)) XGQuaternionRotationMatrix(void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionRotationAxis(void *, const void *, float);
extern void * __attribute__((stdcall)) XGQuaternionRotationYawPitchRoll(void *, float, float, float);
extern void * __attribute__((stdcall)) XGQuaternionMultiply(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionNormalize(void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionInverse(void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionLn(void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionExp(void *, const void *);
extern void * __attribute__((stdcall)) XGQuaternionSlerp(void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGQuaternionSquad(void *, const void *, const void *, const void *, const void *, float);
extern void * __attribute__((stdcall)) XGQuaternionBaryCentric(void *, const void *, const void *, const void *, float, float);
extern void * __attribute__((stdcall)) XGPlaneNormalize(void *, const void *);
extern void * __attribute__((stdcall)) XGPlaneIntersectLine(void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGPlaneFromPointNormal(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGPlaneFromPoints(void *, const void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGPlaneTransform(void *, const void *, const void *);
extern void * __attribute__((stdcall)) XGColorAdjustSaturation(void *, const void *, float);
extern void * __attribute__((stdcall)) XGColorAdjustContrast(void *, const void *, float);

static void rxdk_xm_XGVec2Normalize(void *o, const void *v)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 8); else memset(b0, 0, 8);
    XGVec2Normalize(bo, b0);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec2Hermite(void *o, const void *v1, const void *t1, const void *v2, const void *t2, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (t1) memcpy(b1, t1, 8); else memset(b1, 0, 8);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 8); else memset(b2, 0, 8);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (t2) memcpy(b3, t2, 8); else memset(b3, 0, 8);
    XGVec2Hermite(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec2CatmullRom(void *o, const void *v0, const void *v1, const void *v2, const void *v3, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v0) memcpy(b0, v0, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v1) memcpy(b1, v1, 8); else memset(b1, 0, 8);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 8); else memset(b2, 0, 8);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (v3) memcpy(b3, v3, 8); else memset(b3, 0, 8);
    XGVec2CatmullRom(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec2BaryCentric(void *o, const void *v1, const void *v2, const void *v3, float f, float g)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v2) memcpy(b1, v2, 8); else memset(b1, 0, 8);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v3) memcpy(b2, v3, 8); else memset(b2, 0, 8);
    XGVec2BaryCentric(bo, b0, b1, b2, f, g);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec2Transform(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec2Transform(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec2TransformCoord(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec2TransformCoord(bo, b0, b1);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec2TransformNormal(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 8); else memset(b0, 0, 8);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec2TransformNormal(bo, b0, b1);
    if (o) memcpy(o, bo, 8);
}

static void rxdk_xm_XGVec3Normalize(void *o, const void *v)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    XGVec3Normalize(bo, b0);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3Hermite(void *o, const void *v1, const void *t1, const void *v2, const void *t2, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (t1) memcpy(b1, t1, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 12); else memset(b2, 0, 12);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (t2) memcpy(b3, t2, 12); else memset(b3, 0, 12);
    XGVec3Hermite(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3CatmullRom(void *o, const void *v0, const void *v1, const void *v2, const void *v3, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v0) memcpy(b0, v0, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v1) memcpy(b1, v1, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 12); else memset(b2, 0, 12);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (v3) memcpy(b3, v3, 12); else memset(b3, 0, 12);
    XGVec3CatmullRom(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3BaryCentric(void *o, const void *v1, const void *v2, const void *v3, float f, float g)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v2) memcpy(b1, v2, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v3) memcpy(b2, v3, 12); else memset(b2, 0, 12);
    XGVec3BaryCentric(bo, b0, b1, b2, f, g);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3Transform(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec3Transform(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec3TransformCoord(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec3TransformCoord(bo, b0, b1);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3TransformNormal(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec3TransformNormal(bo, b0, b1);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3Project(void *o, const void *v, const void *viewport, const void *projection, const void *view, const void *world)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[24];
    if (viewport) memcpy(b1, viewport, 24); else memset(b1, 0, 24);
    __attribute__((aligned(16))) unsigned char b2[64];
    if (projection) memcpy(b2, projection, 64); else memset(b2, 0, 64);
    __attribute__((aligned(16))) unsigned char b3[64];
    if (view) memcpy(b3, view, 64); else memset(b3, 0, 64);
    __attribute__((aligned(16))) unsigned char b4[64];
    if (world) memcpy(b4, world, 64); else memset(b4, 0, 64);
    XGVec3Project(bo, b0, b1, b2, b3, b4);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec3Unproject(void *o, const void *v, const void *viewport, const void *projection, const void *view, const void *world)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[24];
    if (viewport) memcpy(b1, viewport, 24); else memset(b1, 0, 24);
    __attribute__((aligned(16))) unsigned char b2[64];
    if (projection) memcpy(b2, projection, 64); else memset(b2, 0, 64);
    __attribute__((aligned(16))) unsigned char b3[64];
    if (view) memcpy(b3, view, 64); else memset(b3, 0, 64);
    __attribute__((aligned(16))) unsigned char b4[64];
    if (world) memcpy(b4, world, 64); else memset(b4, 0, 64);
    XGVec3Unproject(bo, b0, b1, b2, b3, b4);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGVec4Cross(void *o, const void *v1, const void *v2, const void *v3)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v2) memcpy(b1, v2, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v3) memcpy(b2, v3, 16); else memset(b2, 0, 16);
    XGVec4Cross(bo, b0, b1, b2);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec4Normalize(void *o, const void *v)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 16); else memset(b0, 0, 16);
    XGVec4Normalize(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec4Hermite(void *o, const void *v1, const void *t1, const void *v2, const void *t2, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (t1) memcpy(b1, t1, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 16); else memset(b2, 0, 16);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (t2) memcpy(b3, t2, 16); else memset(b3, 0, 16);
    XGVec4Hermite(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec4CatmullRom(void *o, const void *v0, const void *v1, const void *v2, const void *v3, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v0) memcpy(b0, v0, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v1) memcpy(b1, v1, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 16); else memset(b2, 0, 16);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (v3) memcpy(b3, v3, 16); else memset(b3, 0, 16);
    XGVec4CatmullRom(bo, b0, b1, b2, b3, s);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec4BaryCentric(void *o, const void *v1, const void *v2, const void *v3, float f, float g)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v2) memcpy(b1, v2, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v3) memcpy(b2, v3, 16); else memset(b2, 0, 16);
    XGVec4BaryCentric(bo, b0, b1, b2, f, g);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGVec4Transform(void *o, const void *v, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGVec4Transform(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static float rxdk_xm_XGMatrixfDeterminant(const void *m)
{
    __attribute__((aligned(16))) unsigned char b0[64];
    if (m) memcpy(b0, m, 64); else memset(b0, 0, 64);
    return XGMatrixfDeterminant(b0);
}

static void rxdk_xm_XGMatrixMultiply(void *o, const void *m1, const void *m2)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[64];
    if (m1) memcpy(b0, m1, 64); else memset(b0, 0, 64);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m2) memcpy(b1, m2, 64); else memset(b1, 0, 64);
    XGMatrixMultiply(bo, b0, b1);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixTranspose(void *o, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[64];
    if (m) memcpy(b0, m, 64); else memset(b0, 0, 64);
    XGMatrixTranspose(bo, b0);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixInverse(void *o, float *determinant, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[64];
    if (m) memcpy(b0, m, 64); else memset(b0, 0, 64);
    XGMatrixInverse(bo, determinant, b0);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixScaling(void *o, float sx, float sy, float sz)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixScaling(bo, sx, sy, sz);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixTranslation(void *o, float x, float y, float z)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixTranslation(bo, x, y, z);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationX(void *o, float angle)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixRotationX(bo, angle);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationY(void *o, float angle)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixRotationY(bo, angle);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationZ(void *o, float angle)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixRotationZ(bo, angle);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationAxis(void *o, const void *v, float angle)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    XGMatrixRotationAxis(bo, b0, angle);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationQuaternion(void *o, const void *q)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    XGMatrixRotationQuaternion(bo, b0);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixRotationYawPitchRoll(void *o, float yaw, float pitch, float roll)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixRotationYawPitchRoll(bo, yaw, pitch, roll);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixTransformation(void *o, const void *scalingCenter, const void *scalingRotation, const void *scaling, const void *rotationCenter, const void *rotation, const void *translation)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (scalingCenter) memcpy(b0, scalingCenter, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (scalingRotation) memcpy(b1, scalingRotation, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (scaling) memcpy(b2, scaling, 12); else memset(b2, 0, 12);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (rotationCenter) memcpy(b3, rotationCenter, 12); else memset(b3, 0, 12);
    __attribute__((aligned(16))) unsigned char b4[16];
    if (rotation) memcpy(b4, rotation, 16); else memset(b4, 0, 16);
    __attribute__((aligned(16))) unsigned char b5[16];
    if (translation) memcpy(b5, translation, 12); else memset(b5, 0, 12);
    XGMatrixTransformation(bo, b0, b1, b2, b3, b4, b5);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixAffineTransformation(void *o, float scaling, const void *rotationCenter, const void *rotation, const void *translation)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (rotationCenter) memcpy(b0, rotationCenter, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (rotation) memcpy(b1, rotation, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (translation) memcpy(b2, translation, 12); else memset(b2, 0, 12);
    XGMatrixAffineTransformation(bo, scaling, b0, b1, b2);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixLookAtRH(void *o, const void *eye, const void *at, const void *up)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (eye) memcpy(b0, eye, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (at) memcpy(b1, at, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (up) memcpy(b2, up, 12); else memset(b2, 0, 12);
    XGMatrixLookAtRH(bo, b0, b1, b2);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixLookAtLH(void *o, const void *eye, const void *at, const void *up)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (eye) memcpy(b0, eye, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (at) memcpy(b1, at, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (up) memcpy(b2, up, 12); else memset(b2, 0, 12);
    XGMatrixLookAtLH(bo, b0, b1, b2);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveRH(void *o, float w, float h, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveRH(bo, w, h, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveLH(void *o, float w, float h, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveLH(bo, w, h, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveFovRH(void *o, float fovy, float aspect, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveFovRH(bo, fovy, aspect, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveFovLH(void *o, float fovy, float aspect, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveFovLH(bo, fovy, aspect, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveOffCenterRH(void *o, float l, float r, float b, float t, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveOffCenterRH(bo, l, r, b, t, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixPerspectiveOffCenterLH(void *o, float l, float r, float b, float t, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixPerspectiveOffCenterLH(bo, l, r, b, t, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixOrthoRH(void *o, float w, float h, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixOrthoRH(bo, w, h, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixOrthoLH(void *o, float w, float h, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixOrthoLH(bo, w, h, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixOrthoOffCenterRH(void *o, float l, float r, float b, float t, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixOrthoOffCenterRH(bo, l, r, b, t, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixOrthoOffCenterLH(void *o, float l, float r, float b, float t, float zn, float zf)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    XGMatrixOrthoOffCenterLH(bo, l, r, b, t, zn, zf);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixShadow(void *o, const void *light, const void *plane)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (light) memcpy(b0, light, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (plane) memcpy(b1, plane, 16); else memset(b1, 0, 16);
    XGMatrixShadow(bo, b0, b1);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGMatrixReflect(void *o, const void *plane)
{
    __attribute__((aligned(16))) unsigned char bo[64];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (plane) memcpy(b0, plane, 16); else memset(b0, 0, 16);
    XGMatrixReflect(bo, b0);
    if (o) memcpy(o, bo, 64);
}

static void rxdk_xm_XGQuaternionToAxisAngle(const void *q, void *axis, float *angle)
{
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    /* copy axis after */
    XGQuaternionToAxisAngle(b0, b1, angle);
    if (axis) memcpy(axis, b1, 12);
}

static void rxdk_xm_XGQuaternionRotationMatrix(void *o, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[64];
    if (m) memcpy(b0, m, 64); else memset(b0, 0, 64);
    XGQuaternionRotationMatrix(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionRotationAxis(void *o, const void *v, float angle)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v) memcpy(b0, v, 12); else memset(b0, 0, 12);
    XGQuaternionRotationAxis(bo, b0, angle);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionRotationYawPitchRoll(void *o, float yaw, float pitch, float roll)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    XGQuaternionRotationYawPitchRoll(bo, yaw, pitch, roll);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionMultiply(void *o, const void *q1, const void *q2)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q1) memcpy(b0, q1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (q2) memcpy(b1, q2, 16); else memset(b1, 0, 16);
    XGQuaternionMultiply(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionNormalize(void *o, const void *q)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    XGQuaternionNormalize(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionInverse(void *o, const void *q)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    XGQuaternionInverse(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionLn(void *o, const void *q)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    XGQuaternionLn(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionExp(void *o, const void *q)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q) memcpy(b0, q, 16); else memset(b0, 0, 16);
    XGQuaternionExp(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionSlerp(void *o, const void *q1, const void *q2, float t)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q1) memcpy(b0, q1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (q2) memcpy(b1, q2, 16); else memset(b1, 0, 16);
    XGQuaternionSlerp(bo, b0, b1, t);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionSquad(void *o, const void *q1, const void *q2, const void *q3, const void *q4, float t)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q1) memcpy(b0, q1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (q2) memcpy(b1, q2, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (q3) memcpy(b2, q3, 16); else memset(b2, 0, 16);
    __attribute__((aligned(16))) unsigned char b3[16];
    if (q4) memcpy(b3, q4, 16); else memset(b3, 0, 16);
    XGQuaternionSquad(bo, b0, b1, b2, b3, t);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGQuaternionBaryCentric(void *o, const void *q1, const void *q2, const void *q3, float f, float g)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (q1) memcpy(b0, q1, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (q2) memcpy(b1, q2, 16); else memset(b1, 0, 16);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (q3) memcpy(b2, q3, 16); else memset(b2, 0, 16);
    XGQuaternionBaryCentric(bo, b0, b1, b2, f, g);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGPlaneNormalize(void *o, const void *p)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (p) memcpy(b0, p, 16); else memset(b0, 0, 16);
    XGPlaneNormalize(bo, b0);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGPlaneIntersectLine(void *o, const void *p, const void *v1, const void *v2)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (p) memcpy(b0, p, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v1) memcpy(b1, v1, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v2) memcpy(b2, v2, 12); else memset(b2, 0, 12);
    XGPlaneIntersectLine(bo, b0, b1, b2);
    if (o) memcpy(o, bo, 12);
}

static void rxdk_xm_XGPlaneFromPointNormal(void *o, const void *point, const void *normal)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (point) memcpy(b0, point, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (normal) memcpy(b1, normal, 12); else memset(b1, 0, 12);
    XGPlaneFromPointNormal(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGPlaneFromPoints(void *o, const void *v1, const void *v2, const void *v3)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (v1) memcpy(b0, v1, 12); else memset(b0, 0, 12);
    __attribute__((aligned(16))) unsigned char b1[16];
    if (v2) memcpy(b1, v2, 12); else memset(b1, 0, 12);
    __attribute__((aligned(16))) unsigned char b2[16];
    if (v3) memcpy(b2, v3, 12); else memset(b2, 0, 12);
    XGPlaneFromPoints(bo, b0, b1, b2);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGPlaneTransform(void *o, const void *p, const void *m)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (p) memcpy(b0, p, 16); else memset(b0, 0, 16);
    __attribute__((aligned(16))) unsigned char b1[64];
    if (m) memcpy(b1, m, 64); else memset(b1, 0, 64);
    XGPlaneTransform(bo, b0, b1);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGColorAdjustSaturation(void *o, const void *c, float s)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (c) memcpy(b0, c, 16); else memset(b0, 0, 16);
    XGColorAdjustSaturation(bo, b0, s);
    if (o) memcpy(o, bo, 16);
}

static void rxdk_xm_XGColorAdjustContrast(void *o, const void *c, float c2)
{
    __attribute__((aligned(16))) unsigned char bo[16];
    __attribute__((aligned(16))) unsigned char b0[16];
    if (c) memcpy(b0, c, 16); else memset(b0, 0, 16);
    XGColorAdjustContrast(bo, b0, c2);
    if (o) memcpy(o, bo, 16);
}

static void *xg_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (name && (strcmp(name, "xgraphics") == 0 || strcmp(name, "xgraphics.dll") == 0))
        return (void *)(size_t)0x58474D41;
    return NULL;
}

static void *xg_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)handle; (void)err; (void)ud;
    if (!name)
        return NULL;
    if (!strcmp(name, "rxdk_xm_XGVec2Normalize")) return (void *)&rxdk_xm_XGVec2Normalize;
    if (!strcmp(name, "rxdk_xm_XGVec2Hermite")) return (void *)&rxdk_xm_XGVec2Hermite;
    if (!strcmp(name, "rxdk_xm_XGVec2CatmullRom")) return (void *)&rxdk_xm_XGVec2CatmullRom;
    if (!strcmp(name, "rxdk_xm_XGVec2BaryCentric")) return (void *)&rxdk_xm_XGVec2BaryCentric;
    if (!strcmp(name, "rxdk_xm_XGVec2Transform")) return (void *)&rxdk_xm_XGVec2Transform;
    if (!strcmp(name, "rxdk_xm_XGVec2TransformCoord")) return (void *)&rxdk_xm_XGVec2TransformCoord;
    if (!strcmp(name, "rxdk_xm_XGVec2TransformNormal")) return (void *)&rxdk_xm_XGVec2TransformNormal;
    if (!strcmp(name, "rxdk_xm_XGVec3Normalize")) return (void *)&rxdk_xm_XGVec3Normalize;
    if (!strcmp(name, "rxdk_xm_XGVec3Hermite")) return (void *)&rxdk_xm_XGVec3Hermite;
    if (!strcmp(name, "rxdk_xm_XGVec3CatmullRom")) return (void *)&rxdk_xm_XGVec3CatmullRom;
    if (!strcmp(name, "rxdk_xm_XGVec3BaryCentric")) return (void *)&rxdk_xm_XGVec3BaryCentric;
    if (!strcmp(name, "rxdk_xm_XGVec3Transform")) return (void *)&rxdk_xm_XGVec3Transform;
    if (!strcmp(name, "rxdk_xm_XGVec3TransformCoord")) return (void *)&rxdk_xm_XGVec3TransformCoord;
    if (!strcmp(name, "rxdk_xm_XGVec3TransformNormal")) return (void *)&rxdk_xm_XGVec3TransformNormal;
    if (!strcmp(name, "rxdk_xm_XGVec3Project")) return (void *)&rxdk_xm_XGVec3Project;
    if (!strcmp(name, "rxdk_xm_XGVec3Unproject")) return (void *)&rxdk_xm_XGVec3Unproject;
    if (!strcmp(name, "rxdk_xm_XGVec4Cross")) return (void *)&rxdk_xm_XGVec4Cross;
    if (!strcmp(name, "rxdk_xm_XGVec4Normalize")) return (void *)&rxdk_xm_XGVec4Normalize;
    if (!strcmp(name, "rxdk_xm_XGVec4Hermite")) return (void *)&rxdk_xm_XGVec4Hermite;
    if (!strcmp(name, "rxdk_xm_XGVec4CatmullRom")) return (void *)&rxdk_xm_XGVec4CatmullRom;
    if (!strcmp(name, "rxdk_xm_XGVec4BaryCentric")) return (void *)&rxdk_xm_XGVec4BaryCentric;
    if (!strcmp(name, "rxdk_xm_XGVec4Transform")) return (void *)&rxdk_xm_XGVec4Transform;
    if (!strcmp(name, "rxdk_xm_XGMatrixfDeterminant")) return (void *)&rxdk_xm_XGMatrixfDeterminant;
    if (!strcmp(name, "rxdk_xm_XGMatrixMultiply")) return (void *)&rxdk_xm_XGMatrixMultiply;
    if (!strcmp(name, "rxdk_xm_XGMatrixTranspose")) return (void *)&rxdk_xm_XGMatrixTranspose;
    if (!strcmp(name, "rxdk_xm_XGMatrixInverse")) return (void *)&rxdk_xm_XGMatrixInverse;
    if (!strcmp(name, "rxdk_xm_XGMatrixScaling")) return (void *)&rxdk_xm_XGMatrixScaling;
    if (!strcmp(name, "rxdk_xm_XGMatrixTranslation")) return (void *)&rxdk_xm_XGMatrixTranslation;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationX")) return (void *)&rxdk_xm_XGMatrixRotationX;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationY")) return (void *)&rxdk_xm_XGMatrixRotationY;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationZ")) return (void *)&rxdk_xm_XGMatrixRotationZ;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationAxis")) return (void *)&rxdk_xm_XGMatrixRotationAxis;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationQuaternion")) return (void *)&rxdk_xm_XGMatrixRotationQuaternion;
    if (!strcmp(name, "rxdk_xm_XGMatrixRotationYawPitchRoll")) return (void *)&rxdk_xm_XGMatrixRotationYawPitchRoll;
    if (!strcmp(name, "rxdk_xm_XGMatrixTransformation")) return (void *)&rxdk_xm_XGMatrixTransformation;
    if (!strcmp(name, "rxdk_xm_XGMatrixAffineTransformation")) return (void *)&rxdk_xm_XGMatrixAffineTransformation;
    if (!strcmp(name, "rxdk_xm_XGMatrixLookAtRH")) return (void *)&rxdk_xm_XGMatrixLookAtRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixLookAtLH")) return (void *)&rxdk_xm_XGMatrixLookAtLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveRH")) return (void *)&rxdk_xm_XGMatrixPerspectiveRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveLH")) return (void *)&rxdk_xm_XGMatrixPerspectiveLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveFovRH")) return (void *)&rxdk_xm_XGMatrixPerspectiveFovRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveFovLH")) return (void *)&rxdk_xm_XGMatrixPerspectiveFovLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveOffCenterRH")) return (void *)&rxdk_xm_XGMatrixPerspectiveOffCenterRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixPerspectiveOffCenterLH")) return (void *)&rxdk_xm_XGMatrixPerspectiveOffCenterLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixOrthoRH")) return (void *)&rxdk_xm_XGMatrixOrthoRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixOrthoLH")) return (void *)&rxdk_xm_XGMatrixOrthoLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixOrthoOffCenterRH")) return (void *)&rxdk_xm_XGMatrixOrthoOffCenterRH;
    if (!strcmp(name, "rxdk_xm_XGMatrixOrthoOffCenterLH")) return (void *)&rxdk_xm_XGMatrixOrthoOffCenterLH;
    if (!strcmp(name, "rxdk_xm_XGMatrixShadow")) return (void *)&rxdk_xm_XGMatrixShadow;
    if (!strcmp(name, "rxdk_xm_XGMatrixReflect")) return (void *)&rxdk_xm_XGMatrixReflect;
    if (!strcmp(name, "rxdk_xm_XGQuaternionToAxisAngle")) return (void *)&rxdk_xm_XGQuaternionToAxisAngle;
    if (!strcmp(name, "rxdk_xm_XGQuaternionRotationMatrix")) return (void *)&rxdk_xm_XGQuaternionRotationMatrix;
    if (!strcmp(name, "rxdk_xm_XGQuaternionRotationAxis")) return (void *)&rxdk_xm_XGQuaternionRotationAxis;
    if (!strcmp(name, "rxdk_xm_XGQuaternionRotationYawPitchRoll")) return (void *)&rxdk_xm_XGQuaternionRotationYawPitchRoll;
    if (!strcmp(name, "rxdk_xm_XGQuaternionMultiply")) return (void *)&rxdk_xm_XGQuaternionMultiply;
    if (!strcmp(name, "rxdk_xm_XGQuaternionNormalize")) return (void *)&rxdk_xm_XGQuaternionNormalize;
    if (!strcmp(name, "rxdk_xm_XGQuaternionInverse")) return (void *)&rxdk_xm_XGQuaternionInverse;
    if (!strcmp(name, "rxdk_xm_XGQuaternionLn")) return (void *)&rxdk_xm_XGQuaternionLn;
    if (!strcmp(name, "rxdk_xm_XGQuaternionExp")) return (void *)&rxdk_xm_XGQuaternionExp;
    if (!strcmp(name, "rxdk_xm_XGQuaternionSlerp")) return (void *)&rxdk_xm_XGQuaternionSlerp;
    if (!strcmp(name, "rxdk_xm_XGQuaternionSquad")) return (void *)&rxdk_xm_XGQuaternionSquad;
    if (!strcmp(name, "rxdk_xm_XGQuaternionBaryCentric")) return (void *)&rxdk_xm_XGQuaternionBaryCentric;
    if (!strcmp(name, "rxdk_xm_XGPlaneNormalize")) return (void *)&rxdk_xm_XGPlaneNormalize;
    if (!strcmp(name, "rxdk_xm_XGPlaneIntersectLine")) return (void *)&rxdk_xm_XGPlaneIntersectLine;
    if (!strcmp(name, "rxdk_xm_XGPlaneFromPointNormal")) return (void *)&rxdk_xm_XGPlaneFromPointNormal;
    if (!strcmp(name, "rxdk_xm_XGPlaneFromPoints")) return (void *)&rxdk_xm_XGPlaneFromPoints;
    if (!strcmp(name, "rxdk_xm_XGPlaneTransform")) return (void *)&rxdk_xm_XGPlaneTransform;
    if (!strcmp(name, "rxdk_xm_XGColorAdjustSaturation")) return (void *)&rxdk_xm_XGColorAdjustSaturation;
    if (!strcmp(name, "rxdk_xm_XGColorAdjustContrast")) return (void *)&rxdk_xm_XGColorAdjustContrast;
    return NULL;
}

static void *xg_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_xgmath_register(void)
{
    mono_dl_fallback_register(xg_load, xg_symbol, xg_close, NULL);
}
