/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

extern int __attribute__((stdcall)) XMVDecoder_CreateDecoderForFile(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XMVDecoder_CreateDecoderForPackets(int a0, void * a1, int a2, void * a3, void * a4, void * a5);
extern void __attribute__((stdcall)) XMVDecoder_CloseDecoder(void * a0);
extern void __attribute__((stdcall)) XMVDecoder_GetVideoDescriptor(void * a0, void * a1);
extern void __attribute__((stdcall)) XMVDecoder_GetAudioDescriptor(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XMVDecoder_EnableAudioStream(void * a0, int a1, int a2, void * a3, void * a4);
extern void __attribute__((stdcall)) XMVDecoder_DisableAudioStream(void * a0, int a1);
extern void __attribute__((stdcall)) XMVDecoder_GetAudioStream(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XMVDecoder_GetSynchronizationStream(void * a0);
extern void __attribute__((stdcall)) XMVDecoder_SetSynchronizationStream(void * a0, int a1);
extern int __attribute__((stdcall)) XMVDecoder_Reset(void * a0);
extern int __attribute__((stdcall)) XMVDecoder_Play(void * a0, int a1, void * a2);
extern void __attribute__((stdcall)) XMVDecoder_TerminateLoop(void * a0);
extern void __attribute__((stdcall)) XMVDecoder_TerminatePlayback(void * a0);
extern void __attribute__((stdcall)) XMVDecoder_TerminateImmediately(void * a0);
extern int __attribute__((stdcall)) XMVDecoder_GetNextFrame(void * a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XMVDecoder_GetTimeFromStart(void * a0);

static int rxdk_xmv_XMVDecoder_CreateDecoderForFile(int a0, void * a1, void * a2)
{
    return XMVDecoder_CreateDecoderForFile(a0, a1, a2);
}

static int rxdk_xmv_XMVDecoder_CreateDecoderForPackets(int a0, void * a1, int a2, void * a3, void * a4, void * a5)
{
    return XMVDecoder_CreateDecoderForPackets(a0, a1, a2, a3, a4, a5);
}

static void rxdk_xmv_XMVDecoder_CloseDecoder(void * a0)
{
    XMVDecoder_CloseDecoder(a0);
}

static void rxdk_xmv_XMVDecoder_GetVideoDescriptor(void * a0, void * a1)
{
    XMVDecoder_GetVideoDescriptor(a0, a1);
}

static void rxdk_xmv_XMVDecoder_GetAudioDescriptor(void * a0, int a1, void * a2)
{
    XMVDecoder_GetAudioDescriptor(a0, a1, a2);
}

static int rxdk_xmv_XMVDecoder_EnableAudioStream(void * a0, int a1, int a2, void * a3, void * a4)
{
    return XMVDecoder_EnableAudioStream(a0, a1, a2, a3, a4);
}

static void rxdk_xmv_XMVDecoder_DisableAudioStream(void * a0, int a1)
{
    XMVDecoder_DisableAudioStream(a0, a1);
}

static void rxdk_xmv_XMVDecoder_GetAudioStream(void * a0, int a1, void * a2)
{
    XMVDecoder_GetAudioStream(a0, a1, a2);
}

static int rxdk_xmv_XMVDecoder_GetSynchronizationStream(void * a0)
{
    return XMVDecoder_GetSynchronizationStream(a0);
}

static void rxdk_xmv_XMVDecoder_SetSynchronizationStream(void * a0, int a1)
{
    XMVDecoder_SetSynchronizationStream(a0, a1);
}

static int rxdk_xmv_XMVDecoder_Reset(void * a0)
{
    return XMVDecoder_Reset(a0);
}

static int rxdk_xmv_XMVDecoder_Play(void * a0, int a1, void * a2)
{
    return XMVDecoder_Play(a0, a1, a2);
}

static void rxdk_xmv_XMVDecoder_TerminateLoop(void * a0)
{
    XMVDecoder_TerminateLoop(a0);
}

static void rxdk_xmv_XMVDecoder_TerminatePlayback(void * a0)
{
    XMVDecoder_TerminatePlayback(a0);
}

static void rxdk_xmv_XMVDecoder_TerminateImmediately(void * a0)
{
    XMVDecoder_TerminateImmediately(a0);
}

static int rxdk_xmv_XMVDecoder_GetNextFrame(void * a0, void * a1, void * a2, void * a3)
{
    return XMVDecoder_GetNextFrame(a0, a1, a2, a3);
}

static int rxdk_xmv_XMVDecoder_GetTimeFromStart(void * a0)
{
    return XMVDecoder_GetTimeFromStart(a0);
}

static void *xmv_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "xmv") && strcmp(name, "xmv.dll")) return NULL;
    return (void *)(unsigned long)1481463296u;
}

static void *xmv_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1481463296u || !name) return NULL;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_CreateDecoderForFile")) return (void *)&rxdk_xmv_XMVDecoder_CreateDecoderForFile;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_CreateDecoderForPackets")) return (void *)&rxdk_xmv_XMVDecoder_CreateDecoderForPackets;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_CloseDecoder")) return (void *)&rxdk_xmv_XMVDecoder_CloseDecoder;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetVideoDescriptor")) return (void *)&rxdk_xmv_XMVDecoder_GetVideoDescriptor;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetAudioDescriptor")) return (void *)&rxdk_xmv_XMVDecoder_GetAudioDescriptor;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_EnableAudioStream")) return (void *)&rxdk_xmv_XMVDecoder_EnableAudioStream;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_DisableAudioStream")) return (void *)&rxdk_xmv_XMVDecoder_DisableAudioStream;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetAudioStream")) return (void *)&rxdk_xmv_XMVDecoder_GetAudioStream;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetSynchronizationStream")) return (void *)&rxdk_xmv_XMVDecoder_GetSynchronizationStream;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_SetSynchronizationStream")) return (void *)&rxdk_xmv_XMVDecoder_SetSynchronizationStream;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_Reset")) return (void *)&rxdk_xmv_XMVDecoder_Reset;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_Play")) return (void *)&rxdk_xmv_XMVDecoder_Play;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_TerminateLoop")) return (void *)&rxdk_xmv_XMVDecoder_TerminateLoop;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_TerminatePlayback")) return (void *)&rxdk_xmv_XMVDecoder_TerminatePlayback;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_TerminateImmediately")) return (void *)&rxdk_xmv_XMVDecoder_TerminateImmediately;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetNextFrame")) return (void *)&rxdk_xmv_XMVDecoder_GetNextFrame;
    if (!strcmp(name, "rxdk_xmv_XMVDecoder_GetTimeFromStart")) return (void *)&rxdk_xmv_XMVDecoder_GetTimeFromStart;
    return NULL;
}

static void *xmv_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_xmv_register(void)
{
    mono_dl_fallback_register(xmv_load, xmv_symbol, xmv_close, NULL);
}
