/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

#pragma pack(push, 4)
typedef struct { long long id; int flags; } RxdkXuid;
#pragma pack(pop)

extern int __attribute__((stdcall)) XOnlineStartup(void * a0);
extern int __attribute__((stdcall)) XOnlineCleanup(void);
extern int __attribute__((stdcall)) XOnlineTaskContinue(int a0);
extern int __attribute__((stdcall)) XOnlineTaskClose(int a0);
extern int __attribute__((stdcall)) XOnlineGetUsers(void * a0, void * a1);
extern int __attribute__((stdcall)) XOnlineLogon(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineLogonTaskGetResults(int a0);
extern int __attribute__((stdcall)) XOnlineChangeLogonUsers(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineChangeLogonUsersTaskGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineGetLogonUsers(void);
extern int __attribute__((stdcall)) XOnlineGetNatType(void);
extern int __attribute__((stdcall)) XOnlineGetServiceInfo(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineSilentLogon(void * a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineSaveLogonState(void * a0);
extern int __attribute__((stdcall)) XOnlineRetrieveLogonState(void * a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineTitleUpdate(int a0);
extern int __attribute__((stdcall)) XOnlineSignatureVerify(void * a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineSignatureVerifyGetResults(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineStorageUpload(void * a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStorageCreateServerPath(int a0, long long a1, long long a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineStorageUploadByServerPath(int a0, int a1, void * a2, long long a3, void * a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineStorageDownload(int a0, int a1, void * a2, void * a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineStorageUploadFromMemory(int a0, int a1, void * a2, long long a3, void * a4, int a5, int a6, void * a7, void * a8);
extern int __attribute__((stdcall)) XOnlineStorageDownloadToMemory(int a0, int a1, void * a2, void * a3, int a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineStorageDownloadToMemoryGetResults(int a0, void * a1, void * a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineStorageDeleteFile(int a0, int a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStorageEnumerate(int a0, int a1, void * a2, int a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineStorageEnumerateGetResults(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStorageGetProgress(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStorageGetInstallLocation(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStorageSetFamilyTitleID(int a0);
extern int __attribute__((stdcall)) XOnlineTitleUpdateEx(void * a0);
extern int __attribute__((stdcall)) XOnlineOfferingPurchase(int a0, long long a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineOfferingCancel(int a0, long long a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineOfferingDetails(int a0, long long a1, int a2, int a3, void * a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineOfferingDetailsGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineOfferingDetailsMaxSize(int a0);
extern int __attribute__((stdcall)) XOnlineOfferingPriceFormat(void * a0, void * a1, void * a2, int a3);
extern int __attribute__((stdcall)) XOnlineOfferingIsNewContentAvailable(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineOfferingEnumerate(int a0, void * a1, void * a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineOfferingEnumerateGetResults(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineOfferingEnumerateMaxSize(void * a0, int a1);
extern int __attribute__((stdcall)) XOnlineContentInstall(long long a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineContentInstallGetProgress(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineContentInstallGetSize(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineContentSetSecurityKey(void * a0);
extern int __attribute__((stdcall)) XOnlineMessageEnumerate(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMessageSummary(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMessageDetails(int a0, int a1, int a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMessageDetailsGetResultsSummary(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineMessageDetailsGetResultsProperty(int a0, int a1, int a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMessageDownloadAttachmentToMemory(int a0, int a1, void * a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMessageDownloadAttachmentToMemoryGetResults(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineMessageDownloadAttachmentToDirectory(int a0, int a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineMessageDownloadAttachmentGetProgress(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineMessageSetFlags(int a0, int a1, int a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMessageDelete(int a0, int a1, int a2);
extern int __attribute__((stdcall)) XOnlineMessageCreate(int a0, int a1, int a2, long long a3, int a4, int a5, void * a6);
extern int __attribute__((stdcall)) XOnlineMessageDestroy(int a0);
extern int __attribute__((stdcall)) XOnlineMessageSetProperty(int a0, int a1, int a2, void * a3, int a4);
extern int __attribute__((stdcall)) XOnlineMessageSend(int a0, int a1, int a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMessageSendGetProgress(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineMessageSendGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineMessageRevoke(int a0, int a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineMessageSetSummaryRefresh(int a0);
extern int __attribute__((stdcall)) XOnlineMessageEnableReceivingFamilyTitleIDs(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineMessageSetSendingFamilyTitleID(int a0);
extern int __attribute__((stdcall)) XOnlineMatchSessionCreate(int a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineMatchSessionUpdate(long long a0, int a1, int a2, int a3, int a4, int a5, void * a6, void * a7, void * a8);
extern int __attribute__((stdcall)) XOnlineMatchSessionGetInfo(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMatchSessionDelete(long long a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMatchSessionFindFromID(long long a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMatchSearch(int a0, int a1, int a2, void * a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineMatchSearchGetResults(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineMatchSearchParse(void * a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineMatchSearchResultsLen(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineTitleIdIsSameTitle(int a0);
extern int __attribute__((stdcall)) XOnlineTitleIdIsSamePublisher(int a0);
extern int __attribute__((stdcall)) XOnlineNotificationSetState(int a0, int a1, long long a2, int a3, void * a4);
extern int __attribute__((stdcall)) XOnlineGetNotification(int a0, int a1);
extern int __attribute__((stdcall)) XOnlineGetNotificationEx(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineFriendsStartup(void * a0, void * a1);
extern int __attribute__((stdcall)) XOnlineFriendsEnumerate(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineFriendsEnumerateFinish(int a0);
extern int __attribute__((stdcall)) XOnlineFriendsGetLatest(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineFriendsGetLatestByRange(int a0, int a1, void * a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineFriendsGetLatestByFocus(int a0, RxdkXuid a1, int a2, void * a3, void * a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineFriendsGetTitleName(int a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) XOnlineFriendsRemove(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineFriendsRequest(int a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XOnlineFriendsRequestEx(int a0, RxdkXuid a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineFriendsRequestByNameEx(int a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineFriendsGameInvite(int a0, long long a1, int a2, void * a3);
extern int __attribute__((stdcall)) XOnlineFriendsRevokeGameInvite(int a0, long long a1, int a2, void * a3);
extern int __attribute__((stdcall)) XOnlineFriendsAnswerRequest(int a0, void * a1, int a2);
extern int __attribute__((stdcall)) XOnlineFriendsAnswerGameInvite(int a0, void * a1, int a2);
extern int __attribute__((stdcall)) XOnlineFriendsJoinGame(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineFriendsGetAcceptedGameInvite(void * a0);
extern int __attribute__((stdcall)) XOnlineMutelistGet(int a0, int a1, void * a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineMutelistStartup(void * a0, void * a1);
extern int __attribute__((stdcall)) XOnlineMutelistAdd(int a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XOnlineMutelistRemove(int a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XOnlineVerifyNickname(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineFeedbackSend(int a0, RxdkXuid a1, int a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineStringVerify(int a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStringVerifyGetResults(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineStringLookupEx(int a0, int a1, void * a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineStringLookupGetResults(int a0, void * a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineQueryAdd(int a0, long long a1, int a2, int a3, void * a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineQueryAddGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineQueryUpdate(int a0, long long a1, int a2, int a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineQueryUpdateId(int a0, long long a1, int a2, int a3, long long a4, int a5, void * a6, void * a7, void * a8);
extern int __attribute__((stdcall)) XOnlineQueryGetResultsBufferSize(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineQuerySearch(int a0, int a1, int a2, int a3, int a4, void * a5, int a6, void * a7, void * a8, void * a9);
extern int __attribute__((stdcall)) XOnlineQuerySearchGetResults(int a0, void * a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineQueryFindFromIds(int a0, int a1, int a2, void * a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineQueryFindFromIdsGetResults(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineQueryRemove(int a0, long long a1, int a2, int a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineQueryRemoveId(int a0, long long a1, int a2, long long a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineQuerySelect(int a0, long long a1, int a2, long long a3, int a4, int a5, void * a6, void * a7, void * a8);
extern int __attribute__((stdcall)) XOnlineGetSession(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineGetUserSession(int a0, RxdkXuid a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineGameInviteSend(int a0, int a1, void * a2, long long a3, int a4, int a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineGameInviteAnswer(int a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineGameInviteRevoke(int a0, int a1, void * a2, long long a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineGameInviteGetLatestAccepted(void * a0);
extern int __attribute__((stdcall)) XOnlineGameJoin(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineTeamCreate(int a0, void * a1, void * a2, int a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineTeamCreateGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineTeamSetProperties(int a0, RxdkXuid a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineTeamDelete(int a0, RxdkXuid a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineTeamMemberSetProperties(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineTeamMemberRemove(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineTeamMemberRecruit(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineTeamMemberRecruitByName(int a0, RxdkXuid a1, void * a2, void * a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineTeamMemberAnswerRecruit(int a0, RxdkXuid a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineTeamEnumerate(int a0, int a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineTeamEnumerateByUserXUID(int a0, RxdkXuid a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineTeamEnumerateGetResults(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineTeamGetDetails(int a0, RxdkXuid a1, void * a2);
extern int __attribute__((stdcall)) XOnlineTeamMembersEnumerate(int a0, RxdkXuid a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineTeamMembersEnumerateGetResults(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlineTeamMemberGetDetails(int a0, RxdkXuid a1, void * a2);
extern int __attribute__((stdcall)) XOnlineTeamSetFamilyTitleID(int a0);
extern int __attribute__((stdcall)) XOnlinePresenceInit(int a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XOnlinePresenceAdd(int a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) XOnlinePresenceClear(int a0);
extern int __attribute__((stdcall)) XOnlinePresenceSubmit(int a0);
extern int __attribute__((stdcall)) XOnlinePresenceGetLatest(int a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) XOnlinePresenceGetTitleName(int a0, int a1, int a2, int a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStatWrite(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStatWriteEx(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStatWriteGetResult(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStatRead(int a0, void * a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineStatReadGetResult(int a0, int a1, void * a2, int a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStatUnitRead(void * a0, int a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStatUnitReadGetResult(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineStatLeaderEnumerate(void * a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineStatLeaderEnumerateGetResults(int a0, int a1, void * a2, int a3, void * a4, void * a5, void * a6, int a7, void * a8);
extern int __attribute__((stdcall)) XOnlineStatUnitEnumerate(RxdkXuid a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineStatUnitEnumerateGetResults(int a0, void * a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineStatReset(RxdkXuid a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineArbitrationCreateRoundID(void * a0);
extern int __attribute__((stdcall)) XOnlineArbitrationRegister(void * a0, int a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineArbitrationRegisterGetResults(int a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineArbitrationExtendRound(void * a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineArbitrationReport(void * a0, int a1, void * a2, void * a3, int a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineCompetitionCreate(int a0, int a1, long long a2, int a3, void * a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineCompetitionCreateGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineCompetitionCreateSingleElimination(int a0, int a1, long long a2, void * a3, int a4, void * a5, void * a6, void * a7);
extern int __attribute__((stdcall)) XOnlineCompetitionSearch(int a0, int a1, int a2, int a3, int a4, void * a5, int a6, void * a7, void * a8, void * a9);
extern int __attribute__((stdcall)) XOnlineCompetitionSearchGetResults(int a0, void * a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineCompetitionGetResultsBufferSize(int a0, int a1, void * a2);
extern int __attribute__((stdcall)) XOnlineCompetitionManageEntrant(int a0, int a1, int a2, long long a3, long long a4, int a5, void * a6, void * a7, void * a8);
extern int __attribute__((stdcall)) XOnlineCompetitionCheckin(int a0, int a1, long long a2, long long a3, long long a4, void * a5, void * a6);
extern int __attribute__((stdcall)) XOnlineCompetitionCancel(int a0, int a1, long long a2, long long a3, void * a4, void * a5);
extern int __attribute__((stdcall)) XOnlineCompetitionSessionRegister(void * a0, int a1, int a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineCompetitionSessionRegisterGetResults(int a0, int a1, void * a2, void * a3);
extern int __attribute__((stdcall)) XOnlineCompetitionSubmitResults(int a0, long long a1, void * a2, int a3, void * a4, int a5, void * a6, int a7, void * a8, void * a9, void * a10);
extern int __attribute__((stdcall)) XOnlineCompetitionTopology(int a0, long long a1, int a2, int a3, int a4, int a5, int a6, void * a7, void * a8, void * a9);
extern int __attribute__((stdcall)) XOnlineCompetitionTopologyGetResults(int a0, void * a1, void * a2, void * a3, void * a4);
extern int __attribute__((stdcall)) XOnlineCompetitionTopologySingleElimination(int a0, long long a1, int a2, int a3, int a4, int a5, int a6, void * a7, void * a8, void * a9);
extern int __attribute__((stdcall)) XOnlineCompetitionTopologySingleEliminationGetResults(int a0, void * a1);
extern int __attribute__((stdcall)) XOnlineThrottleSet(int a0, void * a1, int a2, int a3);
extern int __attribute__((stdcall)) XOnlineThrottleGet(int a0, void * a1, void * a2, void * a3);

static int rxdk_xonline_XOnlineStartup(void * a0)
{
    return XOnlineStartup(a0);
}

static int rxdk_xonline_XOnlineCleanup(void)
{
    return XOnlineCleanup();
}

static int rxdk_xonline_XOnlineTaskContinue(int a0)
{
    return XOnlineTaskContinue(a0);
}

static int rxdk_xonline_XOnlineTaskClose(int a0)
{
    return XOnlineTaskClose(a0);
}

static int rxdk_xonline_XOnlineGetUsers(void * a0, void * a1)
{
    return XOnlineGetUsers(a0, a1);
}

static int rxdk_xonline_XOnlineLogon(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineLogon(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineLogonTaskGetResults(int a0)
{
    return XOnlineLogonTaskGetResults(a0);
}

static int rxdk_xonline_XOnlineChangeLogonUsers(void * a0, void * a1, void * a2)
{
    return XOnlineChangeLogonUsers(a0, a1, a2);
}

static int rxdk_xonline_XOnlineChangeLogonUsersTaskGetResults(int a0, void * a1)
{
    return XOnlineChangeLogonUsersTaskGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineGetLogonUsers(void)
{
    return XOnlineGetLogonUsers();
}

static int rxdk_xonline_XOnlineGetNatType(void)
{
    return XOnlineGetNatType();
}

static int rxdk_xonline_XOnlineGetServiceInfo(int a0, void * a1)
{
    return XOnlineGetServiceInfo(a0, a1);
}

static int rxdk_xonline_XOnlineSilentLogon(void * a0, int a1, void * a2, void * a3)
{
    return XOnlineSilentLogon(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineSaveLogonState(void * a0)
{
    return XOnlineSaveLogonState(a0);
}

static int rxdk_xonline_XOnlineRetrieveLogonState(void * a0, void * a1, void * a2, void * a3)
{
    return XOnlineRetrieveLogonState(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineTitleUpdate(int a0)
{
    return XOnlineTitleUpdate(a0);
}

static int rxdk_xonline_XOnlineSignatureVerify(void * a0, int a1, void * a2, void * a3)
{
    return XOnlineSignatureVerify(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineSignatureVerifyGetResults(int a0, void * a1, void * a2)
{
    return XOnlineSignatureVerifyGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineStorageUpload(void * a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineStorageUpload(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStorageCreateServerPath(int a0, long long a1, long long a2, void * a3, void * a4, void * a5)
{
    return XOnlineStorageCreateServerPath(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineStorageUploadByServerPath(int a0, int a1, void * a2, long long a3, void * a4, int a5, void * a6, void * a7)
{
    return XOnlineStorageUploadByServerPath(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineStorageDownload(int a0, int a1, void * a2, void * a3, int a4, void * a5, void * a6)
{
    return XOnlineStorageDownload(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineStorageUploadFromMemory(int a0, int a1, void * a2, long long a3, void * a4, int a5, int a6, void * a7, void * a8)
{
    return XOnlineStorageUploadFromMemory(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineStorageDownloadToMemory(int a0, int a1, void * a2, void * a3, int a4, int a5, void * a6, void * a7)
{
    return XOnlineStorageDownloadToMemory(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineStorageDownloadToMemoryGetResults(int a0, void * a1, void * a2, void * a3, void * a4, void * a5)
{
    return XOnlineStorageDownloadToMemoryGetResults(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineStorageDeleteFile(int a0, int a1, void * a2, void * a3, void * a4)
{
    return XOnlineStorageDeleteFile(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStorageEnumerate(int a0, int a1, void * a2, int a3, int a4, void * a5, void * a6)
{
    return XOnlineStorageEnumerate(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineStorageEnumerateGetResults(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStorageEnumerateGetResults(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStorageGetProgress(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStorageGetProgress(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStorageGetInstallLocation(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStorageGetInstallLocation(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStorageSetFamilyTitleID(int a0)
{
    return XOnlineStorageSetFamilyTitleID(a0);
}

static int rxdk_xonline_XOnlineTitleUpdateEx(void * a0)
{
    return XOnlineTitleUpdateEx(a0);
}

static int rxdk_xonline_XOnlineOfferingPurchase(int a0, long long a1, void * a2, void * a3)
{
    return XOnlineOfferingPurchase(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineOfferingCancel(int a0, long long a1, void * a2, void * a3)
{
    return XOnlineOfferingCancel(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineOfferingDetails(int a0, long long a1, int a2, int a3, void * a4, int a5, void * a6, void * a7)
{
    return XOnlineOfferingDetails(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineOfferingDetailsGetResults(int a0, void * a1)
{
    return XOnlineOfferingDetailsGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineOfferingDetailsMaxSize(int a0)
{
    return XOnlineOfferingDetailsMaxSize(a0);
}

static int rxdk_xonline_XOnlineOfferingPriceFormat(void * a0, void * a1, void * a2, int a3)
{
    return XOnlineOfferingPriceFormat(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineOfferingIsNewContentAvailable(int a0, void * a1, void * a2)
{
    return XOnlineOfferingIsNewContentAvailable(a0, a1, a2);
}

static int rxdk_xonline_XOnlineOfferingEnumerate(int a0, void * a1, void * a2, int a3, void * a4, void * a5)
{
    return XOnlineOfferingEnumerate(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineOfferingEnumerateGetResults(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineOfferingEnumerateGetResults(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineOfferingEnumerateMaxSize(void * a0, int a1)
{
    return XOnlineOfferingEnumerateMaxSize(a0, a1);
}

static int rxdk_xonline_XOnlineContentInstall(long long a0, void * a1, void * a2)
{
    return XOnlineContentInstall(a0, a1, a2);
}

static int rxdk_xonline_XOnlineContentInstallGetProgress(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineContentInstallGetProgress(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineContentInstallGetSize(int a0, void * a1, void * a2)
{
    return XOnlineContentInstallGetSize(a0, a1, a2);
}

static int rxdk_xonline_XOnlineContentSetSecurityKey(void * a0)
{
    return XOnlineContentSetSecurityKey(a0);
}

static int rxdk_xonline_XOnlineMessageEnumerate(int a0, void * a1, void * a2)
{
    return XOnlineMessageEnumerate(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMessageSummary(int a0, int a1, void * a2)
{
    return XOnlineMessageSummary(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMessageDetails(int a0, int a1, int a2, int a3, void * a4, void * a5)
{
    return XOnlineMessageDetails(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMessageDetailsGetResultsSummary(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineMessageDetailsGetResultsSummary(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineMessageDetailsGetResultsProperty(int a0, int a1, int a2, void * a3, void * a4, void * a5)
{
    return XOnlineMessageDetailsGetResultsProperty(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMessageDownloadAttachmentToMemory(int a0, int a1, void * a2, int a3, void * a4, void * a5)
{
    return XOnlineMessageDownloadAttachmentToMemory(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMessageDownloadAttachmentToMemoryGetResults(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineMessageDownloadAttachmentToMemoryGetResults(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineMessageDownloadAttachmentToDirectory(int a0, int a1, void * a2, void * a3, void * a4)
{
    return XOnlineMessageDownloadAttachmentToDirectory(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineMessageDownloadAttachmentGetProgress(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineMessageDownloadAttachmentGetProgress(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineMessageSetFlags(int a0, int a1, int a2, int a3, void * a4, void * a5)
{
    return XOnlineMessageSetFlags(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMessageDelete(int a0, int a1, int a2)
{
    return XOnlineMessageDelete(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMessageCreate(int a0, int a1, int a2, long long a3, int a4, int a5, void * a6)
{
    return XOnlineMessageCreate(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineMessageDestroy(int a0)
{
    return XOnlineMessageDestroy(a0);
}

static int rxdk_xonline_XOnlineMessageSetProperty(int a0, int a1, int a2, void * a3, int a4)
{
    return XOnlineMessageSetProperty(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineMessageSend(int a0, int a1, int a2, void * a3, void * a4, void * a5)
{
    return XOnlineMessageSend(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMessageSendGetProgress(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineMessageSendGetProgress(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineMessageSendGetResults(int a0, void * a1)
{
    return XOnlineMessageSendGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineMessageRevoke(int a0, int a1, void * a2, void * a3, void * a4)
{
    return XOnlineMessageRevoke(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineMessageSetSummaryRefresh(int a0)
{
    return XOnlineMessageSetSummaryRefresh(a0);
}

static int rxdk_xonline_XOnlineMessageEnableReceivingFamilyTitleIDs(int a0, void * a1)
{
    return XOnlineMessageEnableReceivingFamilyTitleIDs(a0, a1);
}

static int rxdk_xonline_XOnlineMessageSetSendingFamilyTitleID(int a0)
{
    return XOnlineMessageSetSendingFamilyTitleID(a0);
}

static int rxdk_xonline_XOnlineMatchSessionCreate(int a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineMatchSessionCreate(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineMatchSessionUpdate(long long a0, int a1, int a2, int a3, int a4, int a5, void * a6, void * a7, void * a8)
{
    return XOnlineMatchSessionUpdate(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineMatchSessionGetInfo(int a0, void * a1, void * a2)
{
    return XOnlineMatchSessionGetInfo(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMatchSessionDelete(long long a0, void * a1, void * a2)
{
    return XOnlineMatchSessionDelete(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMatchSessionFindFromID(long long a0, void * a1, void * a2)
{
    return XOnlineMatchSessionFindFromID(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMatchSearch(int a0, int a1, int a2, void * a3, int a4, void * a5, void * a6)
{
    return XOnlineMatchSearch(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineMatchSearchGetResults(int a0, void * a1, void * a2)
{
    return XOnlineMatchSearchGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineMatchSearchParse(void * a0, int a1, void * a2, void * a3)
{
    return XOnlineMatchSearchParse(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineMatchSearchResultsLen(int a0, int a1, void * a2)
{
    return XOnlineMatchSearchResultsLen(a0, a1, a2);
}

static int rxdk_xonline_XOnlineTitleIdIsSameTitle(int a0)
{
    return XOnlineTitleIdIsSameTitle(a0);
}

static int rxdk_xonline_XOnlineTitleIdIsSamePublisher(int a0)
{
    return XOnlineTitleIdIsSamePublisher(a0);
}

static int rxdk_xonline_XOnlineNotificationSetState(int a0, int a1, long long a2, int a3, void * a4)
{
    return XOnlineNotificationSetState(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineGetNotification(int a0, int a1)
{
    return XOnlineGetNotification(a0, a1);
}

static int rxdk_xonline_XOnlineGetNotificationEx(int a0, void * a1, void * a2)
{
    return XOnlineGetNotificationEx(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFriendsStartup(void * a0, void * a1)
{
    return XOnlineFriendsStartup(a0, a1);
}

static int rxdk_xonline_XOnlineFriendsEnumerate(int a0, void * a1, void * a2)
{
    return XOnlineFriendsEnumerate(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFriendsEnumerateFinish(int a0)
{
    return XOnlineFriendsEnumerateFinish(a0);
}

static int rxdk_xonline_XOnlineFriendsGetLatest(int a0, int a1, void * a2)
{
    return XOnlineFriendsGetLatest(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFriendsGetLatestByRange(int a0, int a1, void * a2, void * a3, void * a4, void * a5)
{
    return XOnlineFriendsGetLatestByRange(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineFriendsGetLatestByFocus(int a0, RxdkXuid a1, int a2, void * a3, void * a4, void * a5, void * a6)
{
    return XOnlineFriendsGetLatestByFocus(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineFriendsGetTitleName(int a0, int a1, int a2, void * a3)
{
    return XOnlineFriendsGetTitleName(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineFriendsRemove(int a0, void * a1)
{
    return XOnlineFriendsRemove(a0, a1);
}

static int rxdk_xonline_XOnlineFriendsRequest(int a0, RxdkXuid a1)
{
    return XOnlineFriendsRequest(a0, a1);
}

static int rxdk_xonline_XOnlineFriendsRequestEx(int a0, RxdkXuid a1, int a2, void * a3, void * a4)
{
    return XOnlineFriendsRequestEx(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineFriendsRequestByNameEx(int a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineFriendsRequestByNameEx(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineFriendsGameInvite(int a0, long long a1, int a2, void * a3)
{
    return XOnlineFriendsGameInvite(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineFriendsRevokeGameInvite(int a0, long long a1, int a2, void * a3)
{
    return XOnlineFriendsRevokeGameInvite(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineFriendsAnswerRequest(int a0, void * a1, int a2)
{
    return XOnlineFriendsAnswerRequest(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFriendsAnswerGameInvite(int a0, void * a1, int a2)
{
    return XOnlineFriendsAnswerGameInvite(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFriendsJoinGame(int a0, void * a1)
{
    return XOnlineFriendsJoinGame(a0, a1);
}

static int rxdk_xonline_XOnlineFriendsGetAcceptedGameInvite(void * a0)
{
    return XOnlineFriendsGetAcceptedGameInvite(a0);
}

static int rxdk_xonline_XOnlineMutelistGet(int a0, int a1, void * a2, void * a3, void * a4, void * a5)
{
    return XOnlineMutelistGet(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineMutelistStartup(void * a0, void * a1)
{
    return XOnlineMutelistStartup(a0, a1);
}

static int rxdk_xonline_XOnlineMutelistAdd(int a0, RxdkXuid a1)
{
    return XOnlineMutelistAdd(a0, a1);
}

static int rxdk_xonline_XOnlineMutelistRemove(int a0, RxdkXuid a1)
{
    return XOnlineMutelistRemove(a0, a1);
}

static int rxdk_xonline_XOnlineVerifyNickname(void * a0, void * a1, void * a2)
{
    return XOnlineVerifyNickname(a0, a1, a2);
}

static int rxdk_xonline_XOnlineFeedbackSend(int a0, RxdkXuid a1, int a2, void * a3, void * a4, void * a5)
{
    return XOnlineFeedbackSend(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineStringVerify(int a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineStringVerify(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStringVerifyGetResults(int a0, int a1, void * a2)
{
    return XOnlineStringVerifyGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineStringLookupEx(int a0, int a1, void * a2, int a3, void * a4, void * a5)
{
    return XOnlineStringLookupEx(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineStringLookupGetResults(int a0, void * a1, void * a2, void * a3, void * a4)
{
    return XOnlineStringLookupGetResults(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineQueryAdd(int a0, long long a1, int a2, int a3, void * a4, void * a5, void * a6)
{
    return XOnlineQueryAdd(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineQueryAddGetResults(int a0, void * a1)
{
    return XOnlineQueryAddGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineQueryUpdate(int a0, long long a1, int a2, int a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineQueryUpdate(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineQueryUpdateId(int a0, long long a1, int a2, int a3, long long a4, int a5, void * a6, void * a7, void * a8)
{
    return XOnlineQueryUpdateId(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineQueryGetResultsBufferSize(int a0, int a1, void * a2)
{
    return XOnlineQueryGetResultsBufferSize(a0, a1, a2);
}

static int rxdk_xonline_XOnlineQuerySearch(int a0, int a1, int a2, int a3, int a4, void * a5, int a6, void * a7, void * a8, void * a9)
{
    return XOnlineQuerySearch(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static int rxdk_xonline_XOnlineQuerySearchGetResults(int a0, void * a1, void * a2, void * a3, void * a4)
{
    return XOnlineQuerySearchGetResults(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineQueryFindFromIds(int a0, int a1, int a2, void * a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineQueryFindFromIds(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineQueryFindFromIdsGetResults(int a0, void * a1, void * a2)
{
    return XOnlineQueryFindFromIdsGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineQueryRemove(int a0, long long a1, int a2, int a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineQueryRemove(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineQueryRemoveId(int a0, long long a1, int a2, long long a3, void * a4, void * a5)
{
    return XOnlineQueryRemoveId(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineQuerySelect(int a0, long long a1, int a2, long long a3, int a4, int a5, void * a6, void * a7, void * a8)
{
    return XOnlineQuerySelect(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineGetSession(void * a0, void * a1, void * a2)
{
    return XOnlineGetSession(a0, a1, a2);
}

static int rxdk_xonline_XOnlineGetUserSession(int a0, RxdkXuid a1, void * a2, void * a3, void * a4)
{
    return XOnlineGetUserSession(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineGameInviteSend(int a0, int a1, void * a2, long long a3, int a4, int a5, void * a6, void * a7)
{
    return XOnlineGameInviteSend(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineGameInviteAnswer(int a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineGameInviteAnswer(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineGameInviteRevoke(int a0, int a1, void * a2, long long a3, void * a4, void * a5)
{
    return XOnlineGameInviteRevoke(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineGameInviteGetLatestAccepted(void * a0)
{
    return XOnlineGameInviteGetLatestAccepted(a0);
}

static int rxdk_xonline_XOnlineGameJoin(int a0, void * a1)
{
    return XOnlineGameJoin(a0, a1);
}

static int rxdk_xonline_XOnlineTeamCreate(int a0, void * a1, void * a2, int a3, void * a4, void * a5)
{
    return XOnlineTeamCreate(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineTeamCreateGetResults(int a0, void * a1)
{
    return XOnlineTeamCreateGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineTeamSetProperties(int a0, RxdkXuid a1, void * a2, void * a3, void * a4)
{
    return XOnlineTeamSetProperties(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineTeamDelete(int a0, RxdkXuid a1, void * a2, void * a3)
{
    return XOnlineTeamDelete(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineTeamMemberSetProperties(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, void * a4, void * a5)
{
    return XOnlineTeamMemberSetProperties(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineTeamMemberRemove(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, void * a4)
{
    return XOnlineTeamMemberRemove(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineTeamMemberRecruit(int a0, RxdkXuid a1, RxdkXuid a2, void * a3, int a4, void * a5, void * a6)
{
    return XOnlineTeamMemberRecruit(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineTeamMemberRecruitByName(int a0, RxdkXuid a1, void * a2, void * a3, int a4, void * a5, void * a6)
{
    return XOnlineTeamMemberRecruitByName(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineTeamMemberAnswerRecruit(int a0, RxdkXuid a1, int a2, void * a3, void * a4)
{
    return XOnlineTeamMemberAnswerRecruit(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineTeamEnumerate(int a0, int a1, void * a2, void * a3, void * a4)
{
    return XOnlineTeamEnumerate(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineTeamEnumerateByUserXUID(int a0, RxdkXuid a1, void * a2, void * a3)
{
    return XOnlineTeamEnumerateByUserXUID(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineTeamEnumerateGetResults(int a0, void * a1, void * a2)
{
    return XOnlineTeamEnumerateGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineTeamGetDetails(int a0, RxdkXuid a1, void * a2)
{
    return XOnlineTeamGetDetails(a0, a1, a2);
}

static int rxdk_xonline_XOnlineTeamMembersEnumerate(int a0, RxdkXuid a1, int a2, void * a3, void * a4)
{
    return XOnlineTeamMembersEnumerate(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineTeamMembersEnumerateGetResults(int a0, void * a1, void * a2)
{
    return XOnlineTeamMembersEnumerateGetResults(a0, a1, a2);
}

static int rxdk_xonline_XOnlineTeamMemberGetDetails(int a0, RxdkXuid a1, void * a2)
{
    return XOnlineTeamMemberGetDetails(a0, a1, a2);
}

static int rxdk_xonline_XOnlineTeamSetFamilyTitleID(int a0)
{
    return XOnlineTeamSetFamilyTitleID(a0);
}

static int rxdk_xonline_XOnlinePresenceInit(int a0, void * a1, void * a2)
{
    return XOnlinePresenceInit(a0, a1, a2);
}

static int rxdk_xonline_XOnlinePresenceAdd(int a0, int a1, int a2, void * a3)
{
    return XOnlinePresenceAdd(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlinePresenceClear(int a0)
{
    return XOnlinePresenceClear(a0);
}

static int rxdk_xonline_XOnlinePresenceSubmit(int a0)
{
    return XOnlinePresenceSubmit(a0);
}

static int rxdk_xonline_XOnlinePresenceGetLatest(int a0, int a1, int a2, void * a3)
{
    return XOnlinePresenceGetLatest(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlinePresenceGetTitleName(int a0, int a1, int a2, int a3, void * a4)
{
    return XOnlinePresenceGetTitleName(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStatWrite(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStatWrite(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStatWriteEx(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStatWriteEx(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStatWriteGetResult(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStatWriteGetResult(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStatRead(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineStatRead(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineStatReadGetResult(int a0, int a1, void * a2, int a3, void * a4)
{
    return XOnlineStatReadGetResult(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStatUnitRead(void * a0, int a1, void * a2, void * a3, void * a4)
{
    return XOnlineStatUnitRead(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStatUnitReadGetResult(int a0, int a1, void * a2)
{
    return XOnlineStatUnitReadGetResult(a0, a1, a2);
}

static int rxdk_xonline_XOnlineStatLeaderEnumerate(void * a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineStatLeaderEnumerate(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineStatLeaderEnumerateGetResults(int a0, int a1, void * a2, int a3, void * a4, void * a5, void * a6, int a7, void * a8)
{
    return XOnlineStatLeaderEnumerateGetResults(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineStatUnitEnumerate(RxdkXuid a0, int a1, int a2, int a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineStatUnitEnumerate(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineStatUnitEnumerateGetResults(int a0, void * a1, int a2, void * a3, void * a4)
{
    return XOnlineStatUnitEnumerateGetResults(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineStatReset(RxdkXuid a0, int a1, void * a2, void * a3)
{
    return XOnlineStatReset(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineArbitrationCreateRoundID(void * a0)
{
    return XOnlineArbitrationCreateRoundID(a0);
}

static int rxdk_xonline_XOnlineArbitrationRegister(void * a0, int a1, int a2, void * a3, void * a4)
{
    return XOnlineArbitrationRegister(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineArbitrationRegisterGetResults(int a0, int a1, void * a2, void * a3)
{
    return XOnlineArbitrationRegisterGetResults(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineArbitrationExtendRound(void * a0, int a1, void * a2, void * a3)
{
    return XOnlineArbitrationExtendRound(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineArbitrationReport(void * a0, int a1, void * a2, void * a3, int a4, void * a5, void * a6)
{
    return XOnlineArbitrationReport(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineCompetitionCreate(int a0, int a1, long long a2, int a3, void * a4, void * a5, void * a6)
{
    return XOnlineCompetitionCreate(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineCompetitionCreateGetResults(int a0, void * a1)
{
    return XOnlineCompetitionCreateGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineCompetitionCreateSingleElimination(int a0, int a1, long long a2, void * a3, int a4, void * a5, void * a6, void * a7)
{
    return XOnlineCompetitionCreateSingleElimination(a0, a1, a2, a3, a4, a5, a6, a7);
}

static int rxdk_xonline_XOnlineCompetitionSearch(int a0, int a1, int a2, int a3, int a4, void * a5, int a6, void * a7, void * a8, void * a9)
{
    return XOnlineCompetitionSearch(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static int rxdk_xonline_XOnlineCompetitionSearchGetResults(int a0, void * a1, void * a2, void * a3, void * a4)
{
    return XOnlineCompetitionSearchGetResults(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineCompetitionGetResultsBufferSize(int a0, int a1, void * a2)
{
    return XOnlineCompetitionGetResultsBufferSize(a0, a1, a2);
}

static int rxdk_xonline_XOnlineCompetitionManageEntrant(int a0, int a1, int a2, long long a3, long long a4, int a5, void * a6, void * a7, void * a8)
{
    return XOnlineCompetitionManageEntrant(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static int rxdk_xonline_XOnlineCompetitionCheckin(int a0, int a1, long long a2, long long a3, long long a4, void * a5, void * a6)
{
    return XOnlineCompetitionCheckin(a0, a1, a2, a3, a4, a5, a6);
}

static int rxdk_xonline_XOnlineCompetitionCancel(int a0, int a1, long long a2, long long a3, void * a4, void * a5)
{
    return XOnlineCompetitionCancel(a0, a1, a2, a3, a4, a5);
}

static int rxdk_xonline_XOnlineCompetitionSessionRegister(void * a0, int a1, int a2, void * a3, void * a4)
{
    return XOnlineCompetitionSessionRegister(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineCompetitionSessionRegisterGetResults(int a0, int a1, void * a2, void * a3)
{
    return XOnlineCompetitionSessionRegisterGetResults(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineCompetitionSubmitResults(int a0, long long a1, void * a2, int a3, void * a4, int a5, void * a6, int a7, void * a8, void * a9, void * a10)
{
    return XOnlineCompetitionSubmitResults(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
}

static int rxdk_xonline_XOnlineCompetitionTopology(int a0, long long a1, int a2, int a3, int a4, int a5, int a6, void * a7, void * a8, void * a9)
{
    return XOnlineCompetitionTopology(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static int rxdk_xonline_XOnlineCompetitionTopologyGetResults(int a0, void * a1, void * a2, void * a3, void * a4)
{
    return XOnlineCompetitionTopologyGetResults(a0, a1, a2, a3, a4);
}

static int rxdk_xonline_XOnlineCompetitionTopologySingleElimination(int a0, long long a1, int a2, int a3, int a4, int a5, int a6, void * a7, void * a8, void * a9)
{
    return XOnlineCompetitionTopologySingleElimination(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static int rxdk_xonline_XOnlineCompetitionTopologySingleEliminationGetResults(int a0, void * a1)
{
    return XOnlineCompetitionTopologySingleEliminationGetResults(a0, a1);
}

static int rxdk_xonline_XOnlineThrottleSet(int a0, void * a1, int a2, int a3)
{
    return XOnlineThrottleSet(a0, a1, a2, a3);
}

static int rxdk_xonline_XOnlineThrottleGet(int a0, void * a1, void * a2, void * a3)
{
    return XOnlineThrottleGet(a0, a1, a2, a3);
}

static void *xonline_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "xonline") && strcmp(name, "xonline.dll")) return NULL;
    return (void *)(unsigned long)1481592396u;
}

static void *xonline_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1481592396u || !name) return NULL;
    if (!strcmp(name, "rxdk_xonline_XOnlineStartup")) return (void *)&rxdk_xonline_XOnlineStartup;
    if (!strcmp(name, "rxdk_xonline_XOnlineCleanup")) return (void *)&rxdk_xonline_XOnlineCleanup;
    if (!strcmp(name, "rxdk_xonline_XOnlineTaskContinue")) return (void *)&rxdk_xonline_XOnlineTaskContinue;
    if (!strcmp(name, "rxdk_xonline_XOnlineTaskClose")) return (void *)&rxdk_xonline_XOnlineTaskClose;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetUsers")) return (void *)&rxdk_xonline_XOnlineGetUsers;
    if (!strcmp(name, "rxdk_xonline_XOnlineLogon")) return (void *)&rxdk_xonline_XOnlineLogon;
    if (!strcmp(name, "rxdk_xonline_XOnlineLogonTaskGetResults")) return (void *)&rxdk_xonline_XOnlineLogonTaskGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineChangeLogonUsers")) return (void *)&rxdk_xonline_XOnlineChangeLogonUsers;
    if (!strcmp(name, "rxdk_xonline_XOnlineChangeLogonUsersTaskGetResults")) return (void *)&rxdk_xonline_XOnlineChangeLogonUsersTaskGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetLogonUsers")) return (void *)&rxdk_xonline_XOnlineGetLogonUsers;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetNatType")) return (void *)&rxdk_xonline_XOnlineGetNatType;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetServiceInfo")) return (void *)&rxdk_xonline_XOnlineGetServiceInfo;
    if (!strcmp(name, "rxdk_xonline_XOnlineSilentLogon")) return (void *)&rxdk_xonline_XOnlineSilentLogon;
    if (!strcmp(name, "rxdk_xonline_XOnlineSaveLogonState")) return (void *)&rxdk_xonline_XOnlineSaveLogonState;
    if (!strcmp(name, "rxdk_xonline_XOnlineRetrieveLogonState")) return (void *)&rxdk_xonline_XOnlineRetrieveLogonState;
    if (!strcmp(name, "rxdk_xonline_XOnlineTitleUpdate")) return (void *)&rxdk_xonline_XOnlineTitleUpdate;
    if (!strcmp(name, "rxdk_xonline_XOnlineSignatureVerify")) return (void *)&rxdk_xonline_XOnlineSignatureVerify;
    if (!strcmp(name, "rxdk_xonline_XOnlineSignatureVerifyGetResults")) return (void *)&rxdk_xonline_XOnlineSignatureVerifyGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageUpload")) return (void *)&rxdk_xonline_XOnlineStorageUpload;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageCreateServerPath")) return (void *)&rxdk_xonline_XOnlineStorageCreateServerPath;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageUploadByServerPath")) return (void *)&rxdk_xonline_XOnlineStorageUploadByServerPath;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageDownload")) return (void *)&rxdk_xonline_XOnlineStorageDownload;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageUploadFromMemory")) return (void *)&rxdk_xonline_XOnlineStorageUploadFromMemory;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageDownloadToMemory")) return (void *)&rxdk_xonline_XOnlineStorageDownloadToMemory;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageDownloadToMemoryGetResults")) return (void *)&rxdk_xonline_XOnlineStorageDownloadToMemoryGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageDeleteFile")) return (void *)&rxdk_xonline_XOnlineStorageDeleteFile;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageEnumerate")) return (void *)&rxdk_xonline_XOnlineStorageEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineStorageEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageGetProgress")) return (void *)&rxdk_xonline_XOnlineStorageGetProgress;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageGetInstallLocation")) return (void *)&rxdk_xonline_XOnlineStorageGetInstallLocation;
    if (!strcmp(name, "rxdk_xonline_XOnlineStorageSetFamilyTitleID")) return (void *)&rxdk_xonline_XOnlineStorageSetFamilyTitleID;
    if (!strcmp(name, "rxdk_xonline_XOnlineTitleUpdateEx")) return (void *)&rxdk_xonline_XOnlineTitleUpdateEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingPurchase")) return (void *)&rxdk_xonline_XOnlineOfferingPurchase;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingCancel")) return (void *)&rxdk_xonline_XOnlineOfferingCancel;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingDetails")) return (void *)&rxdk_xonline_XOnlineOfferingDetails;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingDetailsGetResults")) return (void *)&rxdk_xonline_XOnlineOfferingDetailsGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingDetailsMaxSize")) return (void *)&rxdk_xonline_XOnlineOfferingDetailsMaxSize;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingPriceFormat")) return (void *)&rxdk_xonline_XOnlineOfferingPriceFormat;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingIsNewContentAvailable")) return (void *)&rxdk_xonline_XOnlineOfferingIsNewContentAvailable;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingEnumerate")) return (void *)&rxdk_xonline_XOnlineOfferingEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineOfferingEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineOfferingEnumerateMaxSize")) return (void *)&rxdk_xonline_XOnlineOfferingEnumerateMaxSize;
    if (!strcmp(name, "rxdk_xonline_XOnlineContentInstall")) return (void *)&rxdk_xonline_XOnlineContentInstall;
    if (!strcmp(name, "rxdk_xonline_XOnlineContentInstallGetProgress")) return (void *)&rxdk_xonline_XOnlineContentInstallGetProgress;
    if (!strcmp(name, "rxdk_xonline_XOnlineContentInstallGetSize")) return (void *)&rxdk_xonline_XOnlineContentInstallGetSize;
    if (!strcmp(name, "rxdk_xonline_XOnlineContentSetSecurityKey")) return (void *)&rxdk_xonline_XOnlineContentSetSecurityKey;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageEnumerate")) return (void *)&rxdk_xonline_XOnlineMessageEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSummary")) return (void *)&rxdk_xonline_XOnlineMessageSummary;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDetails")) return (void *)&rxdk_xonline_XOnlineMessageDetails;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDetailsGetResultsSummary")) return (void *)&rxdk_xonline_XOnlineMessageDetailsGetResultsSummary;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDetailsGetResultsProperty")) return (void *)&rxdk_xonline_XOnlineMessageDetailsGetResultsProperty;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDownloadAttachmentToMemory")) return (void *)&rxdk_xonline_XOnlineMessageDownloadAttachmentToMemory;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDownloadAttachmentToMemoryGetResults")) return (void *)&rxdk_xonline_XOnlineMessageDownloadAttachmentToMemoryGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDownloadAttachmentToDirectory")) return (void *)&rxdk_xonline_XOnlineMessageDownloadAttachmentToDirectory;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDownloadAttachmentGetProgress")) return (void *)&rxdk_xonline_XOnlineMessageDownloadAttachmentGetProgress;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSetFlags")) return (void *)&rxdk_xonline_XOnlineMessageSetFlags;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDelete")) return (void *)&rxdk_xonline_XOnlineMessageDelete;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageCreate")) return (void *)&rxdk_xonline_XOnlineMessageCreate;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageDestroy")) return (void *)&rxdk_xonline_XOnlineMessageDestroy;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSetProperty")) return (void *)&rxdk_xonline_XOnlineMessageSetProperty;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSend")) return (void *)&rxdk_xonline_XOnlineMessageSend;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSendGetProgress")) return (void *)&rxdk_xonline_XOnlineMessageSendGetProgress;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSendGetResults")) return (void *)&rxdk_xonline_XOnlineMessageSendGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageRevoke")) return (void *)&rxdk_xonline_XOnlineMessageRevoke;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSetSummaryRefresh")) return (void *)&rxdk_xonline_XOnlineMessageSetSummaryRefresh;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageEnableReceivingFamilyTitleIDs")) return (void *)&rxdk_xonline_XOnlineMessageEnableReceivingFamilyTitleIDs;
    if (!strcmp(name, "rxdk_xonline_XOnlineMessageSetSendingFamilyTitleID")) return (void *)&rxdk_xonline_XOnlineMessageSetSendingFamilyTitleID;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSessionCreate")) return (void *)&rxdk_xonline_XOnlineMatchSessionCreate;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSessionUpdate")) return (void *)&rxdk_xonline_XOnlineMatchSessionUpdate;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSessionGetInfo")) return (void *)&rxdk_xonline_XOnlineMatchSessionGetInfo;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSessionDelete")) return (void *)&rxdk_xonline_XOnlineMatchSessionDelete;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSessionFindFromID")) return (void *)&rxdk_xonline_XOnlineMatchSessionFindFromID;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSearch")) return (void *)&rxdk_xonline_XOnlineMatchSearch;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSearchGetResults")) return (void *)&rxdk_xonline_XOnlineMatchSearchGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSearchParse")) return (void *)&rxdk_xonline_XOnlineMatchSearchParse;
    if (!strcmp(name, "rxdk_xonline_XOnlineMatchSearchResultsLen")) return (void *)&rxdk_xonline_XOnlineMatchSearchResultsLen;
    if (!strcmp(name, "rxdk_xonline_XOnlineTitleIdIsSameTitle")) return (void *)&rxdk_xonline_XOnlineTitleIdIsSameTitle;
    if (!strcmp(name, "rxdk_xonline_XOnlineTitleIdIsSamePublisher")) return (void *)&rxdk_xonline_XOnlineTitleIdIsSamePublisher;
    if (!strcmp(name, "rxdk_xonline_XOnlineNotificationSetState")) return (void *)&rxdk_xonline_XOnlineNotificationSetState;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetNotification")) return (void *)&rxdk_xonline_XOnlineGetNotification;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetNotificationEx")) return (void *)&rxdk_xonline_XOnlineGetNotificationEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsStartup")) return (void *)&rxdk_xonline_XOnlineFriendsStartup;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsEnumerate")) return (void *)&rxdk_xonline_XOnlineFriendsEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsEnumerateFinish")) return (void *)&rxdk_xonline_XOnlineFriendsEnumerateFinish;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGetLatest")) return (void *)&rxdk_xonline_XOnlineFriendsGetLatest;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGetLatestByRange")) return (void *)&rxdk_xonline_XOnlineFriendsGetLatestByRange;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGetLatestByFocus")) return (void *)&rxdk_xonline_XOnlineFriendsGetLatestByFocus;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGetTitleName")) return (void *)&rxdk_xonline_XOnlineFriendsGetTitleName;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsRemove")) return (void *)&rxdk_xonline_XOnlineFriendsRemove;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsRequest")) return (void *)&rxdk_xonline_XOnlineFriendsRequest;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsRequestEx")) return (void *)&rxdk_xonline_XOnlineFriendsRequestEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsRequestByNameEx")) return (void *)&rxdk_xonline_XOnlineFriendsRequestByNameEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGameInvite")) return (void *)&rxdk_xonline_XOnlineFriendsGameInvite;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsRevokeGameInvite")) return (void *)&rxdk_xonline_XOnlineFriendsRevokeGameInvite;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsAnswerRequest")) return (void *)&rxdk_xonline_XOnlineFriendsAnswerRequest;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsAnswerGameInvite")) return (void *)&rxdk_xonline_XOnlineFriendsAnswerGameInvite;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsJoinGame")) return (void *)&rxdk_xonline_XOnlineFriendsJoinGame;
    if (!strcmp(name, "rxdk_xonline_XOnlineFriendsGetAcceptedGameInvite")) return (void *)&rxdk_xonline_XOnlineFriendsGetAcceptedGameInvite;
    if (!strcmp(name, "rxdk_xonline_XOnlineMutelistGet")) return (void *)&rxdk_xonline_XOnlineMutelistGet;
    if (!strcmp(name, "rxdk_xonline_XOnlineMutelistStartup")) return (void *)&rxdk_xonline_XOnlineMutelistStartup;
    if (!strcmp(name, "rxdk_xonline_XOnlineMutelistAdd")) return (void *)&rxdk_xonline_XOnlineMutelistAdd;
    if (!strcmp(name, "rxdk_xonline_XOnlineMutelistRemove")) return (void *)&rxdk_xonline_XOnlineMutelistRemove;
    if (!strcmp(name, "rxdk_xonline_XOnlineVerifyNickname")) return (void *)&rxdk_xonline_XOnlineVerifyNickname;
    if (!strcmp(name, "rxdk_xonline_XOnlineFeedbackSend")) return (void *)&rxdk_xonline_XOnlineFeedbackSend;
    if (!strcmp(name, "rxdk_xonline_XOnlineStringVerify")) return (void *)&rxdk_xonline_XOnlineStringVerify;
    if (!strcmp(name, "rxdk_xonline_XOnlineStringVerifyGetResults")) return (void *)&rxdk_xonline_XOnlineStringVerifyGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStringLookupEx")) return (void *)&rxdk_xonline_XOnlineStringLookupEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineStringLookupGetResults")) return (void *)&rxdk_xonline_XOnlineStringLookupGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryAdd")) return (void *)&rxdk_xonline_XOnlineQueryAdd;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryAddGetResults")) return (void *)&rxdk_xonline_XOnlineQueryAddGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryUpdate")) return (void *)&rxdk_xonline_XOnlineQueryUpdate;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryUpdateId")) return (void *)&rxdk_xonline_XOnlineQueryUpdateId;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryGetResultsBufferSize")) return (void *)&rxdk_xonline_XOnlineQueryGetResultsBufferSize;
    if (!strcmp(name, "rxdk_xonline_XOnlineQuerySearch")) return (void *)&rxdk_xonline_XOnlineQuerySearch;
    if (!strcmp(name, "rxdk_xonline_XOnlineQuerySearchGetResults")) return (void *)&rxdk_xonline_XOnlineQuerySearchGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryFindFromIds")) return (void *)&rxdk_xonline_XOnlineQueryFindFromIds;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryFindFromIdsGetResults")) return (void *)&rxdk_xonline_XOnlineQueryFindFromIdsGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryRemove")) return (void *)&rxdk_xonline_XOnlineQueryRemove;
    if (!strcmp(name, "rxdk_xonline_XOnlineQueryRemoveId")) return (void *)&rxdk_xonline_XOnlineQueryRemoveId;
    if (!strcmp(name, "rxdk_xonline_XOnlineQuerySelect")) return (void *)&rxdk_xonline_XOnlineQuerySelect;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetSession")) return (void *)&rxdk_xonline_XOnlineGetSession;
    if (!strcmp(name, "rxdk_xonline_XOnlineGetUserSession")) return (void *)&rxdk_xonline_XOnlineGetUserSession;
    if (!strcmp(name, "rxdk_xonline_XOnlineGameInviteSend")) return (void *)&rxdk_xonline_XOnlineGameInviteSend;
    if (!strcmp(name, "rxdk_xonline_XOnlineGameInviteAnswer")) return (void *)&rxdk_xonline_XOnlineGameInviteAnswer;
    if (!strcmp(name, "rxdk_xonline_XOnlineGameInviteRevoke")) return (void *)&rxdk_xonline_XOnlineGameInviteRevoke;
    if (!strcmp(name, "rxdk_xonline_XOnlineGameInviteGetLatestAccepted")) return (void *)&rxdk_xonline_XOnlineGameInviteGetLatestAccepted;
    if (!strcmp(name, "rxdk_xonline_XOnlineGameJoin")) return (void *)&rxdk_xonline_XOnlineGameJoin;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamCreate")) return (void *)&rxdk_xonline_XOnlineTeamCreate;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamCreateGetResults")) return (void *)&rxdk_xonline_XOnlineTeamCreateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamSetProperties")) return (void *)&rxdk_xonline_XOnlineTeamSetProperties;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamDelete")) return (void *)&rxdk_xonline_XOnlineTeamDelete;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberSetProperties")) return (void *)&rxdk_xonline_XOnlineTeamMemberSetProperties;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberRemove")) return (void *)&rxdk_xonline_XOnlineTeamMemberRemove;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberRecruit")) return (void *)&rxdk_xonline_XOnlineTeamMemberRecruit;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberRecruitByName")) return (void *)&rxdk_xonline_XOnlineTeamMemberRecruitByName;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberAnswerRecruit")) return (void *)&rxdk_xonline_XOnlineTeamMemberAnswerRecruit;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamEnumerate")) return (void *)&rxdk_xonline_XOnlineTeamEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamEnumerateByUserXUID")) return (void *)&rxdk_xonline_XOnlineTeamEnumerateByUserXUID;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineTeamEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamGetDetails")) return (void *)&rxdk_xonline_XOnlineTeamGetDetails;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMembersEnumerate")) return (void *)&rxdk_xonline_XOnlineTeamMembersEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMembersEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineTeamMembersEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamMemberGetDetails")) return (void *)&rxdk_xonline_XOnlineTeamMemberGetDetails;
    if (!strcmp(name, "rxdk_xonline_XOnlineTeamSetFamilyTitleID")) return (void *)&rxdk_xonline_XOnlineTeamSetFamilyTitleID;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceInit")) return (void *)&rxdk_xonline_XOnlinePresenceInit;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceAdd")) return (void *)&rxdk_xonline_XOnlinePresenceAdd;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceClear")) return (void *)&rxdk_xonline_XOnlinePresenceClear;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceSubmit")) return (void *)&rxdk_xonline_XOnlinePresenceSubmit;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceGetLatest")) return (void *)&rxdk_xonline_XOnlinePresenceGetLatest;
    if (!strcmp(name, "rxdk_xonline_XOnlinePresenceGetTitleName")) return (void *)&rxdk_xonline_XOnlinePresenceGetTitleName;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatWrite")) return (void *)&rxdk_xonline_XOnlineStatWrite;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatWriteEx")) return (void *)&rxdk_xonline_XOnlineStatWriteEx;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatWriteGetResult")) return (void *)&rxdk_xonline_XOnlineStatWriteGetResult;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatRead")) return (void *)&rxdk_xonline_XOnlineStatRead;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatReadGetResult")) return (void *)&rxdk_xonline_XOnlineStatReadGetResult;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatUnitRead")) return (void *)&rxdk_xonline_XOnlineStatUnitRead;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatUnitReadGetResult")) return (void *)&rxdk_xonline_XOnlineStatUnitReadGetResult;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatLeaderEnumerate")) return (void *)&rxdk_xonline_XOnlineStatLeaderEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatLeaderEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineStatLeaderEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatUnitEnumerate")) return (void *)&rxdk_xonline_XOnlineStatUnitEnumerate;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatUnitEnumerateGetResults")) return (void *)&rxdk_xonline_XOnlineStatUnitEnumerateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineStatReset")) return (void *)&rxdk_xonline_XOnlineStatReset;
    if (!strcmp(name, "rxdk_xonline_XOnlineArbitrationCreateRoundID")) return (void *)&rxdk_xonline_XOnlineArbitrationCreateRoundID;
    if (!strcmp(name, "rxdk_xonline_XOnlineArbitrationRegister")) return (void *)&rxdk_xonline_XOnlineArbitrationRegister;
    if (!strcmp(name, "rxdk_xonline_XOnlineArbitrationRegisterGetResults")) return (void *)&rxdk_xonline_XOnlineArbitrationRegisterGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineArbitrationExtendRound")) return (void *)&rxdk_xonline_XOnlineArbitrationExtendRound;
    if (!strcmp(name, "rxdk_xonline_XOnlineArbitrationReport")) return (void *)&rxdk_xonline_XOnlineArbitrationReport;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionCreate")) return (void *)&rxdk_xonline_XOnlineCompetitionCreate;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionCreateGetResults")) return (void *)&rxdk_xonline_XOnlineCompetitionCreateGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionCreateSingleElimination")) return (void *)&rxdk_xonline_XOnlineCompetitionCreateSingleElimination;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionSearch")) return (void *)&rxdk_xonline_XOnlineCompetitionSearch;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionSearchGetResults")) return (void *)&rxdk_xonline_XOnlineCompetitionSearchGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionGetResultsBufferSize")) return (void *)&rxdk_xonline_XOnlineCompetitionGetResultsBufferSize;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionManageEntrant")) return (void *)&rxdk_xonline_XOnlineCompetitionManageEntrant;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionCheckin")) return (void *)&rxdk_xonline_XOnlineCompetitionCheckin;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionCancel")) return (void *)&rxdk_xonline_XOnlineCompetitionCancel;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionSessionRegister")) return (void *)&rxdk_xonline_XOnlineCompetitionSessionRegister;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionSessionRegisterGetResults")) return (void *)&rxdk_xonline_XOnlineCompetitionSessionRegisterGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionSubmitResults")) return (void *)&rxdk_xonline_XOnlineCompetitionSubmitResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionTopology")) return (void *)&rxdk_xonline_XOnlineCompetitionTopology;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionTopologyGetResults")) return (void *)&rxdk_xonline_XOnlineCompetitionTopologyGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionTopologySingleElimination")) return (void *)&rxdk_xonline_XOnlineCompetitionTopologySingleElimination;
    if (!strcmp(name, "rxdk_xonline_XOnlineCompetitionTopologySingleEliminationGetResults")) return (void *)&rxdk_xonline_XOnlineCompetitionTopologySingleEliminationGetResults;
    if (!strcmp(name, "rxdk_xonline_XOnlineThrottleSet")) return (void *)&rxdk_xonline_XOnlineThrottleSet;
    if (!strcmp(name, "rxdk_xonline_XOnlineThrottleGet")) return (void *)&rxdk_xonline_XOnlineThrottleGet;
    return NULL;
}

static void *xonline_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_xonline_register(void)
{
    mono_dl_fallback_register(xonline_load, xonline_symbol, xonline_close, NULL);
}
