/* Generated by scripts/gen-sdklibs.py. Do not edit. */
#include <string.h>

typedef void *(*RxdkDlLoad)(const char *name, int flags, char **err, void *ud);
typedef void *(*RxdkDlSymbol)(void *handle, const char *name, char **err, void *ud);
typedef void *(*RxdkDlClose)(void *handle, void *ud);
extern void *mono_dl_fallback_register(RxdkDlLoad, RxdkDlSymbol, RxdkDlClose, void *);

#pragma pack(push, 4)
typedef struct { long long id; int flags; } RxdkXuid;
#pragma pack(pop)

extern int __attribute__((stdcall)) XVoiceQueueCreateMediaObject(void * a0, void * a1);
extern int __attribute__((stdcall)) XVoiceSynchronizedQueueCreateMediaObject(void * a0, void * a1);
extern int __attribute__((stdcall)) XVoiceCreateOneToOneEncoder(void * a0);
extern int __attribute__((stdcall)) XVoiceCreateTwoToTwoEncoder(void * a0);
extern int __attribute__((stdcall)) XVoiceCreateFourToFourFullEncoder(void * a0);
extern int __attribute__((stdcall)) XVoiceCreateFourToFourRoundRobinEncoder(void * a0);
extern int __attribute__((stdcall)) XVoiceCreateOneToOneDecoder(void * a0);
extern int __attribute__((stdcall)) XVoiceCreateFourToFourFullDecoder(int a0, void * a1);
extern int __attribute__((stdcall)) XVoiceCreateFourToOneMixingDecoder(int a0, void * a1);
extern int __attribute__((stdcall)) XVoiceCreateTwoToOneMixingDecoder(int a0, void * a1);
extern int __attribute__((stdcall)) XVoiceGetEncodedPacketEnergy(void * a0, void * a1);
extern int __attribute__((stdcall)) XHVEngine_AddRef(void * a0);
extern int __attribute__((stdcall)) XHVEngine_Release(void * a0);
extern int __attribute__((stdcall)) XHVEngine_EnableProcessingMode(void * a0, int a1);
extern int __attribute__((stdcall)) XHVEngine_SetCallbackInterface(void * a0, void * a1);
extern int __attribute__((stdcall)) XHVEngine_GetCallbackInterface(void * a0, void * a1);
extern int __attribute__((stdcall)) XHVEngine_DoWork(void * a0);
extern int __attribute__((stdcall)) XHVEngine_RegisterLocalTalker(void * a0, int a1);
extern int __attribute__((stdcall)) XHVEngine_UnregisterLocalTalker(void * a0, int a1);
extern int __attribute__((stdcall)) XHVEngine_SetProcessingMode(void * a0, int a1, int a2);
extern int __attribute__((stdcall)) XHVEngine_GetProcessingMode(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XHVEngine_SetVoiceMask(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XHVEngine_GetLocalTalkerStatus(void * a0, int a1, void * a2);
extern int __attribute__((stdcall)) XHVEngine_RegisterRemoteTalker(void * a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XHVEngine_UnregisterRemoteTalker(void * a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XHVEngine_GetRemoteTalkers(void * a0, void * a1, void * a2);
extern int __attribute__((stdcall)) XHVEngine_SubmitIncomingVoicePacket(void * a0, RxdkXuid a1, void * a2, int a3);
extern int __attribute__((stdcall)) XHVEngine_IsTalking(void * a0, RxdkXuid a1);
extern int __attribute__((stdcall)) XHVEngine_SetMixBinMapping(void * a0, RxdkXuid a1, int a2, void * a3);
extern int __attribute__((stdcall)) XHVEngine_SetMixBinVolumes(void * a0, RxdkXuid a1, void * a2);
extern int __attribute__((stdcall)) XHVEngine_SetPlaybackPriority(void * a0, RxdkXuid a1, int a2, int a3);
extern int __attribute__((stdcall)) XHVEngine_SetMaxPlaybackStreamsCount(void * a0, int a1);
extern int __attribute__((stdcall)) XHVEngine_RegisterSpeechRecognitionBank(void * a0, void * a1);
extern int __attribute__((stdcall)) XHVEngine_SelectVocabulary(void * a0, int a1, int a2, void * a3);
extern int __attribute__((stdcall)) XHVEngine_VoiceMailRecord(void * a0, int a1, int a2, int a3, void * a4);
extern int __attribute__((stdcall)) XHVEngine_VoiceMailPlay(void * a0, int a1, int a2, void * a3, int a4);
extern int __attribute__((stdcall)) XHVEngine_VoiceMailStop(void * a0, int a1);
extern int __attribute__((stdcall)) XHVEngineCreate(void * a0, void * a1);

static int rxdk_xvoice_XVoiceQueueCreateMediaObject(void * a0, void * a1)
{
    return XVoiceQueueCreateMediaObject(a0, a1);
}

static int rxdk_xvoice_XVoiceSynchronizedQueueCreateMediaObject(void * a0, void * a1)
{
    return XVoiceSynchronizedQueueCreateMediaObject(a0, a1);
}

static int rxdk_xvoice_XVoiceCreateOneToOneEncoder(void * a0)
{
    return XVoiceCreateOneToOneEncoder(a0);
}

static int rxdk_xvoice_XVoiceCreateTwoToTwoEncoder(void * a0)
{
    return XVoiceCreateTwoToTwoEncoder(a0);
}

static int rxdk_xvoice_XVoiceCreateFourToFourFullEncoder(void * a0)
{
    return XVoiceCreateFourToFourFullEncoder(a0);
}

static int rxdk_xvoice_XVoiceCreateFourToFourRoundRobinEncoder(void * a0)
{
    return XVoiceCreateFourToFourRoundRobinEncoder(a0);
}

static int rxdk_xvoice_XVoiceCreateOneToOneDecoder(void * a0)
{
    return XVoiceCreateOneToOneDecoder(a0);
}

static int rxdk_xvoice_XVoiceCreateFourToFourFullDecoder(int a0, void * a1)
{
    return XVoiceCreateFourToFourFullDecoder(a0, a1);
}

static int rxdk_xvoice_XVoiceCreateFourToOneMixingDecoder(int a0, void * a1)
{
    return XVoiceCreateFourToOneMixingDecoder(a0, a1);
}

static int rxdk_xvoice_XVoiceCreateTwoToOneMixingDecoder(int a0, void * a1)
{
    return XVoiceCreateTwoToOneMixingDecoder(a0, a1);
}

static int rxdk_xvoice_XVoiceGetEncodedPacketEnergy(void * a0, void * a1)
{
    return XVoiceGetEncodedPacketEnergy(a0, a1);
}

static int rxdk_xvoice_XHVEngine_AddRef(void * a0)
{
    return XHVEngine_AddRef(a0);
}

static int rxdk_xvoice_XHVEngine_Release(void * a0)
{
    return XHVEngine_Release(a0);
}

static int rxdk_xvoice_XHVEngine_EnableProcessingMode(void * a0, int a1)
{
    return XHVEngine_EnableProcessingMode(a0, a1);
}

static int rxdk_xvoice_XHVEngine_SetCallbackInterface(void * a0, void * a1)
{
    return XHVEngine_SetCallbackInterface(a0, a1);
}

static int rxdk_xvoice_XHVEngine_GetCallbackInterface(void * a0, void * a1)
{
    return XHVEngine_GetCallbackInterface(a0, a1);
}

static int rxdk_xvoice_XHVEngine_DoWork(void * a0)
{
    return XHVEngine_DoWork(a0);
}

static int rxdk_xvoice_XHVEngine_RegisterLocalTalker(void * a0, int a1)
{
    return XHVEngine_RegisterLocalTalker(a0, a1);
}

static int rxdk_xvoice_XHVEngine_UnregisterLocalTalker(void * a0, int a1)
{
    return XHVEngine_UnregisterLocalTalker(a0, a1);
}

static int rxdk_xvoice_XHVEngine_SetProcessingMode(void * a0, int a1, int a2)
{
    return XHVEngine_SetProcessingMode(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_GetProcessingMode(void * a0, int a1, void * a2)
{
    return XHVEngine_GetProcessingMode(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_SetVoiceMask(void * a0, int a1, void * a2)
{
    return XHVEngine_SetVoiceMask(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_GetLocalTalkerStatus(void * a0, int a1, void * a2)
{
    return XHVEngine_GetLocalTalkerStatus(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_RegisterRemoteTalker(void * a0, RxdkXuid a1)
{
    return XHVEngine_RegisterRemoteTalker(a0, a1);
}

static int rxdk_xvoice_XHVEngine_UnregisterRemoteTalker(void * a0, RxdkXuid a1)
{
    return XHVEngine_UnregisterRemoteTalker(a0, a1);
}

static int rxdk_xvoice_XHVEngine_GetRemoteTalkers(void * a0, void * a1, void * a2)
{
    return XHVEngine_GetRemoteTalkers(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_SubmitIncomingVoicePacket(void * a0, RxdkXuid a1, void * a2, int a3)
{
    return XHVEngine_SubmitIncomingVoicePacket(a0, a1, a2, a3);
}

static int rxdk_xvoice_XHVEngine_IsTalking(void * a0, RxdkXuid a1)
{
    return XHVEngine_IsTalking(a0, a1);
}

static int rxdk_xvoice_XHVEngine_SetMixBinMapping(void * a0, RxdkXuid a1, int a2, void * a3)
{
    return XHVEngine_SetMixBinMapping(a0, a1, a2, a3);
}

static int rxdk_xvoice_XHVEngine_SetMixBinVolumes(void * a0, RxdkXuid a1, void * a2)
{
    return XHVEngine_SetMixBinVolumes(a0, a1, a2);
}

static int rxdk_xvoice_XHVEngine_SetPlaybackPriority(void * a0, RxdkXuid a1, int a2, int a3)
{
    return XHVEngine_SetPlaybackPriority(a0, a1, a2, a3);
}

static int rxdk_xvoice_XHVEngine_SetMaxPlaybackStreamsCount(void * a0, int a1)
{
    return XHVEngine_SetMaxPlaybackStreamsCount(a0, a1);
}

static int rxdk_xvoice_XHVEngine_RegisterSpeechRecognitionBank(void * a0, void * a1)
{
    return XHVEngine_RegisterSpeechRecognitionBank(a0, a1);
}

static int rxdk_xvoice_XHVEngine_SelectVocabulary(void * a0, int a1, int a2, void * a3)
{
    return XHVEngine_SelectVocabulary(a0, a1, a2, a3);
}

static int rxdk_xvoice_XHVEngine_VoiceMailRecord(void * a0, int a1, int a2, int a3, void * a4)
{
    return XHVEngine_VoiceMailRecord(a0, a1, a2, a3, a4);
}

static int rxdk_xvoice_XHVEngine_VoiceMailPlay(void * a0, int a1, int a2, void * a3, int a4)
{
    return XHVEngine_VoiceMailPlay(a0, a1, a2, a3, a4);
}

static int rxdk_xvoice_XHVEngine_VoiceMailStop(void * a0, int a1)
{
    return XHVEngine_VoiceMailStop(a0, a1);
}

static int rxdk_xvoice_XHVEngineCreate(void * a0, void * a1)
{
    return XHVEngineCreate(a0, a1);
}

static void *xvoice_load(const char *name, int flags, char **err, void *ud)
{
    (void)flags; (void)err; (void)ud;
    if (!name) return NULL;
    if (strcmp(name, "xvoice") && strcmp(name, "xvoice.dll")) return NULL;
    return (void *)(unsigned long)1482051401u;
}

static void *xvoice_symbol(void *handle, const char *name, char **err, void *ud)
{
    (void)err; (void)ud;
    if (handle != (void *)(unsigned long)1482051401u || !name) return NULL;
    if (!strcmp(name, "rxdk_xvoice_XVoiceQueueCreateMediaObject")) return (void *)&rxdk_xvoice_XVoiceQueueCreateMediaObject;
    if (!strcmp(name, "rxdk_xvoice_XVoiceSynchronizedQueueCreateMediaObject")) return (void *)&rxdk_xvoice_XVoiceSynchronizedQueueCreateMediaObject;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateOneToOneEncoder")) return (void *)&rxdk_xvoice_XVoiceCreateOneToOneEncoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateTwoToTwoEncoder")) return (void *)&rxdk_xvoice_XVoiceCreateTwoToTwoEncoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateFourToFourFullEncoder")) return (void *)&rxdk_xvoice_XVoiceCreateFourToFourFullEncoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateFourToFourRoundRobinEncoder")) return (void *)&rxdk_xvoice_XVoiceCreateFourToFourRoundRobinEncoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateOneToOneDecoder")) return (void *)&rxdk_xvoice_XVoiceCreateOneToOneDecoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateFourToFourFullDecoder")) return (void *)&rxdk_xvoice_XVoiceCreateFourToFourFullDecoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateFourToOneMixingDecoder")) return (void *)&rxdk_xvoice_XVoiceCreateFourToOneMixingDecoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceCreateTwoToOneMixingDecoder")) return (void *)&rxdk_xvoice_XVoiceCreateTwoToOneMixingDecoder;
    if (!strcmp(name, "rxdk_xvoice_XVoiceGetEncodedPacketEnergy")) return (void *)&rxdk_xvoice_XVoiceGetEncodedPacketEnergy;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_AddRef")) return (void *)&rxdk_xvoice_XHVEngine_AddRef;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_Release")) return (void *)&rxdk_xvoice_XHVEngine_Release;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_EnableProcessingMode")) return (void *)&rxdk_xvoice_XHVEngine_EnableProcessingMode;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetCallbackInterface")) return (void *)&rxdk_xvoice_XHVEngine_SetCallbackInterface;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_GetCallbackInterface")) return (void *)&rxdk_xvoice_XHVEngine_GetCallbackInterface;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_DoWork")) return (void *)&rxdk_xvoice_XHVEngine_DoWork;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_RegisterLocalTalker")) return (void *)&rxdk_xvoice_XHVEngine_RegisterLocalTalker;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_UnregisterLocalTalker")) return (void *)&rxdk_xvoice_XHVEngine_UnregisterLocalTalker;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetProcessingMode")) return (void *)&rxdk_xvoice_XHVEngine_SetProcessingMode;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_GetProcessingMode")) return (void *)&rxdk_xvoice_XHVEngine_GetProcessingMode;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetVoiceMask")) return (void *)&rxdk_xvoice_XHVEngine_SetVoiceMask;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_GetLocalTalkerStatus")) return (void *)&rxdk_xvoice_XHVEngine_GetLocalTalkerStatus;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_RegisterRemoteTalker")) return (void *)&rxdk_xvoice_XHVEngine_RegisterRemoteTalker;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_UnregisterRemoteTalker")) return (void *)&rxdk_xvoice_XHVEngine_UnregisterRemoteTalker;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_GetRemoteTalkers")) return (void *)&rxdk_xvoice_XHVEngine_GetRemoteTalkers;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SubmitIncomingVoicePacket")) return (void *)&rxdk_xvoice_XHVEngine_SubmitIncomingVoicePacket;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_IsTalking")) return (void *)&rxdk_xvoice_XHVEngine_IsTalking;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetMixBinMapping")) return (void *)&rxdk_xvoice_XHVEngine_SetMixBinMapping;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetMixBinVolumes")) return (void *)&rxdk_xvoice_XHVEngine_SetMixBinVolumes;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetPlaybackPriority")) return (void *)&rxdk_xvoice_XHVEngine_SetPlaybackPriority;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SetMaxPlaybackStreamsCount")) return (void *)&rxdk_xvoice_XHVEngine_SetMaxPlaybackStreamsCount;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_RegisterSpeechRecognitionBank")) return (void *)&rxdk_xvoice_XHVEngine_RegisterSpeechRecognitionBank;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_SelectVocabulary")) return (void *)&rxdk_xvoice_XHVEngine_SelectVocabulary;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_VoiceMailRecord")) return (void *)&rxdk_xvoice_XHVEngine_VoiceMailRecord;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_VoiceMailPlay")) return (void *)&rxdk_xvoice_XHVEngine_VoiceMailPlay;
    if (!strcmp(name, "rxdk_xvoice_XHVEngine_VoiceMailStop")) return (void *)&rxdk_xvoice_XHVEngine_VoiceMailStop;
    if (!strcmp(name, "rxdk_xvoice_XHVEngineCreate")) return (void *)&rxdk_xvoice_XHVEngineCreate;
    return NULL;
}

static void *xvoice_close(void *handle, void *ud)
{
    (void)handle; (void)ud;
    return NULL;
}

void rxdk_bind_xvoice_register(void)
{
    mono_dl_fallback_register(xvoice_load, xvoice_symbol, xvoice_close, NULL);
}
